# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-11-24 00:03
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.contenttypes.models import ContentType
from core.models import DlpLibrary


def edit_content_type_ids(apps, schema_editor):
    
    dlp_library_content_type = ContentType.objects.get_for_model(DlpLibrary)
    TaggedItem = apps.get_model('taggit', 'TaggedItem')
    
    TaggedItem.objects.filter(content_type_id = 3).update(content_type_id = dlp_library_content_type)

class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_historicaltag'),
        ('core', '0024_auto_20171121_1504'),
        ('sisyphus', '0003_auto_20171122_1034'),
    ]

    operations = [
        migrations.RunPython(edit_content_type_ids),
    ]