# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-03-06 21:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_historicaltag_history_change_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltag',
            name='history_change_reason',
        ),
    ]
