# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-06 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_remove_historicaltag_history_change_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltag',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
