# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-03-18 19:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0007_historicaltag_history_change_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltag',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalTag',
        ),
    ]
