# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-29 17:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0008_auto_20190318_1215'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='taggeditem',
            index_together=set([]),
        ),
        migrations.RemoveField(
            model_name='taggeditem',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='taggeditem',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='TaggedItem',
        ),
    ]
