# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-12 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenx', '0001_initial'),
        ('core', '0002_auto_20190712_1140'),
        ('dlp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dlplibrary',
            name='relates_to_tenx',
            field=models.ManyToManyField(blank=True, to='tenx.TenxLibrary', verbose_name='Relates to (Tenx)'),
        ),
        migrations.AddField(
            model_name='dlplibrary',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Sample', verbose_name='Primary Sample'),
        ),
        migrations.AddField(
            model_name='dlplane',
            name='sequencing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dlp.DlpSequencing', verbose_name='Sequencing'),
        ),
        migrations.AlterUniqueTogether(
            name='dlpsequencing',
            unique_together=set([('library', 'sequencing_center', 'sequencing_instrument')]),
        ),
    ]
