# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-09 18:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dlplane',
            table=None,
        ),
        migrations.AlterModelTable(
            name='dlplibrary',
            table=None,
        ),
        migrations.AlterModelTable(
            name='dlplibraryconstructioninformation',
            table=None,
        ),
        migrations.AlterModelTable(
            name='dlplibraryquantificationandstorage',
            table=None,
        ),
        migrations.AlterModelTable(
            name='dlplibrarysampledetail',
            table=None,
        ),
        migrations.AlterModelTable(
            name='dlpsequencing',
            table=None,
        ),
    ]
