# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-26 22:21
from __future__ import unicode_literals

from django.db import migrations


def update_missing_lane_requested_date(apps, schema_editor):
    DlpSequencing = apps.get_model('dlp','dlpsequencing')

    for seq in DlpSequencing.objects.filter(lane_requested_date=None):
        if seq.dlplane_set.all():
            try:
                latest_date = max([l.sequencing_date for l in seq.dlplane_set.all()])
            except:
                print("NO LANES WITH VALID DATE {}".format(seq.id))
                continue
            seq.lane_requested_date = latest_date
            seq.save()
            print("UPDATED LANE REQUESTED DATE TO {} FOR {}".format(str(latest_date), seq.id))
        else:
            print("MISSING LANE REQUESTED DATE WITH 0 LANE IN {}".format(seq.id))

class Migration(migrations.Migration):
    dependencies = [
        ('dlp', '0002_auto_20190712_1140'),
    ]

    operations = [
        migrations.RunPython(update_missing_lane_requested_date)
    ]
