# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-16 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlp', '0002_auto_20190509_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dlpsequencing',
            name='number_of_lanes_requested',
            field=models.PositiveIntegerField(default=1, verbose_name='Sequencing Goal'),
        ),
        migrations.AlterField(
            model_name='historicaldlpsequencing',
            name='number_of_lanes_requested',
            field=models.PositiveIntegerField(default=1, verbose_name='Sequencing Goal'),
        ),
    ]
