# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-12 00:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlp', '0003_auto_20190516_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dlpsequencing',
            name='analysis',
        ),
    ]
