# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-12-12 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlp', '0005_auto_20191212_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dlpsequencing',
            name='external_gsc_id',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='External GSC ID'),
        ),
        migrations.AlterField(
            model_name='historicaldlpsequencing',
            name='external_gsc_id',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='External GSC ID'),
        ),
    ]
