# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-05-06 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlp', '0007_auto_20200327_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='dlplibrary',
            name='normal_sample_id',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Normal sample ID'),
        ),
        migrations.AddField(
            model_name='dlplibrary',
            name='normal_sample_library_id',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Normal sample library ID'),
        ),
        migrations.AddField(
            model_name='dlplibrary',
            name='normal_sample_type',
            field=models.CharField(blank=True, choices=[('D', 'DLP+ library'), ('W', 'GSC WGS library')], default=None, max_length=50, null=True, verbose_name='Normal sample type'),
        ),
        migrations.AddField(
            model_name='historicaldlplibrary',
            name='normal_sample_id',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Normal sample ID'),
        ),
        migrations.AddField(
            model_name='historicaldlplibrary',
            name='normal_sample_library_id',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Normal sample library ID'),
        ),
        migrations.AddField(
            model_name='historicaldlplibrary',
            name='normal_sample_type',
            field=models.CharField(blank=True, choices=[('D', 'DLP+ library'), ('W', 'GSC WGS library')], default=None, max_length=50, null=True, verbose_name='Normal sample type'),
        ),
    ]
