# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 20:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='pub_date',
            new_name='create_date',
        ),
    ]
