# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-01 22:08
from __future__ import unicode_literals

import core.helpers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenxPool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gsc_pool_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='GSC Pool Name')),
                ('construction_location', models.CharField(blank=True, choices=[('BCCAGSC', 'GSC'), ('UBCBRC', 'UBC')], max_length=50, null=True, verbose_name='Construction Location')),
                ('constructed_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Constructed By')),
                ('constructed_date', models.DateField(blank=True, null=True, verbose_name='Construction Date')),
                ('libraries', models.ManyToManyField(blank=True, to='core.TenxLibrary')),
            ],
            bases=(models.Model, core.helpers.FieldValue),
        ),
        migrations.AddField(
            model_name='historicaltenxsequencing',
            name='tenx_pool',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.TenxPool'),
        ),
        migrations.AddField(
            model_name='tenxsequencing',
            name='tenx_pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.TenxPool'),
        ),
    ]
