# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-04 17:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190401_1508'),
    ]

    database_operations = [
        migrations.AlterModelTable(name='PbalLibrary', table='pbal_pballibrary'),
        migrations.AlterModelTable(name='PbalLibrarySampleDetail', table='pbal_pballibrarysampledetail'),
        migrations.AlterModelTable(name='PbalLibraryConstructionInformation', table='pbal_pballibraryconstructioninformation'),
        migrations.AlterModelTable(name='PbalLibraryQuantificationAndStorage', table='pbal_pballibraryquantificationandstorage'),
        migrations.AlterModelTable(name='PbalSequencing', table='pbal_pbalsequencing'),
        migrations.AlterModelTable(name='PbalLane', table='pbal_pballane'),
        migrations.AlterModelTable(name='Plate', table='pbal_plate'),

    ]



    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
        )
    ]
