# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-09 21:19
from __future__ import unicode_literals

import core.helpers
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pbal', '0002_auto_20190404_1313'),
        ('core', '0004_auto_20190404_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_type', models.CharField(blank=True, choices=[('DLP', 'DLP'), ('PBAL', 'PBAL'), ('TENX', 'TenX')], max_length=50, verbose_name='Input Type')),
                ('version', models.CharField(max_length=50, null=True, verbose_name='Analysis Version')),
                ('jira_ticket', models.CharField(max_length=50, null=True, verbose_name='Analysis Jira Ticket')),
                ('run_status', models.CharField(choices=[('idle', 'Idle'), ('error', 'Error'), ('running', 'Running'), ('archiving', 'Archiving'), ('complete', 'Complete'), ('align_complete', 'Align Complete'), ('hmmcopy_complete', 'Hmmcopy Complete')], default='idle', max_length=50, verbose_name='Run Status')),
                ('last_updated_date', models.DateTimeField(auto_now=True, verbose_name='Last Updated Date')),
                ('submission_date', models.DateField(default=datetime.date.today, verbose_name='Analysis Submission Date')),
                ('description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Description')),
                ('dlp_library', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.DlpLibrary')),
                ('pbal_library', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pbal.PbalLibrary')),
                ('tenx_library', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.TenxLibrary')),
            ],
            options={
                'ordering': ['id'],
            },
            bases=(models.Model, core.helpers.FieldValue),
        ),
        migrations.AddField(
            model_name='dlpsequencing',
            name='analysis',
            field=models.ManyToManyField(blank=True, to='core.Analysis', verbose_name='Analysis'),
        ),
        migrations.AddField(
            model_name='tenxsequencing',
            name='analysis',
            field=models.ManyToManyField(blank=True, to='core.Analysis', verbose_name='Analysis'),
        ),
    ]
