# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-12 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170526_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Sample', verbose_name='Primary Sample'),
        ),
    ]
