# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-10 23:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_analysis_tenx_lanes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltenxsequencing',
            name='adapter',
        ),
        migrations.RemoveField(
            model_name='historicaltenxsequencing',
            name='format_for_data_submission',
        ),
        migrations.RemoveField(
            model_name='historicaltenxsequencing',
            name='gsc_library_id',
        ),
        migrations.RemoveField(
            model_name='historicaltenxsequencing',
            name='index_read1_length',
        ),
        migrations.RemoveField(
            model_name='historicaltenxsequencing',
            name='index_read2_length',
        ),
        migrations.RemoveField(
            model_name='historicaltenxsequencing',
            name='index_read_type',
        ),
        migrations.RemoveField(
            model_name='historicaltenxsequencing',
            name='read1_length',
        ),
        migrations.RemoveField(
            model_name='historicaltenxsequencing',
            name='read2_length',
        ),
        migrations.RemoveField(
            model_name='historicaltenxsequencing',
            name='read_type',
        ),
        migrations.RemoveField(
            model_name='historicaltenxsequencing',
            name='sequencing_output_mode',
        ),
        migrations.RemoveField(
            model_name='historicaltenxsequencing',
            name='short_description_of_submission',
        ),
        migrations.RemoveField(
            model_name='tenxsequencing',
            name='adapter',
        ),
        migrations.RemoveField(
            model_name='tenxsequencing',
            name='format_for_data_submission',
        ),
        migrations.RemoveField(
            model_name='tenxsequencing',
            name='gsc_library_id',
        ),
        migrations.RemoveField(
            model_name='tenxsequencing',
            name='index_read1_length',
        ),
        migrations.RemoveField(
            model_name='tenxsequencing',
            name='index_read2_length',
        ),
        migrations.RemoveField(
            model_name='tenxsequencing',
            name='index_read_type',
        ),
        migrations.RemoveField(
            model_name='tenxsequencing',
            name='read1_length',
        ),
        migrations.RemoveField(
            model_name='tenxsequencing',
            name='read2_length',
        ),
        migrations.RemoveField(
            model_name='tenxsequencing',
            name='read_type',
        ),
        migrations.RemoveField(
            model_name='tenxsequencing',
            name='relates_to',
        ),
        migrations.RemoveField(
            model_name='tenxsequencing',
            name='sequencing_output_mode',
        ),
        migrations.RemoveField(
            model_name='tenxsequencing',
            name='short_description_of_submission',
        ),
        migrations.AlterField(
            model_name='tenxsequencing',
            name='library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.TenxLibrary', verbose_name='Library'),
        ),
    ]
