# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-09 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170612_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='sublibraryinformation',
            name='sample_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Sample', verbose_name='Sample_ID'),
        ),
    ]
