# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-09 18:00
from __future__ import unicode_literals

from django.db import migrations

def move_sampleID_TO_sublibraryinformation_FROM_library(apps, schema_editor):
    Library = apps.get_model('core', 'Library')
    for library in Library.objects.all():
        for sublibrary in library.sublibraryinformation_set.all():
            sublibrary.sample_id = library.sample
            sublibrary.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sublibraryinformation_sample_id'),
    ]

    operations = [
        # data migration
       migrations.RunPython(move_sampleID_TO_sublibraryinformation_FROM_library)
    ]


