# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-23 21:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190723_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpipelinetag',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='PipelineTag',
        ),
        migrations.DeleteModel(
            name='HistoricalPipelineTag',
        ),
    ]
