# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-24 19:10
from __future__ import unicode_literals

from django.db import migrations



# Trigger save of all the dlp analysis with no request lane date
def trigger_save_dlp_sequencing(apps, schema_editor):
    DlpSequencing = apps.get_model('dlp', 'dlpsequencing')
    for s in DlpSequencing.objects.all():
        if s.number_of_lanes_requested is 1 and not s.lane_requested_date:
            s.lane_requested_date = s.submission_date
            s.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190723_1443'),
    ]

    operations = [
        migrations.RunPython(trigger_save_dlp_sequencing)
    ]
