# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-17 19:31
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190412_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltenxlane',
            name='tantalus_datasets',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='tenxlane',
            name='tantalus_datasets',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None),
        ),
    ]
