# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-13 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20191112_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalsampleinformation',
            name='receptor_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Receptor status'),
        ),
        migrations.AlterField(
            model_name='additionalsampleinformation',
            name='sample_treatment_status',
            field=models.CharField(blank=True, choices=[('PR', 'Pre-treatment'), ('IN', 'In-treatment'), ('PO', 'Post-treatment'), ('NA', 'N/A'), ('UN', 'Unknown')], max_length=50, null=True, verbose_name='Sample treatment status'),
        ),
        migrations.AlterField(
            model_name='historicaladditionalsampleinformation',
            name='receptor_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Receptor status'),
        ),
        migrations.AlterField(
            model_name='historicaladditionalsampleinformation',
            name='sample_treatment_status',
            field=models.CharField(blank=True, choices=[('PR', 'Pre-treatment'), ('IN', 'In-treatment'), ('PO', 'Post-treatment'), ('NA', 'N/A'), ('UN', 'Unknown')], max_length=50, null=True, verbose_name='Sample treatment status'),
        ),
    ]
