# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-17 20:57
from __future__ import unicode_literals

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190417_1231'),
    ]


    operations = [
        migrations.AlterField(
            model_name='historicaltenxlibrary',
            name='experimental_condition',
            field=models.CharField(blank=True, max_length=1025, null=True, verbose_name='Experimental condition'),
        ),
        migrations.AlterField(
            model_name='tenxlibrary',
            name='experimental_condition',
            field=models.CharField(blank=True, max_length=1025, null=True, verbose_name='Experimental condition'),
        ),
    ]
