# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-17 20:57
from __future__ import unicode_literals

from django.db import migrations, models



def update_experimental_condition(apps, schema_editor):
    TenxLibrary = apps.get_model('core', 'TenxLibrary')

    for library in TenxLibrary.objects.all():
        metadata_list = []
        for condition in library.tenxcondition_set.all():
            metadata = {
                "Condition" : condition.experimental_condition,
                "Enzyme": condition.enzyme,
                "Digestion_temperature": condition.digestion_temperature,
                "Live_dead": condition.live_dead,
                "cells_targeted": condition.cells_targeted,
            }
            metadata_list.append(" | ".join([str(key) + ": " + str(value) + "" for key,value in metadata.items()]))
        if metadata_list:
            print(library.name)
            print(str(library.experimental_condition) + "\n".join(metadata_list))
            library.experimental_condition = str("\n".join(metadata_list))
            library.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190417_1231'),
    ]


    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_opeations,

        )
        migrations.AlterField(
            model_name='historicaltenxlibrary',
            name='experimental_condition',
            field=models.CharField(blank=True, max_length=1025, null=True, verbose_name='Experimental condition'),
        ),
        migrations.AlterField(
            model_name='tenxlibrary',
            name='experimental_condition',
            field=models.CharField(blank=True, max_length=1025, null=True, verbose_name='Experimental condition'),
        ),
        migrations.RunPython(update_experimental_condition)
    ]
