# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-28 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

def get_existing_chipregionmetadata_fields_and_create_metadatafield_models(apps, schema_editor):
    ChipRegionMetadata = apps.get_model('core', 'ChipRegionMetadata')
    MetadataField = apps.get_model('core', 'MetadataField')
    existing_fields = ChipRegionMetadata.objects.all().values_list('metadata_field_old', flat=True).distinct()
    for field in existing_fields:
        metadatafield = MetadataField(field=field)
        metadatafield.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20170726_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetadataField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=50, verbose_name='Metadata key')),
            ],
        ),
        migrations.RenameField(
            model_name='ChipRegionMetadata',
            old_name='metadata_field',
            new_name='metadata_field_old'
        ),
        migrations.RunPython(get_existing_chipregionmetadata_fields_and_create_metadatafield_models),
    ]
