# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-18 18:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20190417_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltenxcondition',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaltenxcondition',
            name='library',
        ),
        migrations.RemoveField(
            model_name='historicaltenxcondition',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='tenxcondition',
            name='library',
        ),
        migrations.RemoveField(
            model_name='tenxcondition',
            name='sample',
        ),
        migrations.DeleteModel(
            name='HistoricalTenxCondition',
        ),
        migrations.DeleteModel(
            name='TenxCondition',
        ),
    ]
