# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-18 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20190418_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenxpool',
            name='pool_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Pool Name'),
        ),
    ]
