# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-25 17:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20190418_1406'),
    ]

    database_operations = [
        migrations.AlterModelTable(name='TenxChip', table='tenx_tenxchip'),
        migrations.AlterModelTable(name='TenxLibrary', table='tenx_tenxlibrary'),
        migrations.AlterModelTable(name='TenxPool', table='tenx_tenxpool'),
        migrations.AlterModelTable(name='TenxLibrarySampleDetail', table='tenx_tenxlibrarysampledetail'),
        migrations.AlterModelTable(name='TenxLibraryConstructionInformation', table='tenx_tenxlibraryconstructioninformation'),
        migrations.AlterModelTable(name='TenxSequencing', table='tenx_tenxsequencing'),
        migrations.AlterModelTable(name='TenxLane', table='tenx_tenxlane'),
        migrations.AlterModelTable(name='TenxLibraryQuantificationAndStorage', table='tenx_tenxlibraryquantificationandstorage'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations
        )
    ]
