# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-06 19:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20190418_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dlplibrarysampledetail',
            name='sample_spot_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Sample spot date'),
        ),
        migrations.AlterField(
            model_name='historicaldlplibrarysampledetail',
            name='sample_spot_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Sample spot date'),
        ),
    ]
