# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-13 19:14
from __future__ import unicode_literals

import core.helpers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20170731_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_cell_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Flow cell/Lane ID')),
                ('path_to_archive', models.CharField(blank=True, max_length=150, null=True, verbose_name='Path to archive')),
                ('sequencing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Sequencing', verbose_name='Sequencing')),
            ],
            bases=(models.Model, core.helpers.FieldValue),
        ),
    ]
