# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-06 22:14
from __future__ import unicode_literals

from django.db import migrations, models

def format_tenxlibrary_naming(apps, schema_editor):
    tenx_library = apps.get_model('core', 'TenxLibrary')
    for library in tenx_library.objects.all():
        if not library.name.startswith('TENX'):
            library.name = "_".join(["SCRNA10X", library.chips.lab_name, "CHIP" + str(library.chips.pk).zfill(4), str(library.chip_well).zfill(4)])
        library.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20190506_1207'),
    ]

    operations = [
    	migrations.RunPython(format_tenxlibrary_naming),
    ]
