# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-13 20:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_sequencing_to_lane'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sequencingdetail',
            name='flow_cell_id',
        ),
        migrations.RemoveField(
            model_name='sequencingdetail',
            name='path_to_archive',
        ),
    ]
