# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-09 17:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20190506_1402'),
    ]

    database_operations = [
        migrations.AlterModelTable(name='DlpLibrary', table='dlp_dlplibrary'),
        migrations.AlterModelTable(name='DlpLibrarySampleDetail', table='dlp_dlplibrarysampledetail'),
        migrations.AlterModelTable(name='DlpLibraryConstructionInformation', table='dlp_dlplibraryconstructioninformation'),
        migrations.AlterModelTable(name='DlpLibraryQuantificationAndStorage', table='dlp_dlplibraryquantificationandstorage'),
        migrations.AlterModelTable(name='DlpSequencing', table='dlp_dlpsequencing'),
        migrations.AlterModelTable(name='DlpLane', table='dlp_dlplane'),
    ]


    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations
        )
    ]
