# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-15 22:10
from __future__ import unicode_literals

from django.db import migrations


def remove_null_lanes(apps, schema_editor):
    Lane = apps.get_model('core', 'Lane')
    Lane.objects.filter(flow_cell_id='').delete()
    Lane.objects.filter(flow_cell_id__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20170913_1338'),
    ]

    operations = [
        migrations.RunPython(remove_null_lanes),
    ]
