# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-09 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenx', '0004_auto_20190509_1122'),
        ('pbal', '0005_auto_20190509_1122'),
        ('sisyphus', '0004_auto_20190509_1122'),
        ('core', '0019_rename_table_dlp'),
    ]

    state_operations = [
        migrations.RemoveField(
            model_name='dlplane',
            name='sequencing',
        ),
        migrations.RemoveField(
            model_name='dlplibrary',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='dlplibrary',
            name='relates_to_dlp',
        ),
        migrations.RemoveField(
            model_name='dlplibrary',
            name='relates_to_tenx',
        ),
        migrations.RemoveField(
            model_name='dlplibrary',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='dlplibraryconstructioninformation',
            name='library',
        ),
        migrations.RemoveField(
            model_name='dlplibraryquantificationandstorage',
            name='library',
        ),
        migrations.RemoveField(
            model_name='dlplibrarysampledetail',
            name='library',
        ),
        migrations.AlterUniqueTogether(
            name='dlpsequencing',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='dlpsequencing',
            name='analysis',
        ),
        migrations.RemoveField(
            model_name='dlpsequencing',
            name='library',
        ),
        migrations.RemoveField(
            model_name='dlpsequencing',
            name='relates_to',
        ),
        migrations.RemoveField(
            model_name='historicaldlplane',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaldlplane',
            name='sequencing',
        ),
        migrations.RemoveField(
            model_name='historicaldlplibrary',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaldlplibrary',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='historicaldlplibraryconstructioninformation',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaldlplibraryconstructioninformation',
            name='library',
        ),
        migrations.RemoveField(
            model_name='historicaldlplibraryquantificationandstorage',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaldlplibraryquantificationandstorage',
            name='library',
        ),
        migrations.RemoveField(
            model_name='historicaldlplibrarysampledetail',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaldlplibrarysampledetail',
            name='library',
        ),
        migrations.RemoveField(
            model_name='historicaldlpsequencing',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaldlpsequencing',
            name='library',
        ),
        migrations.AlterField(
            model_name='analysis',
            name='dlp_library',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dlp.DlpLibrary'),
        ),
        migrations.AlterField(
            model_name='chipregion',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dlp.DlpLibrary', verbose_name='Library'),
        ),
        migrations.AlterField(
            model_name='historicalchipregion',
            name='library',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dlp.DlpLibrary', verbose_name='Library'),
        ),
        migrations.AlterField(
            model_name='historicalsublibraryinformation',
            name='library',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dlp.DlpLibrary', verbose_name='Library'),
        ),
        migrations.AlterField(
            model_name='sublibraryinformation',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dlp.DlpLibrary', verbose_name='Library'),
        ),
        migrations.DeleteModel(
            name='DlpLane',
        ),
        migrations.DeleteModel(
            name='DlpLibrary',
        ),
        migrations.DeleteModel(
            name='DlpLibraryConstructionInformation',
        ),
        migrations.DeleteModel(
            name='DlpLibraryQuantificationAndStorage',
        ),
        migrations.DeleteModel(
            name='DlpLibrarySampleDetail',
        ),
        migrations.DeleteModel(
            name='DlpSequencing',
        ),
        migrations.DeleteModel(
            name='HistoricalDlpLane',
        ),
        migrations.DeleteModel(
            name='HistoricalDlpLibrary',
        ),
        migrations.DeleteModel(
            name='HistoricalDlpLibraryConstructionInformation',
        ),
        migrations.DeleteModel(
            name='HistoricalDlpLibraryQuantificationAndStorage',
        ),
        migrations.DeleteModel(
            name='HistoricalDlpLibrarySampleDetail',
        ),
        migrations.DeleteModel(
            name='HistoricalDlpSequencing',
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=state_operations
        )
    ]
