# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-12 00:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlp', '0004_remove_dlpsequencing_analysis'),
        ('core', '0020_auto_20190509_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='dlp_library',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='pbal_library',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='tenx_lanes',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='tenx_library',
        ),
        migrations.DeleteModel(
            name='Analysis',
        ),
    ]
