# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-11-21 23:04
from __future__ import unicode_literals

import core.helpers
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_historicaltag'),
        ('core', '0023_auto_20171116_1353'),
        ('sisyphus', '0002_auto_20171121_1707'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Library',
            new_name='DlpLibrary',   
        ),
        migrations.RenameModel(
            old_name='Sequencing',
            new_name='DlpSequencing',    
        ),
        migrations.RenameModel(
            old_name='Lane',
            new_name='DlpLane',
        ),
        migrations.RenameModel(
            old_name='LibraryConstructionInformation',
            new_name='DlpLibraryConstructionInformation',
        ),
        migrations.RenameModel(
            old_name='LibraryQuantificationAndStorage',
            new_name='DlpLibraryQuantificationAndStorage',
        ),
        migrations.RenameModel(
            old_name='LibrarySampleDetail',
            new_name='DlpLibrarySampleDetail',
        ),
        migrations.RenameModel(
            old_name='SequencingDetail',
            new_name='DlpSequencingDetail',
        ),
        migrations.RenameModel(
            old_name='HistoricalLibrary',
            new_name='HistoricalDlpLibrary',
        ),
        migrations.RenameModel(
            old_name='HistoricalSequencing',
            new_name='HistoricalDlpSequencing',
        ),
        migrations.AlterModelOptions(
            name='historicaldlplibrary',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical dlp library'},
        ),
        migrations.AlterModelOptions(
            name='historicaldlpsequencing',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical dlp sequencing'},
        ),
        migrations.RenameField(
            model_name='pballibraryconstructioninformation',
            old_name='library_prep_date',
            new_name='submission_date',
        ),
        migrations.RenameField(
            model_name='tenxlibraryconstructioninformation',
            old_name='library_prep_date',
            new_name='submission_date',
        ),
        migrations.AlterField(
            model_name='pballibraryconstructioninformation',
            name='submission_date',
            field=models.DateField(blank=True, null=True, verbose_name='Submission date'),
        ),
        migrations.AlterField(
            model_name='tenxlibraryconstructioninformation',
            name='submission_date',
            field=models.DateField(blank=True, null=True, verbose_name='Submission date'),
        ),
        migrations.AlterField(
            model_name='chipregion',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DlpLibrary', verbose_name='Library'),
        ),
        migrations.AlterField(
            model_name='dlplane',
            name='sequencing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DlpSequencing', verbose_name='Sequencing'),
        ),
        migrations.AlterField(
            model_name='dlplibraryconstructioninformation',
            name='library',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.DlpLibrary', verbose_name='Library'),
        ),
        migrations.AlterField(
            model_name='dlplibraryquantificationandstorage',
            name='library',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.DlpLibrary', verbose_name='Library'),
        ),
        migrations.AlterField(
            model_name='dlplibrarysampledetail',
            name='library',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.DlpLibrary', verbose_name='Library'),
        ),
        migrations.AlterField(
            model_name='dlpsequencingdetail',
            name='sequencing',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.DlpSequencing', verbose_name='Sequencing'),
        ),
        migrations.AlterField(
            model_name='historicaldlpsequencing',
            name='library',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.DlpLibrary'),
        ),
        migrations.AlterField(
            model_name='pballibrary',
            name='relates_to',
            field=models.ManyToManyField(blank=True, null=True, to='core.DlpLibrary', verbose_name='Relates to'),
        ),
        migrations.AlterField(
            model_name='sublibraryinformation',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DlpLibrary', verbose_name='Library'),
        ),
        migrations.AlterField(
            model_name='tenxlibrary',
            name='relates_to',
            field=models.ManyToManyField(blank=True, null=True, to='core.DlpLibrary', verbose_name='Relates to'),
        ),
        migrations.AlterField(
            model_name='tenxlibraryconstructioninformation',
            name='library_construction_method',
            field=models.CharField(blank=True, default='10x Genomics', max_length=50, null=True, verbose_name='Library construction method'),
        ),
        migrations.AlterField(
            model_name='dlpsequencing',
            name='read1_length',
            field=models.IntegerField(blank=True, default=150, null=True, verbose_name='Read1 length'),
        ),
        migrations.AlterField(
            model_name='dlpsequencing',
            name='read2_length',
            field=models.IntegerField(blank=True, default=150, null=True, verbose_name='Read2 length'),
        ),
        migrations.AlterField(
            model_name='historicaldlpsequencing',
            name='read1_length',
            field=models.IntegerField(blank=True, default=150, null=True, verbose_name='Read1 length'),
        ),
        migrations.AlterField(
            model_name='historicaldlpsequencing',
            name='read2_length',
            field=models.IntegerField(blank=True, default=150, null=True, verbose_name='Read2 length'),
        ),
        migrations.AlterField(
            model_name='historicalpbalsequencing',
            name='read1_length',
            field=models.IntegerField(blank=True, default=150, null=True, verbose_name='Read1 length'),
        ),
        migrations.AlterField(
            model_name='historicalpbalsequencing',
            name='read2_length',
            field=models.IntegerField(blank=True, default=150, null=True, verbose_name='Read2 length'),
        ),
        migrations.AlterField(
            model_name='historicaltenxsequencing',
            name='read1_length',
            field=models.IntegerField(blank=True, default=150, null=True, verbose_name='Read1 length'),
        ),
        migrations.AlterField(
            model_name='historicaltenxsequencing',
            name='read2_length',
            field=models.IntegerField(blank=True, default=150, null=True, verbose_name='Read2 length'),
        ),
        migrations.AlterField(
            model_name='pbalsequencing',
            name='read1_length',
            field=models.IntegerField(blank=True, default=150, null=True, verbose_name='Read1 length'),
        ),
        migrations.AlterField(
            model_name='pbalsequencing',
            name='read2_length',
            field=models.IntegerField(blank=True, default=150, null=True, verbose_name='Read2 length'),
        ),
        migrations.AlterField(
            model_name='tenxsequencing',
            name='read1_length',
            field=models.IntegerField(blank=True, default=150, null=True, verbose_name='Read1 length'),
        ),
        migrations.AlterField(
            model_name='tenxsequencing',
            name='read2_length',
            field=models.IntegerField(blank=True, default=150, null=True, verbose_name='Read2 length'),
        ),
        migrations.AlterField(
            model_name='dlpsequencing',
            name='sequencing_instrument',
            field=models.CharField(blank=True, choices=[('HX', 'HiSeqX'), ('H2500', 'HiSeq2500'), ('N550', 'NextSeq550'), ('MI', 'MiSeq'), ('O', 'other')], default='HX', max_length=50, null=True, verbose_name='Sequencing instrument'),
        ),
        migrations.AlterField(
            model_name='historicaldlpsequencing',
            name='sequencing_instrument',
            field=models.CharField(blank=True, choices=[('HX', 'HiSeqX'), ('H2500', 'HiSeq2500'), ('N550', 'NextSeq550'), ('MI', 'MiSeq'), ('O', 'other')], default='HX', max_length=50, null=True, verbose_name='Sequencing instrument'),
        ),
        migrations.AlterField(
            model_name='historicalpbalsequencing',
            name='sequencing_instrument',
            field=models.CharField(blank=True, choices=[('HX', 'HiSeqX'), ('H2500', 'HiSeq2500'), ('N550', 'NextSeq550'), ('MI', 'MiSeq'), ('O', 'other')], default='HX', max_length=50, null=True, verbose_name='Sequencing instrument'),
        ),
        migrations.AlterField(
            model_name='historicaltenxsequencing',
            name='sequencing_instrument',
            field=models.CharField(blank=True, choices=[('HX', 'HiSeqX'), ('H2500', 'HiSeq2500'), ('N550', 'NextSeq550'), ('MI', 'MiSeq'), ('O', 'other')], default='HX', max_length=50, null=True, verbose_name='Sequencing instrument'),
        ),
        migrations.AlterField(
            model_name='pbalsequencing',
            name='sequencing_instrument',
            field=models.CharField(blank=True, choices=[('HX', 'HiSeqX'), ('H2500', 'HiSeq2500'), ('N550', 'NextSeq550'), ('MI', 'MiSeq'), ('O', 'other')], default='HX', max_length=50, null=True, verbose_name='Sequencing instrument'),
        ),
        migrations.AlterField(
            model_name='tenxsequencing',
            name='sequencing_instrument',
            field=models.CharField(blank=True, choices=[('HX', 'HiSeqX'), ('H2500', 'HiSeq2500'), ('N550', 'NextSeq550'), ('MI', 'MiSeq'), ('O', 'other')], default='HX', max_length=50, null=True, verbose_name='Sequencing instrument'),
        ),
        migrations.AddField(
            model_name='plate',
            name='plate_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Plate number'),
        ),
    ]
