# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-11-27 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20171121_1504'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='historicaldlpsequencing',
            table='dlp_history_sequencing',
        ),
        migrations.AlterModelTable(
            name='historicaldlplibrary',
            table='dlp_history_library',
        ),
        migrations.AlterField(
            model_name='dlplibrary',
            name='relates_to',
            field=models.ManyToManyField(blank=True, related_name='_dlplibrary_relates_to_+', to='core.DlpLibrary', verbose_name='Relates to'),
        ),
        migrations.AlterField(
            model_name='dlpsequencing',
            name='relates_to',
            field=models.ManyToManyField(blank=True, related_name='_dlpsequencing_relates_to_+', to='core.DlpSequencing', verbose_name='Relates to'),
        ),
        migrations.AlterField(
            model_name='pballibrary',
            name='relates_to',
            field=models.ManyToManyField(blank=True, to='core.DlpLibrary', verbose_name='Relates to'),
        ),
        migrations.AlterField(
            model_name='pbalsequencing',
            name='relates_to',
            field=models.ManyToManyField(blank=True, related_name='_pbalsequencing_relates_to_+', to='core.PbalSequencing', verbose_name='Relates to'),
        ),
        migrations.AlterField(
            model_name='tenxlibrary',
            name='relates_to',
            field=models.ManyToManyField(blank=True, to='core.DlpLibrary', verbose_name='Relates to'),
        ),
        migrations.AlterField(
            model_name='tenxsequencing',
            name='relates_to',
            field=models.ManyToManyField(blank=True, related_name='_tenxsequencing_relates_to_+', to='core.TenxSequencing', verbose_name='Relates to'),
        ),
    ]
