# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-01-17 22:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20171127_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dlpsequencing',
            name='submission_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Submission date'),
        ),
        migrations.AlterField(
            model_name='dlpsequencingdetail',
            name='sequencing_center',
            field=models.CharField(blank=True, choices=[('bccagsc', 'BCCAGSC'), ('ubcbrc', 'UBCBRC')], max_length=50, null=True, verbose_name='Sequencing center'),
        ),
        migrations.AlterField(
            model_name='historicaldlpsequencing',
            name='submission_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Submission date'),
        ),
        migrations.AlterField(
            model_name='historicalpbalsequencing',
            name='submission_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Submission date'),
        ),
        migrations.AlterField(
            model_name='historicaltenxsequencing',
            name='submission_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Submission date'),
        ),
        migrations.AlterField(
            model_name='pbalsequencing',
            name='submission_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Submission date'),
        ),
        migrations.AlterField(
            model_name='pbalsequencingdetail',
            name='sequencing_center',
            field=models.CharField(blank=True, choices=[('bccagsc', 'BCCAGSC'), ('ubcbrc', 'UBCBRC')], max_length=50, null=True, verbose_name='Sequencing center'),
        ),
        migrations.AlterField(
            model_name='tenxsequencing',
            name='submission_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Submission date'),
        ),
        migrations.AlterField(
            model_name='tenxsequencingdetail',
            name='sequencing_center',
            field=models.CharField(blank=True, choices=[('bccagsc', 'BCCAGSC'), ('ubcbrc', 'UBCBRC')], max_length=50, null=True, verbose_name='Sequencing center'),
        ),
    ]
