# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-01-17 22:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20180117_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dlpsequencing',
            name='pool_id',
        ),
        migrations.RemoveField(
            model_name='historicaldlpsequencing',
            name='pool_id',
        ),
    ]
