# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-03-02 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20180207_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalsampleinformation',
            name='pathology_disease_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Pathology/disease name (for diseased samples only)'),
        ),
        migrations.AlterField(
            model_name='dlplibraryconstructioninformation',
            name='spotting_location',
            field=models.CharField(blank=True, choices=[('AD', 'Aparicio Lab - Deckard'), ('AR', 'Aparicio Lab - Rachael'), ('H', 'Hansen Lab'), ('G', 'GSC')], max_length=50, null=True, verbose_name='Spotting location'),
        ),
        migrations.AlterField(
            model_name='dlplibrarysampledetail',
            name='spotting_location',
            field=models.CharField(blank=True, choices=[('AD', 'Aparicio Lab - Deckard'), ('AR', 'Aparicio Lab - Rachael'), ('H', 'Hansen Lab'), ('G', 'GSC')], max_length=50, null=True, verbose_name='Spotting location'),
        ),
        migrations.AlterField(
            model_name='pballibrarysampledetail',
            name='spotting_location',
            field=models.CharField(blank=True, choices=[('AD', 'Aparicio Lab - Deckard'), ('AR', 'Aparicio Lab - Rachael'), ('H', 'Hansen Lab'), ('G', 'GSC'), ('T', 'TFL flow facility')], max_length=50, null=True, verbose_name='Spotting location'),
        ),
    ]
