# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-03-29 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_dlpsequencingdetail_rev_comp_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsample',
            name='notes',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='sample',
            name='notes',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Notes'),
        ),
    ]
