# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-06-25 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20180329_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dlplane',
            name='path_to_archive',
            field=models.CharField(max_length=150, null=True, verbose_name='Path to archive'),
        ),
        migrations.AlterField(
            model_name='pballane',
            name='path_to_archive',
            field=models.CharField(max_length=150, null=True, verbose_name='Path to archive'),
        ),
        migrations.AlterField(
            model_name='tenxlane',
            name='path_to_archive',
            field=models.CharField(max_length=150, null=True, verbose_name='Path to archive'),
        ),
    ]
