# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-08-03 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20180803_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='dlplibrary',
            name='quality',
            field=models.DecimalField(decimal_places=2, default=0.75, max_digits=10, verbose_name='Quality'),
        ),
        migrations.AddField(
            model_name='dlplibrary',
            name='title',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='historicaldlplibrary',
            name='quality',
            field=models.DecimalField(decimal_places=2, default=0.75, max_digits=10, verbose_name='Quality'),
        ),
        migrations.AddField(
            model_name='historicaldlplibrary',
            name='title',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Title'),
        ),
    ]
