# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-05 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20180905_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenxlibraryconstructioninformation',
            name='concentration',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='DNA concentration (nM)'),
        ),
    ]
