# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-11 00:38
from __future__ import unicode_literals

import core.helpers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20180905_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenxCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_id', models.IntegerField(blank=True, null=True, verbose_name='Condition_ID')),
                ('experimental_condition', models.CharField(blank=True, max_length=50, null=True, verbose_name='Experimental_condition')),
                ('enzyme', models.CharField(blank=True, max_length=50, null=True, verbose_name='Enzyme')),
                ('digestion_temperature', models.CharField(blank=True, max_length=50, null=True, verbose_name='Digestion_Temperature')),
                ('live_dead', models.CharField(blank=True, max_length=50, null=True, verbose_name='Live/Dead')),
                ('cells_targeted', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cells_Targeted')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TenxLibrary', verbose_name='Library')),
                ('sample', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Sample', verbose_name='Sample')),
            ],
            options={
                'ordering': ['id'],
            },
            bases=(models.Model, core.helpers.FieldValue),
        ),
        migrations.RemoveField(
            model_name='tenxlibrarysampledetail',
            name='num_conditions',
        ),
    ]
