# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-04 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20180910_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dlplibrary',
            name='relates_to',
            field=models.ManyToManyField(blank=True, to='core.DlpLibrary', verbose_name='Relates to (DLP)'),
        ),
        migrations.RenameField(
            model_name='dlplibrary',
            old_name='relates_to',
            new_name='relates_to_dlp',
        ),
        migrations.AlterField(
            model_name='pballibrary',
            name='relates_to',
            field=models.ManyToManyField(blank=True, to='core.DlpLibrary', verbose_name='Relates to (DLP)'),
        ),
        migrations.RenameField(
            model_name='pballibrary',
            old_name='relates_to',
            new_name='relates_to_dlp',
        ),
        migrations.AlterField(
            model_name='tenxlibrary',
            name='relates_to',
            field=models.ManyToManyField(blank=True, to='core.DlpLibrary', verbose_name='Relates to (DLP)'),
        ),
        migrations.RenameField(
            model_name='tenxlibrary',
            old_name='relates_to',
            new_name='relates_to_dlp',
        ),
    ]
