# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-04 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_relates_to_field_change_20180904_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='dlplibrary',
            name='relates_to_tenx',
            field=models.ManyToManyField(blank=True, to='core.TenxLibrary', verbose_name='Relates to (Tenx)'),
        ),
        migrations.AddField(
            model_name='pballibrary',
            name='relates_to_tenx',
            field=models.ManyToManyField(blank=True, to='core.TenxLibrary', verbose_name='Relates to (Tenx)'),
        ),
        migrations.AddField(
            model_name='tenxlibrary',
            name='relates_to_tenx',
            field=models.ManyToManyField(blank=True, to='core.TenxLibrary', verbose_name='Relates to (Tenx)'),
        ),
    ]
