# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-18 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20180904_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dlplibrary',
            name='jira_ticket',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Jira ticket'),
        ),
        migrations.AlterField(
            model_name='historicaldlplibrary',
            name='jira_ticket',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Jira ticket'),
        ),
        migrations.AlterField(
            model_name='historicaltenxlibrary',
            name='jira_ticket',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Jira ticket'),
        ),
        migrations.AlterField(
            model_name='tenxlibrary',
            name='jira_ticket',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Jira ticket'),
        ),
    ]
