# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-18 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20180918_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='dlplibrary',
            name='failed',
            field=models.BooleanField(default=False, verbose_name='Failed'),
        ),
        migrations.AddField(
            model_name='historicaldlplibrary',
            name='failed',
            field=models.BooleanField(default=False, verbose_name='Failed'),
        ),
        migrations.AddField(
            model_name='historicalpballibrary',
            name='failed',
            field=models.BooleanField(default=False, verbose_name='Failed'),
        ),
        migrations.AddField(
            model_name='historicaltenxlibrary',
            name='failed',
            field=models.BooleanField(default=False, verbose_name='Failed'),
        ),
        migrations.AddField(
            model_name='pballibrary',
            name='failed',
            field=models.BooleanField(default=False, verbose_name='Failed'),
        ),
        migrations.AddField(
            model_name='tenxlibrary',
            name='failed',
            field=models.BooleanField(default=False, verbose_name='Failed'),
        ),
    ]
