# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-28 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20180918_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsample',
            name='xenograft_treatment_status',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Xenograft treatment status'),
        ),
        migrations.AddField(
            model_name='sample',
            name='xenograft_treatment_status',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Xenograft treatment status'),
        ),
    ]
