# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-09 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20181128_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dlpsequencingdetail',
            name='lanes_received',
        ),
        migrations.RemoveField(
            model_name='dlpsequencingdetail',
            name='lanes_requested',
        ),
        migrations.RemoveField(
            model_name='pbalsequencingdetail',
            name='lanes_received',
        ),
        migrations.RemoveField(
            model_name='pbalsequencingdetail',
            name='lanes_requested',
        ),
        migrations.RemoveField(
            model_name='tenxsequencingdetail',
            name='lanes_received',
        ),
        migrations.RemoveField(
            model_name='tenxsequencingdetail',
            name='lanes_requested',
        ),
        migrations.AddField(
            model_name='dlpsequencingdetail',
            name='number_of_lanes_requested',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pbalsequencingdetail',
            name='number_of_lanes_requested',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tenxsequencingdetail',
            name='number_of_lanes_requested',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
