# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-12 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_auto_20190108_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='dlplane',
            name='sequencing_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='pballane',
            name='sequencing_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tenxlane',
            name='sequencing_date',
            field=models.DateTimeField(null=True),
        ),
    ]
