# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-08 22:43
from __future__ import unicode_literals

from django.db import migrations


def update_number_of_lanes_requested(apps, schema_editor):
    Sequences = apps.get_model('core','DlpSequencing')
    for sequence in Sequences.objects.all():
        if hasattr(sequence, 'dlpsequencingdetail'):
            sequence.dlpsequencingdetail.number_of_lanes_requested = sequence.dlplane_set.all().count()
            sequence.dlpsequencingdetail.save()
        else:
            pass

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_auto_20190107_1738'),
    ]

    operations = [
        migrations.RunPython(update_number_of_lanes_requested)
    ]



