# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-25 23:53
from __future__ import unicode_literals

from django.db import migrations, models

def migrate_sequencing_details(apps, schema_editor):

    DlpSequencing = apps.get_model('core', 'DlpSequencing')

    for sequencing in DlpSequencing.objects.all():
        if(sequencing.dlpsequencingdetail is None):
            continue
        sequencing.number_of_lanes_requested = sequencing.dlpsequencingdetail.number_of_lanes_requested
        sequencing.gsc_library_id = sequencing.dlpsequencingdetail.gsc_library_id
        sequencing.sequencer_id = sequencing.dlpsequencingdetail.sequencer_id
        sequencing.sequencing_center = sequencing.dlpsequencingdetail.sequencing_center
        sequencing.sequencer_notes = sequencing.dlpsequencingdetail.sequencer_notes
        sequencing.rev_comp_override = sequencing.dlpsequencingdetail.rev_comp_override
        sequencing.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_auto_20190111_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='dlpsequencing',
            name='gsc_library_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='GSC library ID'),
        ),
        migrations.AddField(
            model_name='dlpsequencing',
            name='number_of_lanes_requested',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dlpsequencing',
            name='rev_comp_override',
            field=models.CharField(blank=True, choices=[('i7,i5', 'No Reverse Complement'), ('i7,rev(i5)', 'Reverse Complement i5'), ('rev(i7),i5', 'Reverse Complement i7'), ('rev(i7),rev(i5)', 'Reverse Complement i7 and i5')], default=None, max_length=50, null=True, verbose_name='Reverse Complement Override'),
        ),
        migrations.AddField(
            model_name='dlpsequencing',
            name='sequencer_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sequencer ID'),
        ),
        migrations.AddField(
            model_name='dlpsequencing',
            name='sequencer_notes',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Sequencing notes'),
        ),
        migrations.AddField(
            model_name='dlpsequencing',
            name='sequencing_center',
            field=models.CharField(choices=[('BCCAGSC', 'BCCAGSC'), ('UBCBRC', 'UBCBRC')], default='BCCAGSC', max_length=50, null=True, verbose_name='Sequencing center'),
        ),
        migrations.AddField(
            model_name='historicaldlpsequencing',
            name='gsc_library_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='GSC library ID'),
        ),
        migrations.AddField(
            model_name='historicaldlpsequencing',
            name='number_of_lanes_requested',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicaldlpsequencing',
            name='rev_comp_override',
            field=models.CharField(blank=True, choices=[('i7,i5', 'No Reverse Complement'), ('i7,rev(i5)', 'Reverse Complement i5'), ('rev(i7),i5', 'Reverse Complement i7'), ('rev(i7),rev(i5)', 'Reverse Complement i7 and i5')], default=None, max_length=50, null=True, verbose_name='Reverse Complement Override'),
        ),
        migrations.AddField(
            model_name='historicaldlpsequencing',
            name='sequencer_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sequencer ID'),
        ),
        migrations.AddField(
            model_name='historicaldlpsequencing',
            name='sequencer_notes',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Sequencing notes'),
        ),
        migrations.AddField(
            model_name='historicaldlpsequencing',
            name='sequencing_center',
            field=models.CharField(choices=[('BCCAGSC', 'BCCAGSC'), ('UBCBRC', 'UBCBRC')], default='BCCAGSC', max_length=50, null=True, verbose_name='Sequencing center'),
        ),
        migrations.AddField(
            model_name='historicalpbalsequencing',
            name='gsc_library_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='GSC library ID'),
        ),
        migrations.AddField(
            model_name='historicalpbalsequencing',
            name='number_of_lanes_requested',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalpbalsequencing',
            name='sequencer_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sequencer ID'),
        ),
        migrations.AddField(
            model_name='historicalpbalsequencing',
            name='sequencer_notes',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Sequencing notes'),
        ),
        migrations.AddField(
            model_name='historicalpbalsequencing',
            name='sequencing_center',
            field=models.CharField(choices=[('BCCAGSC', 'BCCAGSC'), ('UBCBRC', 'UBCBRC')], default='BCCAGSC', max_length=50, null=True, verbose_name='Sequencing center'),
        ),
        migrations.AddField(
            model_name='historicaltenxsequencing',
            name='gsc_library_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='GSC library ID'),
        ),
        migrations.AddField(
            model_name='historicaltenxsequencing',
            name='number_of_lanes_requested',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicaltenxsequencing',
            name='sequencer_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sequencer ID'),
        ),
        migrations.AddField(
            model_name='historicaltenxsequencing',
            name='sequencer_notes',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Sequencing notes'),
        ),
        migrations.AddField(
            model_name='historicaltenxsequencing',
            name='sequencing_center',
            field=models.CharField(choices=[('BCCAGSC', 'BCCAGSC'), ('UBCBRC', 'UBCBRC')], default='BCCAGSC', max_length=50, null=True, verbose_name='Sequencing center'),
        ),
        migrations.AddField(
            model_name='pbalsequencing',
            name='gsc_library_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='GSC library ID'),
        ),
        migrations.AddField(
            model_name='pbalsequencing',
            name='number_of_lanes_requested',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pbalsequencing',
            name='sequencer_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sequencer ID'),
        ),
        migrations.AddField(
            model_name='pbalsequencing',
            name='sequencer_notes',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Sequencing notes'),
        ),
        migrations.AddField(
            model_name='pbalsequencing',
            name='sequencing_center',
            field=models.CharField(choices=[('BCCAGSC', 'BCCAGSC'), ('UBCBRC', 'UBCBRC')], default='BCCAGSC', max_length=50, null=True, verbose_name='Sequencing center'),
        ),
        migrations.AddField(
            model_name='tenxsequencing',
            name='gsc_library_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='GSC library ID'),
        ),
        migrations.AddField(
            model_name='tenxsequencing',
            name='number_of_lanes_requested',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tenxsequencing',
            name='sequencer_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sequencer ID'),
        ),
        migrations.AddField(
            model_name='tenxsequencing',
            name='sequencer_notes',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Sequencing notes'),
        ),
        migrations.AddField(
            model_name='tenxsequencing',
            name='sequencing_center',
            field=models.CharField(choices=[('BCCAGSC', 'BCCAGSC'), ('UBCBRC', 'UBCBRC')], default='BCCAGSC', max_length=50, null=True, verbose_name='Sequencing center'),
        ),
        migrations.RunPython(migrate_sequencing_details),
    ]
