# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-26 00:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_auto_20190125_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dlpsequencingdetail',
            name='sequencing',
        ),
        migrations.RemoveField(
            model_name='pbalsequencingdetail',
            name='sequencing',
        ),
        migrations.RemoveField(
            model_name='tenxsequencingdetail',
            name='sequencing',
        ),
        migrations.DeleteModel(
            name='DlpSequencingDetail',
        ),
        migrations.DeleteModel(
            name='PbalSequencingDetail',
        ),
        migrations.DeleteModel(
            name='TenxSequencingDetail',
        ),
    ]
