# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-01 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

def combine_sequencings(apps, schema_editor):
    DlpLibrary= apps.get_model('core', 'DlpLibrary')
    DlpSequencing = apps.get_model('core', 'DlpSequencing')

    for library in DlpLibrary.objects.all():
        if(library.dlpsequencing_set.filter(sequencing_center='BCCAGSC').count() >= 2):
            base_sequencing = library.dlpsequencing_set.filter(sequencing_center='BCCAGSC').first()

            for sequence in library.dlpsequencing_set.filter(sequencing_center='BCCAGSC')[1:]:
                for lane in sequence.dlplane_set.all():
                    if(lane not in base_sequencing.dlplane_set.all()):
                        base_sequencing.dlplane_set.add(lane)
                sequence.delete()

        if(library.dlpsequencing_set.filter(sequencing_center='UBCBRC').count() >= 2):
            base_sequencing = library.dlpsequencing_set.filter(sequencing_center='UBCBRC').first()

            for sequence in library.dlpsequencing_set.filter(sequencing_center='UBCBRC')[1:]:
                for lane in sequence.dlplane_set.all():
                    if(lane not in base_sequencing.dlplane_set.all()):
                        base_sequencing.dlplane_set.add(lane)
                sequence.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_auto_20190125_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dlplane',
            name='sequencing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.DlpSequencing', verbose_name='Sequencing'),
        ),
        migrations.RunPython(combine_sequencings),
    ]
