# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-01 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_auto_20190201_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dlplane',
            name='sequencing',
            field=models.ForeignKey(default=112358, on_delete=django.db.models.deletion.CASCADE, to='core.DlpSequencing', verbose_name='Sequencing'),
            preserve_default=False,
        ),
    ]
