# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-02 01:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_auto_20190201_1242'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dlpsequencing',
            unique_together=set([('library', 'sequencing_center')]),
        ),
        migrations.AlterUniqueTogether(
            name='pbalsequencing',
            unique_together=set([('library', 'sequencing_center')]),
        ),
        migrations.AlterUniqueTogether(
            name='tenxsequencing',
            unique_together=set([('library', 'sequencing_center')]),
        ),
    ]
