# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-01 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_auto_20190201_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dlplane',
            name='path_to_archive',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Path to archive'),
        ),
        migrations.AlterUniqueTogether(
            name='dlpsequencing',
            unique_together=set([('library', 'sequencing_center')]),
        ),
        migrations.AlterUniqueTogether(
            name='pbalsequencing',
            unique_together=set([('library', 'sequencing_center')]),
        ),
        migrations.AlterUniqueTogether(
            name='tenxsequencing',
            unique_together=set([('library', 'sequencing_center')]),
        ),
    ]
