# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-02-06 19:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    def sequencing_delete_clear(apps, schema_editor):
        sequencings = apps.get_model('core', 'DlpSequencing')

        for sequencing in sequencings.objects.all():
            if sequencing.sequencing_goal:
                sequencing.number_of_lanes_requested = max(
                    (sequencing.number_of_lanes_requested, sequencing.sequencing_goal), key=int)
                sequencing.save()

    dependencies = [
        ('core', '0052_auto_20190201_1712'),
    ]

    operations = [
        migrations.RunPython(sequencing_delete_clear),
    ]
