# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-02-06 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_auto_20190206_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dlpsequencing',
            name='sequencing_goal',
        ),
        migrations.RemoveField(
            model_name='historicaldlpsequencing',
            name='sequencing_goal',
        ),
        migrations.RemoveField(
            model_name='historicalpbalsequencing',
            name='sequencing_goal',
        ),
        migrations.RemoveField(
            model_name='historicaltenxsequencing',
            name='sequencing_goal',
        ),
        migrations.RemoveField(
            model_name='pbalsequencing',
            name='sequencing_goal',
        ),
        migrations.RemoveField(
            model_name='tenxsequencing',
            name='sequencing_goal',
        ),
        migrations.AlterField(
            model_name='dlpsequencing',
            name='number_of_lanes_requested',
            field=models.PositiveIntegerField(default=0, verbose_name='Sequencing Goal'),
        ),
        migrations.AlterField(
            model_name='historicaldlpsequencing',
            name='number_of_lanes_requested',
            field=models.PositiveIntegerField(default=0, verbose_name='Sequencing Goal'),
        ),
        migrations.AlterField(
            model_name='historicalpbalsequencing',
            name='number_of_lanes_requested',
            field=models.PositiveIntegerField(default=0, verbose_name='Sequencing Goal'),
        ),
        migrations.AlterField(
            model_name='historicaltenxsequencing',
            name='number_of_lanes_requested',
            field=models.PositiveIntegerField(default=0, verbose_name='Sequencing Goal'),
        ),
        migrations.AlterField(
            model_name='pbalsequencing',
            name='number_of_lanes_requested',
            field=models.PositiveIntegerField(default=0, verbose_name='Sequencing Goal'),
        ),
        migrations.AlterField(
            model_name='tenxsequencing',
            name='number_of_lanes_requested',
            field=models.PositiveIntegerField(default=0, verbose_name='Sequencing Goal'),
        ),
    ]
