# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-02-06 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_auto_20190206_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenxlibraryconstructioninformation',
            name='chemistry_version',
            field=models.CharField(choices=[(b'VERSION_2', b'v2'), (b'VERSION_3', b'v3')], default='VERSION_2', max_length=150, null=True, verbose_name='Chemistry Version'),
        ),
    ]
