# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-11 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_tenxlibraryconstructioninformation_chemistry_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='dlpsequencing',
            name='lane_requested_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='historicaldlpsequencing',
            name='lane_requested_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='historicalpbalsequencing',
            name='lane_requested_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='historicaltenxsequencing',
            name='lane_requested_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='pbalsequencing',
            name='lane_requested_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='tenxsequencing',
            name='lane_requested_date',
            field=models.DateField(null=True),
        ),
    ]
