# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-15 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_auto_20190211_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='JiraUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('associated_with_dlp', models.BooleanField(default=True)),
                ('associated_with_tenx', models.BooleanField(default=True)),
            ],
        ),
    ]
