# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-02-26 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='dlplibrary',
            name='exclude_from_analysis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaldlplibrary',
            name='exclude_from_analysis',
            field=models.BooleanField(default=False),
        ),
    ]
