# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-03-08 17:43
from __future__ import unicode_literals

import core.helpers
from django.db import migrations, models
import django.db.models.deletion

def create_chip(apps, schema_editor):
    Chips = apps.get_model('core', 'TenxChip')
    TenxLibrary = apps.get_model('core', 'TenxLibrary')
    db_alias = schema_editor.connection.alias
    for i in range(1,77):
        chip = Chips.objects.using(db_alias).create()
        library = TenxLibrary.objects.filter(id=i)
        if library:
            library[0].chips = chip
            library[0].save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_auto_20190306_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenxChip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(blank=True, choices=[('SA', 'Sam Aparicio'), ('DH', 'David Huntsman')], default='SA', max_length=50, null=True, verbose_name='Lab Name')),
            ],
            bases=(models.Model, core.helpers.FieldValue),
        ),
        migrations.AddField(
            model_name='historicaltenxlibrary',
            name='chip_well',
            field=models.IntegerField(choices=[(0, 'NOT SET'), (1, 'WELL_1'), (2, 'WELL_2'), (3, 'WELL_3'), (4, 'WELL_4'), (5, 'WELL_5'), (6, 'WELL_6'), (7, 'WELL_7'), (8, 'WELL_8')], default=0),
        ),
        migrations.AddField(
            model_name='historicaltenxlibrary',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Library Name'),
        ),
        migrations.AddField(
            model_name='tenxlibrary',
            name='chip_well',
            field=models.IntegerField(choices=[(0, 'NOT SET'), (1, 'WELL_1'), (2, 'WELL_2'), (3, 'WELL_3'), (4, 'WELL_4'), (5, 'WELL_5'), (6, 'WELL_6'), (7, 'WELL_7'), (8, 'WELL_8')], default=0),
        ),
        migrations.AddField(
            model_name='tenxlibrary',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Library Name'),
        ),
        migrations.AddField(
            model_name='historicaltenxlibrary',
            name='chips',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.TenxChip'),
        ),
        migrations.AddField(
            model_name='tenxlibrary',
            name='chips',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.TenxChip', verbose_name='Chip'),
        ),
        migrations.RunPython(create_chip),
    ]

