# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-08 18:49
from __future__ import unicode_literals

from django.db import migrations


def create_chip(apps, schema_editor):
    Chips = apps.get_model('core', 'TenxChip')
    TenxLibrary = apps.get_model('core', 'TenxLibrary')
    db_alias = schema_editor.connection.alias
    for i in range(1,77):
        chip = Chips.objects.create()
        library = TenxLibrary.objects.filter(id=i)
        if library:
            library[0].name = "TENX" + str(chip.id).zfill(3)
            library[0].chips = chip
            library[0].save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_auto_20190308_1013'),
    ]

    operations = [
        migrations.RunPython(create_chip),
    ]
