# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-08 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_auto_20190308_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalsampleinformation',
            name='cancer_subtype',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cancer Subtype'),
        ),
        migrations.AddField(
            model_name='additionalsampleinformation',
            name='cancer_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cancer Type'),
        ),
        migrations.AddField(
            model_name='additionalsampleinformation',
            name='tissue_state',
            field=models.CharField(blank=True, choices=[('NONE', 'None'), ('FROZ', 'Frozen'), ('FRES', 'Fresh'),
                                                        ('DIG-FRES', 'Digested-Fresh')], default='NONE', max_length=50,
                                   null=True, verbose_name='Tissue State'),
        ),
        migrations.AddField(
            model_name='historicaltenxlibrary',
            name='condition',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Condition'),
        ),
        migrations.AddField(
            model_name='tenxlibrary',
            name='condition',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Condition'),
        ),
    ]
