# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-08 18:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_auto_20190308_1049'),
    ]

    operations = [
    ]
