# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-03-11 21:35
from __future__ import unicode_literals

from django.db import migrations

def create_chip(apps, schema_editor):
    TenxLibrary = apps.get_model('core', 'TenxLibrary')
    for i in range(1,77):
        library = TenxLibrary.objects.filter(id=i)
        if library:
            library[0].name = "TENX" + str(i).zfill(3)
            library[0].save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_auto_20190311_1427'),
    ]

    operations = [
        migrations.RunPython(create_chip)
    ]
