# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-03-14 19:24
from __future__ import unicode_literals

from django.db import migrations

CHANGED_SAMPLE_INFO = {'25': {'anatomic_site': 'Breast', 'tissue_state': 'NONE', 'cancer_type': 'None', 'tissue_type': 'M', 'cancer_subtype': 'None'},
                       '86': {'anatomic_site': 'Breast', 'tissue_state': 'NONE', 'cancer_type': 'None', 'tissue_type': 'M', 'cancer_subtype': 'None'},
                       '38': {'anatomic_site': 'Breast', 'tissue_state': 'NONE', 'cancer_type': 'None', 'tissue_type': 'M', 'cancer_subtype': 'None'},
                       '173': {'anatomic_site': 'Ovary', 'tissue_state': 'NONE', 'cancer_type': 'None', 'tissue_type': 'M', 'cancer_subtype': 'None'},
                       '49': {'anatomic_site': 'Breast', 'tissue_state': 'NONE', 'cancer_type': 'None', 'tissue_type': 'M', 'cancer_subtype': 'None'},
                       '33': {'anatomic_site': 'Breast', 'tissue_state': 'NONE', 'cancer_type': 'None', 'tissue_type': 'M', 'cancer_subtype': 'None'},
                       '158': {'anatomic_site': 'Breast', 'tissue_state': 'NONE', 'cancer_type': 'None', 'tissue_type': 'M', 'cancer_subtype': 'None'},
                       '30': {'anatomic_site': 'Breast', 'tissue_state': 'NONE', 'cancer_type': 'None', 'tissue_type': 'M', 'cancer_subtype': 'None'},
                       '172': {'anatomic_site': 'Ovary', 'tissue_state': 'NONE', 'cancer_type': 'None', 'tissue_type': 'M', 'cancer_subtype': 'None'},
                       '60': {'anatomic_site': 'Breast', 'tissue_state': 'NONE', 'cancer_type': 'None', 'tissue_type': 'M', 'cancer_subtype': 'None'},
                       '141': {'anatomic_site': 'Ovary', 'tissue_state': 'NONE', 'cancer_type': 'None', 'tissue_type': 'M', 'cancer_subtype': 'None'},
                       '3': {'anatomic_site': 'Blood', 'tissue_state': 'NONE', 'cancer_type': 'None', 'tissue_type': 'N', 'cancer_subtype': 'None'},
                       '116': {'anatomic_site': 'Breast', 'tissue_state': 'NONE', 'cancer_type': 'None', 'tissue_type': 'M', 'cancer_subtype': 'None'},
                       '196': {'anatomic_site': 'Ovary', 'tissue_state': 'NONE', 'cancer_type': 'None', 'tissue_type': 'M', 'cancer_subtype': 'None'},
                       '110': {'anatomic_site': 'Pleural Effusion', 'tissue_state': 'NONE', 'cancer_type': 'None', 'tissue_type': 'M', 'cancer_subtype': 'None'},
                       '109': {'anatomic_site': 'Breast', 'tissue_state': 'NONE', 'cancer_type': 'None', 'tissue_type': 'M', 'cancer_subtype': 'None'},
                       '177': {'anatomic_site': 'Breast', 'tissue_state': 'NONE', 'cancer_type': 'None', 'tissue_type': 'M', 'cancer_subtype': 'None'},
                       '100': {'anatomic_site': 'Ovarian', 'tissue_state': 'NONE', 'cancer_type': 'None', 'tissue_type': 'M', 'cancer_subtype': 'None'},
                       '160': {'anatomic_site': 'Breast', 'tissue_state': 'NONE', 'cancer_type': 'None', 'tissue_type': 'M', 'cancer_subtype': 'None'},
                       '118': {'anatomic_site': 'Breast', 'tissue_state': 'NONE', 'cancer_type': 'None', 'tissue_type': 'M', 'cancer_subtype': 'None'},
                       '125': {'anatomic_site': 'Ovary', 'tissue_state': 'NONE', 'cancer_type': 'None', 'tissue_type': 'M', 'cancer_subtype': 'None'}}


CHANGED_SAMPLE = {'150': {'anonymous_patient_id': 'None', 'sample_type': 'None', 'sample_id': 'VOA11267S'},
                  '39': {'anonymous_patient_id': 'CBX028', 'sample_type': 'X', 'sample_id': 'SA609X6XB01899'},
                  '205': {'anonymous_patient_id': 'None', 'sample_type': 'None', 'sample_id': 'VOA12024'},
                  '58': {'anonymous_patient_id': 'None', 'sample_type': 'X', 'sample_id': 'SA604X6XB01979'},
                  '109': {'anonymous_patient_id': 'VOA11019SA', 'sample_type': 'None', 'sample_id': 'VOA11019SA'},
                  '134': {'anonymous_patient_id': 'None', 'sample_type': 'P', 'sample_id': 'VOA11083SD'},
                  '47': {'anonymous_patient_id': 'VBA0662', 'sample_type': 'X', 'sample_id': 'SA501X2XB00096'},
                  '127': {'anonymous_patient_id': '', 'sample_type': 'None', 'sample_id': 'SA604X9XB02417'},
                  '42': {'anonymous_patient_id': 'CBX028', 'sample_type': 'X', 'sample_id': 'SA609X4XB01734'},
                  '34': {'anonymous_patient_id': 'CBX028', 'sample_type': 'X', 'sample_id': 'SA609X6XB01898'},
                  '182': {'anonymous_patient_id': 'VOA11924F', 'sample_type': 'None', 'sample_id': 'VOA11924F'},
                  '181': {'anonymous_patient_id': 'VOA11924A', 'sample_type': 'P', 'sample_id': 'VOA11924A'},
                  '186': {'anonymous_patient_id': 'None', 'sample_type': 'X', 'sample_id': 'SA535X5XB02887'},
                  '125': {'anonymous_patient_id': '', 'sample_type': 'X', 'sample_id': 'SA604X9XB02413'},
                  '69': {'anonymous_patient_id': '', 'sample_type': 'X', 'sample_id': 'SA605X3XB01966'},
                  '95': {'anonymous_patient_id': 'None', 'sample_type': 'X', 'sample_id': 'SA604X7XB02089'},
                  '8': {'anonymous_patient_id': 'None', 'sample_type': 'C', 'sample_id': 'SA928'},
                  '167': {'anonymous_patient_id': 'PBC0006433', 'sample_type': 'P', 'sample_id': 'PBC0006433'},
                  '119': {'anonymous_patient_id': 'None', 'sample_type': 'C', 'sample_id': 'SA854'},
                  '118': {'anonymous_patient_id': 'CBX038', 'sample_type': 'X', 'sample_id': 'SA604X8XB02164'},
                  '169': {'anonymous_patient_id': 'PBC0004573', 'sample_type': 'P', 'sample_id': 'PBC0004573'}}

def fix_sample_and_sample_info(apps, schema_editor):

    Sample = apps.get_model('core', 'Sample')
    SampleInfo = apps.get_model('core', 'AdditionalSampleInformation')

    for key in CHANGED_SAMPLE:
        sample = Sample.objects.filter(id=int(key))[0]
        sample.sample_id = CHANGED_SAMPLE[key]["sample_id"]
        sample.sample_type = CHANGED_SAMPLE[key]["sample_type"]
        sample.anonymous_patient_id = CHANGED_SAMPLE[key]["anonymous_patient_id"]
        sample.save()

    for key in CHANGED_SAMPLE_INFO:
        sample_info  = SampleInfo.objects.filter(id=int(key))[0]
        sample_info.anatomic_site = CHANGED_SAMPLE_INFO[key]["anatomic_site"]
        sample_info.tissue_state = CHANGED_SAMPLE_INFO[key]["tissue_state"]
        sample_info.cancer_type = CHANGED_SAMPLE_INFO[key]["cancer_type"]
        sample_info.tissue_type = CHANGED_SAMPLE_INFO[key]["tissue_type"]
        sample_info.cancer_subtype = CHANGED_SAMPLE_INFO[key]["cancer_subtype"]
        sample_info.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_auto_20190311_1435'),
    ]

    operations = [
        migrations.RunPython(fix_sample_and_sample_info)
    ]
