# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-03-15 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_historicaladditionalsampleinformation_historicalchipregion_historicalchipregionmetadata_historicaldl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dlpsequencing',
            name='sequencing_instrument',
            field=models.CharField(blank=True, choices=[('HX', 'HiSeqX'), ('H2500', 'HiSeq2500'), ('N500', 'NextSeq500'), ('N550', 'NextSeq550'), ('MI', 'MiSeq'), ('O', 'other')], default='HX', max_length=50, null=True, verbose_name='Sequencing instrument'),
        ),
        migrations.AlterField(
            model_name='historicaldlpsequencing',
            name='sequencing_instrument',
            field=models.CharField(blank=True, choices=[('HX', 'HiSeqX'), ('H2500', 'HiSeq2500'), ('N500', 'NextSeq500'), ('N550', 'NextSeq550'), ('MI', 'MiSeq'), ('O', 'other')], default='HX', max_length=50, null=True, verbose_name='Sequencing instrument'),
        ),
        migrations.AlterField(
            model_name='historicalpbalsequencing',
            name='sequencing_instrument',
            field=models.CharField(blank=True, choices=[('HX', 'HiSeqX'), ('H2500', 'HiSeq2500'), ('N500', 'NextSeq500'), ('N550', 'NextSeq550'), ('MI', 'MiSeq'), ('O', 'other')], default='HX', max_length=50, null=True, verbose_name='Sequencing instrument'),
        ),
        migrations.AlterField(
            model_name='historicaltenxsequencing',
            name='sequencing_instrument',
            field=models.CharField(blank=True, choices=[('HX', 'HiSeqX'), ('H2500', 'HiSeq2500'), ('N500', 'NextSeq500'), ('N550', 'NextSeq550'), ('MI', 'MiSeq'), ('O', 'other')], default='HX', max_length=50, null=True, verbose_name='Sequencing instrument'),
        ),
        migrations.AlterField(
            model_name='pbalsequencing',
            name='sequencing_instrument',
            field=models.CharField(blank=True, choices=[('HX', 'HiSeqX'), ('H2500', 'HiSeq2500'), ('N500', 'NextSeq500'), ('N550', 'NextSeq550'), ('MI', 'MiSeq'), ('O', 'other')], default='HX', max_length=50, null=True, verbose_name='Sequencing instrument'),
        ),
        migrations.AlterField(
            model_name='tenxsequencing',
            name='sequencing_instrument',
            field=models.CharField(blank=True, choices=[('HX', 'HiSeqX'), ('H2500', 'HiSeq2500'), ('N500', 'NextSeq500'), ('N550', 'NextSeq550'), ('MI', 'MiSeq'), ('O', 'other')], default='HX', max_length=50, null=True, verbose_name='Sequencing instrument'),
        ),
    ]
