# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-03-15 23:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_auto_20190315_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dlplibrary',
            old_name='projects',
            new_name='tag_projects',
        ),
        migrations.RenameField(
            model_name='pballibrary',
            old_name='projects',
            new_name='tag_projects',
        ),
        migrations.RenameField(
            model_name='tenxlibrary',
            old_name='projects',
            new_name='tag_projects',
        ),
    ]
