# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-03-18 22:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_auto_20190318_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dlplibrary',
            name='tag_projects',
        ),
        migrations.RemoveField(
            model_name='pballibrary',
            name='tag_projects',
        ),
        migrations.RemoveField(
            model_name='tenxlibrary',
            name='tag_projects',
        ),
    ]
