# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-12 18:42
from __future__ import unicode_literals

from django.db import migrations

data=[{
            "id": 1,
            "version": "v1.0.0",
            "jira_ticket": "SC-2122",
            "run_status": "complete",
            "last_updated_date": "2019-07-11T16:48:54.232817-07:00",
            "submission_date": "2019-04-25",
            "description": "2019-04-25",
            "tenx_library": 83,
            "tenxsequencing_set": []
        },
        {
            "id": 2,
            "version": "v1.0.0",
            "jira_ticket": "SC-2177",
            "run_status": "complete",
            "last_updated_date": "2019-07-11T16:48:54.237279-07:00",
            "submission_date": "2019-05-12",
            "description": "2019-05-12",
            "tenx_library": 141,
            "tenxsequencing_set": []
        },
        {
            "id": 3,
            "version": "v1.0.0",
            "jira_ticket": "SC-2178",
            "run_status": "idle",
            "last_updated_date": "2019-07-11T16:48:54.241886-07:00",
            "submission_date": "2019-05-14",
            "description": "2019-05-14",
            "tenx_library": 142,
            "tenxsequencing_set": []
        },
        {
            "id": 4,
            "version": "v1.0.0",
            "jira_ticket": "SC-2242",
            "run_status": "idle",
            "last_updated_date": "2019-07-11T16:48:54.246399-07:00",
            "submission_date": "2019-06-04",
            "description": "2019-06-04",
            "tenx_library": 143,
            "tenxsequencing_set": []
        },
        {
            "id": 5,
            "version": "v1.0.0",
            "jira_ticket": "SC-2246",
            "run_status": "idle",
            "last_updated_date": "2019-07-11T16:48:54.250849-07:00",
            "submission_date": "2019-06-05",
            "description": "2019-06-05",
            "tenx_library": 133,
            "tenxsequencing_set": []
        },
        {
            "id": 6,
            "version": "v1.0.0",
            "jira_ticket": "SC-2279",
            "run_status": "idle",
            "last_updated_date": "2019-07-11T16:48:54.255645-07:00",
            "submission_date": "2019-06-10",
            "description": "2019-06-10",
            "tenx_library": 131,
            "tenxsequencing_set": []
        },
        {
            "id": 7,
            "version": "v1.0.0",
            "jira_ticket": "SC-2280",
            "run_status": "complete",
            "last_updated_date": "2019-07-11T16:48:54.261319-07:00",
            "submission_date": "2019-06-10",
            "description": "2019-06-10",
            "tenx_library": 132,
            "tenxsequencing_set": []
        },
        {
            "id": 8,
            "version": "v1.0.0",
            "jira_ticket": "SC-2285",
            "run_status": "complete",
            "last_updated_date": "2019-07-11T16:48:54.265787-07:00",
            "submission_date": "2019-06-11",
            "description": "2019-06-11",
            "tenx_library": 134,
            "tenxsequencing_set": []
        },
        {
            "id": 9,
            "version": "v1.0.0",
            "jira_ticket": "SC-2286",
            "run_status": "complete",
            "last_updated_date": "2019-07-11T16:48:54.270292-07:00",
            "submission_date": "2019-06-13",
            "description": "2019-06-13",
            "tenx_library": 137,
            "tenxsequencing_set": []
        },
        {
            "id": 10,
            "version": "v1.0.0",
            "jira_ticket": "SC-2287",
            "run_status": "complete",
            "last_updated_date": "2019-07-11T16:48:54.274914-07:00",
            "submission_date": "2019-06-13",
            "description": "2019-06-13",
            "tenx_library": 138,
            "tenxsequencing_set": []
        },
        {
            "id": 11,
            "version": "v1.0.0",
            "jira_ticket": "SC-2288",
            "run_status": "complete",
            "last_updated_date": "2019-07-11T16:48:54.279448-07:00",
            "submission_date": "2019-06-13",
            "description": "2019-06-13",
            "tenx_library": 140,
            "tenxsequencing_set": []
        },
        {
            "id": 12,
            "version": "v1.0.0",
            "jira_ticket": "SC-2289",
            "run_status": "complete",
            "last_updated_date": "2019-07-11T16:48:54.284045-07:00",
            "submission_date": "2019-06-13",
            "description": "2019-06-13",
            "tenx_library": 71,
            "tenxsequencing_set": []
        },
        {
            "id": 13,
            "version": "v1.0.0",
            "jira_ticket": "SC-2290",
            "run_status": "complete",
            "last_updated_date": "2019-07-11T16:48:54.288630-07:00",
            "submission_date": "2019-06-13",
            "description": "2019-06-13",
            "tenx_library": 76,
            "tenxsequencing_set": []
        },
        {
            "id": 14,
            "version": "v1.0.0",
            "jira_ticket": "SC-2291",
            "run_status": "complete",
            "last_updated_date": "2019-07-11T16:48:54.293059-07:00",
            "submission_date": "2019-06-13",
            "description": "2019-06-13",
            "tenx_library": 139,
            "tenxsequencing_set": []
        },
        {
            "id": 15,
            "version": "v1.0.0",
            "jira_ticket": "SC-2295",
            "run_status": "complete",
            "last_updated_date": "2019-07-11T16:48:54.297961-07:00",
            "submission_date": "2019-06-13",
            "description": "2019-06-13",
            "tenx_library": 62,
            "tenxsequencing_set": []
        },
        {
            "id": 16,
            "version": "v1.0.0",
            "jira_ticket": "SC-2300",
            "run_status": "complete",
            "last_updated_date": "2019-07-11T16:48:54.302802-07:00",
            "submission_date": "2019-06-14",
            "description": "2019-06-14",
            "tenx_library": 63,
            "tenxsequencing_set": []
        },
        {
            "id": 17,
            "version": "v1.0.0",
            "jira_ticket": "SC-2301",
            "run_status": "complete",
            "last_updated_date": "2019-07-11T16:48:54.307611-07:00",
            "submission_date": "2019-06-14",
            "description": "2019-06-14",
            "tenx_library": 64,
            "tenxsequencing_set": []
        },
        {
            "id": 18,
            "version": "v1.0.0",
            "jira_ticket": "SC-2302",
            "run_status": "complete",
            "last_updated_date": "2019-07-11T16:48:54.311996-07:00",
            "submission_date": "2019-06-14",
            "description": "2019-06-14",
            "tenx_library": 65,
            "tenxsequencing_set": []
        },
        {
            "id": 19,
            "version": "v1.0.0",
            "jira_ticket": "SC-2303",
            "run_status": "complete",
            "last_updated_date": "2019-07-11T16:48:54.316241-07:00",
            "submission_date": "2019-06-14",
            "description": "2019-06-14",
            "tenx_library": 66,
            "tenxsequencing_set": []
        },
        {
            "id": 20,
            "version": "v1.0.0",
            "jira_ticket": "SC-2304",
            "run_status": "complete",
            "last_updated_date": "2019-07-11T16:48:54.320834-07:00",
            "submission_date": "2019-06-14",
            "description": "2019-06-14",
            "tenx_library": 130,
            "tenxsequencing_set": []
        },
        {
            "id": 21,
            "version": "v1.0.0",
            "jira_ticket": "SC-2305",
            "run_status": "complete",
            "last_updated_date": "2019-07-11T16:48:54.325354-07:00",
            "submission_date": "2019-06-14",
            "description": "2019-06-14",
            "tenx_library": 144,
            "tenxsequencing_set": []
        },
        {
            "id": 22,
            "version": "v1.0.0",
            "jira_ticket": "SC-2306",
            "run_status": "complete",
            "last_updated_date": "2019-07-11T16:48:54.329662-07:00",
            "submission_date": "2019-06-14",
            "description": "2019-06-14",
            "tenx_library": 145,
            "tenxsequencing_set": []
        },
        {
            "id": 23,
            "version": "v1.0.0",
            "jira_ticket": "SC-2307",
            "run_status": "complete",
            "last_updated_date": "2019-07-11T16:48:54.334208-07:00",
            "submission_date": "2019-06-14",
            "description": "2019-06-14",
            "tenx_library": 146,
            "tenxsequencing_set": []
        },
        {
            "id": 24,
            "version": "v1.0.0",
            "jira_ticket": "SC-2314",
            "run_status": "complete",
            "last_updated_date": "2019-07-11T16:48:54.339265-07:00",
            "submission_date": "2019-06-16",
            "description": "2019-06-16",
            "tenx_library": 147,
            "tenxsequencing_set": []
        },
        {
            "id": 25,
            "version": "v1.0.0",
            "jira_ticket": "SC-2315",
            "run_status": "complete",
            "last_updated_date": "2019-07-11T16:48:54.343568-07:00",
            "submission_date": "2019-06-16",
            "description": "2019-06-16",
            "tenx_library": 148,
            "tenxsequencing_set": []
        },
        {
            "id": 26,
            "version": "v1.0.0",
            "jira_ticket": "SC-2316",
            "run_status": "complete",
            "last_updated_date": "2019-07-11T16:48:54.347945-07:00",
            "submission_date": "2019-06-16",
            "description": "2019-06-16",
            "tenx_library": 149,
            "tenxsequencing_set": []
        },
        {
            "id": 27,
            "version": "v1.0.0",
            "jira_ticket": "SC-2317",
            "run_status": "complete",
            "last_updated_date": "2019-07-11T16:48:54.352518-07:00",
            "submission_date": "2019-06-16",
            "description": "2019-06-16",
            "tenx_library": 150,
            "tenxsequencing_set": []
        },
        {
            "id": 28,
            "version": "v1.0.0",
            "jira_ticket": "SC-2318",
            "run_status": "complete",
            "last_updated_date": "2019-07-11T16:48:54.357185-07:00",
            "submission_date": "2019-06-16",
            "description": "2019-06-16",
            "tenx_library": 151,
            "tenxsequencing_set": []
        },
        {
            "id": 29,
            "version": "v1.0.0",
            "jira_ticket": "SC-2327",
            "run_status": "idle",
            "last_updated_date": "2019-07-11T16:48:54.361409-07:00",
            "submission_date": "2019-06-18",
            "description": "2019-06-18",
            "tenx_library": 152,
            "tenxsequencing_set": []
        },
        {
            "id": 30,
            "version": "v1.0.0",
            "jira_ticket": "SC-2328",
            "run_status": "idle",
            "last_updated_date": "2019-07-11T16:48:54.365937-07:00",
            "submission_date": "2019-06-18",
            "description": "2019-06-18",
            "tenx_library": 153,
            "tenxsequencing_set": []
        },
        {
            "id": 31,
            "version": "v1.0.0",
            "jira_ticket": "SC-2337",
            "run_status": "complete",
            "last_updated_date": "2019-07-11T16:48:54.370638-07:00",
            "submission_date": "2019-06-19",
            "description": "2019-06-19",
            "tenx_library": 206,
            "tenxsequencing_set": []
        },
        {
            "id": 32,
            "version": "v1.0.0",
            "jira_ticket": "SC-2338",
            "run_status": "complete",
            "last_updated_date": "2019-07-11T16:48:54.375540-07:00",
            "submission_date": "2019-06-19",
            "description": "2019-06-19",
            "tenx_library": 207,
            "tenxsequencing_set": []
        },
        {
            "id": 33,
            "version": "v1.0.0",
            "jira_ticket": "SC-2339",
            "run_status": "complete",
            "last_updated_date": "2019-07-11T16:48:54.379834-07:00",
            "submission_date": "2019-06-19",
            "description": "2019-06-19",
            "tenx_library": 208,
            "tenxsequencing_set": []
        },
        {
            "id": 34,
            "version": "v1.0.0",
            "jira_ticket": "SC-2340",
            "run_status": "complete",
            "last_updated_date": "2019-07-11T16:48:54.384327-07:00",
            "submission_date": "2019-06-19",
            "description": "2019-06-19",
            "tenx_library": 209,
            "tenxsequencing_set": []
        },
        {
            "id": 35,
            "version": "v1.0.0",
            "jira_ticket": "SC-2341",
            "run_status": "idle",
            "last_updated_date": "2019-07-11T16:48:54.389071-07:00",
            "submission_date": "2019-06-19",
            "description": "2019-06-19",
            "tenx_library": 216,
            "tenxsequencing_set": []
        },
        {
            "id": 36,
            "version": "v1.0.0",
            "jira_ticket": "SC-2356",
            "run_status": "complete",
            "last_updated_date": "2019-07-11T16:48:54.393723-07:00",
            "submission_date": "2019-06-24",
            "description": "2019-06-24",
            "tenx_library": 154,
            "tenxsequencing_set": []
        },
        {
            "id": 37,
            "version": "v1.0.0",
            "jira_ticket": "SC-2357",
            "run_status": "complete",
            "last_updated_date": "2019-07-11T16:48:54.398048-07:00",
            "submission_date": "2019-06-24",
            "description": "2019-06-24",
            "tenx_library": 155,
            "tenxsequencing_set": []
        },
        {
            "id": 38,
            "version": "v1.0.0",
            "jira_ticket": "SC-2358",
            "run_status": "complete",
            "last_updated_date": "2019-07-11T16:48:54.402506-07:00",
            "submission_date": "2019-06-24",
            "description": "2019-06-24",
            "tenx_library": 156,
            "tenxsequencing_set": []
        },
        {
            "id": 39,
            "version": "v1.0.0",
            "jira_ticket": "SC-2365",
            "run_status": "complete",
            "last_updated_date": "2019-07-11T16:48:54.407059-07:00",
            "submission_date": "2019-06-25",
            "description": "2019-06-25",
            "tenx_library": 157,
            "tenxsequencing_set": []
        },
        {
            "id": 40,
            "version": "v1.0.0",
            "jira_ticket": "SC-2366",
            "run_status": "complete",
            "last_updated_date": "2019-07-11T16:48:54.412119-07:00",
            "submission_date": "2019-06-26",
            "description": "2019-06-26",
            "tenx_library": 212,
            "tenxsequencing_set": []
        },
        {
            "id": 41,
            "version": "v1.0.0",
            "jira_ticket": "SC-2367",
            "run_status": "complete",
            "last_updated_date": "2019-07-11T16:48:54.416884-07:00",
            "submission_date": "2019-06-26",
            "description": "2019-06-26",
            "tenx_library": 136,
            "tenxsequencing_set": []
        },
        {
            "id": 42,
            "version": "v1.0.0",
            "jira_ticket": "SC-2368",
            "run_status": "complete",
            "last_updated_date": "2019-07-11T16:48:54.421375-07:00",
            "submission_date": "2019-06-26",
            "description": "2019-06-26",
            "tenx_library": 135,
            "tenxsequencing_set": []
        },
        {
            "id": 43,
            "version": "v1.0.0",
            "jira_ticket": "SC-2375",
            "run_status": "complete",
            "last_updated_date": "2019-07-11T16:48:54.425783-07:00",
            "submission_date": "2019-06-27",
            "description": "2019-06-27",
            "tenx_library": 213,
            "tenxsequencing_set": []
        },
        {
            "id": 44,
            "version": "v1.0.0",
            "jira_ticket": "SC-2377",
            "run_status": "idle",
            "last_updated_date": "2019-07-11T16:48:54.430151-07:00",
            "submission_date": "2019-06-28",
            "description": "2019-06-28",
            "tenx_library": 229,
            "tenxsequencing_set": []
        },
        {
            "id": 45,
            "version": "v1.0.0",
            "jira_ticket": "SC-2378",
            "run_status": "idle",
            "last_updated_date": "2019-07-11T16:48:54.434861-07:00",
            "submission_date": "2019-06-28",
            "description": "2019-06-28",
            "tenx_library": 73,
            "tenxsequencing_set": []
        },
        {
            "id": 46,
            "version": "v1.0.0",
            "jira_ticket": "SC-2379",
            "run_status": "idle",
            "last_updated_date": "2019-07-11T16:48:54.439509-07:00",
            "submission_date": "2019-06-28",
            "description": "2019-06-28",
            "tenx_library": 74,
            "tenxsequencing_set": []
        },
        {
            "id": 47,
            "version": "v1.0.0",
            "jira_ticket": "SC-2381",
            "run_status": "complete",
            "last_updated_date": "2019-07-11T16:48:54.444243-07:00",
            "submission_date": "2019-06-28",
            "description": "2019-06-28",
            "tenx_library": 217,
            "tenxsequencing_set": []
        },
        {
            "id": 48,
            "version": "v1.0.0",
            "jira_ticket": "SC-2466",
            "run_status": "idle",
            "last_updated_date": "2019-07-11T16:48:54.449531-07:00",
            "submission_date": "2019-07-03",
            "description": "2019-07-03",
            "tenx_library": 158,
            "tenxsequencing_set": []
        },
        {
            "id": 49,
            "version": "v1.0.0",
            "jira_ticket": "SC-2470",
            "run_status": "complete",
            "last_updated_date": "2019-07-11T16:48:54.454248-07:00",
            "submission_date": "2019-07-04",
            "description": "2019-07-04",
            "tenx_library": 115,
            "tenxsequencing_set": []
        },
        {
            "id": 50,
            "version": "v1.0.0",
            "jira_ticket": "SC-2471",
            "run_status": "idle",
            "last_updated_date": "2019-07-11T16:48:54.458896-07:00",
            "submission_date": "2019-07-05",
            "description": "2019-07-05",
            "tenx_library": 111,
            "tenxsequencing_set": []
        },
        {
            "id": 51,
            "version": "v1.0.0",
            "jira_ticket": "SC-2472",
            "run_status": "idle",
            "last_updated_date": "2019-07-11T16:48:54.463416-07:00",
            "submission_date": "2019-07-08",
            "description": "2019-07-08",
            "tenx_library": 58,
            "tenxsequencing_set": []
        },
        {
            "id": 52,
            "version": "v1.0.0",
            "jira_ticket": "SC-2473",
            "run_status": "idle",
            "last_updated_date": "2019-07-11T16:48:54.467941-07:00",
            "submission_date": "2019-07-08",
            "description": "2019-07-08",
            "tenx_library": 59,
            "tenxsequencing_set": []
        }]
def migrate_tenx_analyses(apps, schema_editor):
    TenxAnalyses = apps.get_model('tenx', 'TenxAnalysis')
    TenxLibraries = apps.get_model('tenx','TenxLibrary')
    for ca in data:
        tenx = TenxAnalyses.objects.create(
            version=ca["version"],
            jira_ticket=ca["jira_ticket"],
            run_status=ca["run_status"],
            last_updated_date=ca["last_updated_date"],
            submission_date=ca["submission_date"],
            description=ca["submission_date"]
        )
        tenx.save()
        tenx.tenx_library = TenxLibraries.objects.get(id=ca["tenx_library"])
        tenx.save()

class Migration(migrations.Migration):

    dependencies = [
        ('tenx', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate_tenx_analyses),
    ]
