# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-06 21:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenx', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tenxchip',
            table=None,
        ),
        migrations.AlterModelTable(
            name='tenxlane',
            table=None,
        ),
        migrations.AlterModelTable(
            name='tenxlibrary',
            table=None,
        ),
        migrations.AlterModelTable(
            name='tenxlibraryconstructioninformation',
            table=None,
        ),
        migrations.AlterModelTable(
            name='tenxlibraryquantificationandstorage',
            table=None,
        ),
        migrations.AlterModelTable(
            name='tenxlibrarysampledetail',
            table=None,
        ),
        migrations.AlterModelTable(
            name='tenxpool',
            table=None,
        ),
        migrations.AlterModelTable(
            name='tenxsequencing',
            table=None,
        ),
    ]
