# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-01 23:07
from __future__ import unicode_literals

from django.db import migrations


def append_condition_to_experimental_condition(apps, schema_editor):
    TenxLibrary = apps.get_model('tenx', 'tenxlibrary')

    for lib in TenxLibrary.objects.exclude(condition=None):
        print("EXP COND: ",lib.experimental_condition)
        print("COND: ", lib.condition)
        lib.experimental_condition = str(lib.experimental_condition) + "\n" + str(lib.condition)
        lib.save()

class Migration(migrations.Migration):

    dependencies = [
        ('tenx', '0002_auto_20190712_1142'),
    ]

    operations = [
        migrations.RunPython(append_condition_to_experimental_condition)
    ]
