# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-01 23:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenx', '0003_auto_20190801_1607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenxchip',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='historicaltenxlibrary',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='tenxlibrary',
            name='condition',
        ),
        migrations.AlterField(
            model_name='historicaltenxlibrarysampledetail',
            name='sample_prep_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Sample prep date'),
        ),
        migrations.AlterField(
            model_name='tenxlibrarysampledetail',
            name='sample_prep_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Sample prep date'),
        ),
        migrations.RemoveField(
            model_name='historicaltenxlibraryconstructioninformation',
            name='concentration',
        ),
        migrations.RemoveField(
            model_name='historicaltenxlibraryconstructioninformation',
            name='pool',
        ),
        migrations.RemoveField(
            model_name='historicaltenxlibrarysampledetail',
            name='sorting_location',
        ),
        migrations.RemoveField(
            model_name='tenxlibraryconstructioninformation',
            name='concentration',
        ),
        migrations.RemoveField(
            model_name='tenxlibraryconstructioninformation',
            name='pool',
        ),
        migrations.RemoveField(
            model_name='tenxlibrarysampledetail',
            name='sorting_location',
        ),
        migrations.AddField(
            model_name='historicaltenxlibraryquantificationandstorage',
            name='dna_concentration_bp',
            field=models.IntegerField(blank=True, null=True, verbose_name='DNA Concentration(bp)'),
        ),
        migrations.AddField(
            model_name='historicaltenxlibraryquantificationandstorage',
            name='dna_concentration_ng',
            field=models.IntegerField(blank=True, null=True, verbose_name='DNA Concentration(ng/uL)'),
        ),
        migrations.AddField(
            model_name='historicaltenxlibraryquantificationandstorage',
            name='dna_concentration_nm',
            field=models.IntegerField(blank=True, null=True, verbose_name='DNA Concentration(nM)'),
        ),
        migrations.AddField(
            model_name='tenxlibraryquantificationandstorage',
            name='dna_concentration_bp',
            field=models.IntegerField(blank=True, null=True, verbose_name='DNA Concentration(bp)'),
        ),
        migrations.AddField(
            model_name='tenxlibraryquantificationandstorage',
            name='dna_concentration_ng',
            field=models.IntegerField(blank=True, null=True, verbose_name='DNA Concentration(ng/uL)'),
        ),
        migrations.AddField(
            model_name='tenxlibraryquantificationandstorage',
            name='dna_concentration_nm',
            field=models.IntegerField(blank=True, null=True, verbose_name='DNA Concentration(nM)'),
        ),
        migrations.AlterField(
            model_name='historicaltenxlibraryconstructioninformation',
            name='chemistry_version',
            field=models.CharField(choices=[('VERSION_2', 'v2'), ('VERSION_3', 'v3')], default='VERSION_3',
                                   max_length=150, null=True, verbose_name='Chemistry Version'),
        ),
        migrations.AlterField(
            model_name='historicaltenxlibraryconstructioninformation',
            name='library_prep_location',
            field=models.CharField(blank=True, default='BCCRC', max_length=50, null=True,
                                   verbose_name='Library prep location'),
        ),
        migrations.AlterField(
            model_name='historicaltenxlibraryconstructioninformation',
            name='submission_date',
            field=models.DateField(blank=True, null=True, verbose_name='Library Prep Date'),
        ),
        migrations.AlterField(
            model_name='tenxlibraryconstructioninformation',
            name='chemistry_version',
            field=models.CharField(choices=[('VERSION_2', 'v2'), ('VERSION_3', 'v3')], default='VERSION_3',
                                   max_length=150, null=True, verbose_name='Chemistry Version'),
        ),
        migrations.AlterField(
            model_name='tenxlibraryconstructioninformation',
            name='library_prep_location',
            field=models.CharField(blank=True, default='BCCRC', max_length=50, null=True,
                                   verbose_name='Library prep location'),
        ),
        migrations.AlterField(
            model_name='tenxlibraryconstructioninformation',
            name='submission_date',
            field=models.DateField(blank=True, null=True, verbose_name='Library Prep Date'),
        ),
        migrations.AlterField(
            model_name='historicaltenxlibraryconstructioninformation',
            name='library_type',
            field=models.CharField(blank=True, choices=[("5'", "5'"), ("3'", "3'"), ('V(D)J', 'V(D)J')], default="3'",
                                   max_length=20, null=True, verbose_name='Library type'),
        ),
        migrations.AlterField(
            model_name='tenxlibraryconstructioninformation',
            name='library_type',
            field=models.CharField(blank=True, choices=[("5'", "5'"), ("3'", "3'"), ('V(D)J', 'V(D)J')], default="3'",
                                   max_length=20, null=True, verbose_name='Library type'),
        ),
    ]
