# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-01 23:49
from __future__ import unicode_literals

from django.db import migrations, models

# Library ID, Concentration
condition_list = [
( 58 , 96 ),
( 59 , 143 ),
( 60 , 110 ),
( 61 , 100 ),
( 72 , 295 ),
( 74 , 181 ),
( 75 , 224 ),
( 73 , 183 ),
( 71 , 106 ),
( 140 , 9 ),
( 139 , 7 ),
( 135 , 115 ),
( 136 , 76 ),
( 76 , 102 ),
( 137 , 13 ),
( 138 , 8 ),
( 134 , 8 ),
( 131 , 8 ),
( 133 , 7 ),
( 132 , 10 ),
( 210 , 139 ),
( 211 , 156 ),
( 213 , 132 ),
( 217 , 108 ),
( 206 , 65 ),
( 212 , 40 ),
( 207 , 75 ),
( 208 , 59 ),
( 209 , 106 ),
( 216 , 64 ),
( 214 , 55 ),
( 222 , 194 ),
( 221 , 29 ),
( 223 , 133 ),
( 224 , 114 ),
( 225 , 66 ),
( 219 , 67 ),
( 218 , 125 ),
( 227 , 33 ),
( 228 , 50 ),
( 220 , 111 ),
( 226 , 30 ),
( 229 , 63 ),
( 230 , 58 )
]

def library_concentration_update(apps, schema_editor):
    TenxLibrary = apps.get_model('tenx', 'tenxlibrary')
    for i in condition_list:
        library = TenxLibrary.objects.get(id=i[0])
        library.tenxlibraryquantificationandstorage.dna_concentration_nm = i[1]
        library.tenxlibraryquantificationandstorage.save()

class Migration(migrations.Migration):

    dependencies = [
        ('tenx', '0004_auto_20190801_1611'),
    ]

    operations = [
        migrations.RunPython(library_concentration_update)
    ]
