# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-16 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenx', '0005_library_rename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltenxsequencing',
            name='number_of_lanes_requested',
            field=models.PositiveIntegerField(default=1, verbose_name='Sequencing Goal'),
        ),
        migrations.AlterField(
            model_name='tenxsequencing',
            name='number_of_lanes_requested',
            field=models.PositiveIntegerField(default=1, verbose_name='Sequencing Goal'),
        ),
    ]
