# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-08 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenx', '0007_auto_20190702_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltenxsequencing',
            name='gsc_library_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='GSC Library ID'),
        ),
        migrations.AddField(
            model_name='tenxsequencing',
            name='gsc_library_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='GSC Library ID'),
        ),
    ]
