# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-11 21:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenx', '0008_auto_20190708_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenxsequencing',
            name='tenx_pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenx.TenxPool'),
        ),
    ]
