# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-19 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenx', '0009_auto_20190917_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltenxchip',
            name='lab_name',
            field=models.CharField(blank=True, choices=[('SA', 'Sam Aparicio'), ('DH', 'David Huntsman'), ('CS', 'Christian Steidl')], default='SA', max_length=50, null=True, verbose_name='Lab Name'),
        ),
        migrations.AlterField(
            model_name='tenxchip',
            name='lab_name',
            field=models.CharField(blank=True, choices=[('SA', 'Sam Aparicio'), ('DH', 'David Huntsman'), ('CS', 'Christian Steidl')], default='SA', max_length=50, null=True, verbose_name='Lab Name'),
        ),
    ]
