# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-11 21:54
from __future__ import unicode_literals

from django.db import migrations


def migrate_tenx_analyses(apps, schema_editor):
    CoreAnlayses = apps.get_model('core', 'Analysis')
    TenxAnalyses = apps.get_model('tenx', 'TenxAnalysis')
    for ca in CoreAnlayses.objects.all():
        print(ca.tenx_library)
        tenx = TenxAnalyses.objects.create(
            version=ca.version,
            jira_ticket=ca.jira_ticket,
            run_status=ca.run_status,
            last_updated_date=ca.last_updated_date,
            submission_date=ca.submission_date,
            description=ca.submission_date
        )
        tenx.save()
        tenx.tenx_library = ca.tenx_library
        tenx.save()



class Migration(migrations.Migration):

    dependencies = [
        ('tenx', '0010_auto_20190711_1453'),
    ]

    operations = [
        migrations.RunPython(migrate_tenx_analyses),
    ]
