# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-19 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenx', '0010_auto_20190919_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenxpool',
            name='construction_location',
            field=models.CharField(blank=True, choices=[('BCCAGSC', 'GSC'), ('UBCBRC', 'UBC'), ('BCCRC', 'BCCRC')], max_length=50, null=True, verbose_name='Construction Location'),
        ),
    ]
