# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-11 23:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenx', '0010_auto_20190711_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenxsequencing',
            name='analysis',
        ),
    ]
