# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-16 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenx', '0011_auto_20190919_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaltenxlibraryquantificationandstorage',
            old_name='dna_concentration_bp',
            new_name='average_size_bp'
        ),
        migrations.RenameField(
            model_name='tenxlibraryquantificationandstorage',
            old_name='dna_concentration_bp',
            new_name='average_size_bp'
        ),
        migrations.AlterField(
            model_name='historicaltenxlibraryquantificationandstorage',
            name='average_size_bp',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Average Size(bp)'),
        ),
        migrations.AlterField(
            model_name='tenxlibraryquantificationandstorage',
            name='average_size_bp',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Average Size(bp)'),
        ),
    ]
