# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-21 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenx', '0012_auto_20191016_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltenxlibrary',
            name='well_partition',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V'), ('W', 'W'), ('X', 'X'), ('Y', 'Y'), ('Z', 'Z'), ('', '')], default='', max_length=1, null=True, verbose_name='Well Partition'),
        ),
        migrations.AddField(
            model_name='tenxlibrary',
            name='well_partition',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V'), ('W', 'W'), ('X', 'X'), ('Y', 'Y'), ('Z', 'Z'), ('', '')], default='', max_length=1, null=True, verbose_name='Well Partition'),
        ),
        migrations.AlterField(
            model_name='historicaltenxlibrary',
            name='chip_well',
            field=models.IntegerField(choices=[(0, 'NOT SET'), (1, 'WELL_1'), (2, 'WELL_2'), (3, 'WELL_3'), (4, 'WELL_4'), (5, 'WELL_5'), (6, 'WELL_6'), (7, 'WELL_7'), (8, 'WELL_8')], default=0, verbose_name='Chip Well'),
        ),
        migrations.AlterField(
            model_name='tenxlibrary',
            name='chip_well',
            field=models.IntegerField(choices=[(0, 'NOT SET'), (1, 'WELL_1'), (2, 'WELL_2'), (3, 'WELL_3'), (4, 'WELL_4'), (5, 'WELL_5'), (6, 'WELL_6'), (7, 'WELL_7'), (8, 'WELL_8')], default=0, verbose_name='Chip Well'),
        ),
    ]
