# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-03-28 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenx', '0014_auto_20191112_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltenxsequencing',
            name='sequencing_instrument',
            field=models.CharField(blank=True, choices=[('HX', 'HiSeqX'), ('H2500', 'HiSeq2500'), ('N500', 'NextSeq500'), ('N550', 'NextSeq550'), ('MI', 'MiSeq'), ('BGI', 'BGI'), ('O', 'other')], default='HX', max_length=50, null=True, verbose_name='Sequencing instrument'),
        ),
        migrations.AlterField(
            model_name='tenxsequencing',
            name='sequencing_instrument',
            field=models.CharField(blank=True, choices=[('HX', 'HiSeqX'), ('H2500', 'HiSeq2500'), ('N500', 'NextSeq500'), ('N550', 'NextSeq550'), ('MI', 'MiSeq'), ('BGI', 'BGI'), ('O', 'other')], default='HX', max_length=50, null=True, verbose_name='Sequencing instrument'),
        ),
    ]
