# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=100, verbose_name='Sample ID')),
                ('pool_id', models.CharField(max_length=100, verbose_name='Pool ID')),
                ('jira_ticket', models.CharField(max_length=100, verbose_name='Jira Ticket')),
                ('pub_date', models.DateTimeField(verbose_name='Date added')),
                ('tube_label', models.CharField(blank=True, max_length=100, verbose_name='Tube Label')),
            ],
        ),
    ]
