# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-26 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170526_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryconstructioninformation',
            name='number_of_pcr_cycles',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of PCR cycles'),
        ),
    ]
