# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-21 18:40
from __future__ import unicode_literals

import core.helpers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sample_id_datamigration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChipRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='region_code')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Library', verbose_name='Library')),
            ],
            bases=(models.Model, core.helpers.FieldValue),
        ),
        migrations.CreateModel(
            name='ChipRegionMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata_field', models.CharField(blank=True, max_length=50, null=True, verbose_name='Metadata key')),
                ('metadata_value', models.CharField(blank=True, max_length=50, null=True, verbose_name='Metadata value')),
                ('chip_region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ChipRegion', verbose_name='Chip_Region')),
            ],
            bases=(models.Model, core.helpers.FieldValue),
        ),
        migrations.AddField(
            model_name='sublibraryinformation',
            name='chip_region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ChipRegion', verbose_name='Chip_Region'),
        ),
    ]
