# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-28 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20170621_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalsampleinformation',
            name='anatomic_site',
            field=models.CharField(max_length=50, null=True, verbose_name='Anatomic site'),
        ),
        migrations.AlterField(
            model_name='additionalsampleinformation',
            name='tissue_type',
            field=models.CharField(choices=[('N', 'Normal'), ('B', 'Benign'), ('PM', 'Pre-malignant'), ('M', 'Malignant'), ('NNP', 'Non-neoplastic Disease'), ('U', 'Undetermined'), ('HP', 'Hyperplasia'), ('MP', 'Metaplasia'), ('DP', 'Dysplasia')], max_length=50, null=True, verbose_name='Tissue type'),
        ),
    ]
