# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-28 21:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_chipmetadatafield_datamigration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chipregionmetadata',
            name='metadata_field_old',
        ),
    ]
