# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-13 03:33
from __future__ import unicode_literals

from django.db import migrations


def move_sequencing_to_lane(apps, schema_editor):
    Sequencing = apps.get_model('core', 'Sequencing')
    Lane = apps.get_model('core', 'Lane')
    for sequencing in Sequencing.objects.all():
        lane = Lane()
        lane.sequencing = sequencing
        lane.flow_cell_id = sequencing.sequencingdetail.flow_cell_id
        lane.path_to_archive = sequencing.sequencingdetail.path_to_archive
        lane.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_lane'),
    ]

    operations = [
        migrations.RunPython(move_sequencing_to_lane),
    ]
