# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-15 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_null_lanes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lane',
            name='flow_cell_id',
            field=models.CharField(max_length=50, verbose_name='Flow cell/Lane ID'),
        ),
    ]
