"""Holds constants for the core app.

Note: don't expect to find *all* constants in here, only some of them
(this was a late addition to the app).
"""

# Enumeration for TenxLibraryConstructionInformation library_type
# choices
FIVE_PRIME = "5'"
THREE_PRIME = "3'"
THREE_PRIME_BARCODING = "3' Feature barcoding"
ATACSEQ = "scATACseq"
VDJ = "V(D)J"
CNV = "CNV"

pathology_occurrence_choices = (
    ('PR', 'Primary'),
    ('RC', 'Recurrent or Relapse'),
    ('ME', 'Metastatic'),
    ('RM', 'Remission'),
    ('UN', 'Undetermined'),
    ('US', 'Unspecified'),
)

sex_choices = (
    ('M', 'Male'),
    ('F', 'Female'),
    ('X', 'Mixed'),
    ('U', 'Unknown'),
)

tissue_type_choices = (
    ('N', 'Normal'),
    ('B', 'Benign'),
    ('PM', 'Pre-malignant'),
    ('M', 'Malignant'),
    ('NNP', 'Non-neoplastic Disease'),
    ('U', 'Undetermined'),
    ('HP', 'Hyperplasia'),
    ('MP', 'Metaplasia'),
    ('DP', 'Dysplasia'),
)

treatment_status_choices = (
    ('PR', 'Pre-treatment'),
    ('IN', 'In-treatment'),
    ('PO', 'Post-treatment'),
    ('NA', 'N/A'),
    ('UN', 'Unknown'),
)
TISSUE_STATES = (
    ('NONE', 'None'),
    ('FROZ', 'Frozen'),
    ('FRES', 'Fresh'),
    ('DIG-FRES', 'Digested-Fresh'),
)

CHIP_WELL = (
    (0, 'NOT SET'),
    (1, 'WELL_1'),
    (2, 'WELL_2'),
    (3, 'WELL_3'),
    (4, 'WELL_4'),
    (5, 'WELL_5'),
    (6, 'WELL_6'),
    (7, 'WELL_7'),
    (8, 'WELL_8'),
)

WELL_PARTITIONS = (
    ('A', 'A'),
    ('B', 'B'),
    ('C', 'C'),
    ('D', 'D'),
    ('E', 'E'),
    ('F', 'F'),
    ('G', 'G'),
    ('H', 'H'),
    ('I', 'I'),
    ('J', 'J'),
    ('K', 'K'),
    ('L', 'L'),
    ('M', 'M'),
    ('N', 'N'),
    ('O', 'O'),
    ('P', 'P'),
    ('Q', 'Q'),
    ('R', 'R'),
    ('S', 'S'),
    ('T', 'T'),
    ('U', 'U'),
    ('V', 'V'),
    ('W', 'W'),
    ('X', 'X'),
    ('Y', 'Y'),
    ('Z', 'Z'),
    ('', ''),
)

TENX_LIBRARY_TYPE_CHOICES = (
    (FIVE_PRIME, FIVE_PRIME),
    (THREE_PRIME, THREE_PRIME),
    (THREE_PRIME_BARCODING, THREE_PRIME_BARCODING),
    (ATACSEQ, ATACSEQ),
    (VDJ, VDJ),
)

CHEMISTRY_VERSION_CHOICES = (("VERSION_1_1", "v1.1"), ("VERSION_2", "v2"), ("VERSION_3", "v3"), ("VERSION_3_1", "v3.1"))

spotting_location_choices = (
    ('AD', 'Aparicio Lab - Deckard'),
    ('AR', 'Aparicio Lab - Rachael'),
    ('H', 'Hansen Lab'),
    ('G', 'GSC'),
)

# choices
cell_state_choices = (
    ('C', 'Cells'),
    ('N', 'Nuclei'),
    ('M', 'Mixed'),
    ('U', 'Unknown'),
)

# choices
chip_format_choices = (
    ('W', 'Wafergen'),
    ('M', 'Microfluidic'),
    ('B', 'Bulk'),
    ('O', 'Other'),
)

qc_check_choices = (('P', 'Will sequence'), ('N', 'Will not sequence'), ('H', 'On Hold'))

# fields
rev_comp_override_choices = (
    ('i7,i5', 'No Reverse Complement'),
    ('i7,rev(i5)', 'Reverse Complement i5'),
    ('rev(i7),i5', 'Reverse Complement i7'),
    ('rev(i7),rev(i5)', 'Reverse Complement i7 and i5'),
)

# choices
sequencing_instrument_choices = (
    ('HX', 'HiSeqX'),
    ('H2500', 'HiSeq2500'),
    ('N500', 'NextSeq500'),
    ('N550', 'NextSeq550'),
    ('MI', 'MiSeq'),
    ('BGI', 'BGI'),
    ('O', 'other'),
)

sequencing_output_mode_choices = (
    ('L', 'Low'),
    ('M', 'Medium'),
    ('H', 'High'),
)

read_type_choices = (
    ('P', 'PET'),
    ('S', 'SET'),
)

SEQ_CENTER = (
    ('BCCAGSC', 'BCCAGSC'),
    ('UBCBRC', 'UBCBRC'),
)

# choices
plate_type_choices = (
    ('submitted', 'submitted'),
    ('sequenced', 'sequenced'),
    ('stored', 'stored'),
)

INPUT_TYPE = (('DLP', "DLP"), ('PBAL', "PBAL"), ('TENX', "TenX"))

##########
#SISYPHUS#
##########
# Choices for the run status
IDLE = 'idle'
ERROR = 'error'
RUNNING = 'running'
ARCHIVING = 'archiving'
COMPLETE = 'complete'
ALIGN_COMPLETE = 'align_complete'
HMMCOPY_COMPLETE = 'hmmcopy_complete'
ANNOTATION_COMPLETE = 'annotation_complete'

RUN_STATUS_CHOICES = (
    (IDLE, 'Idle'),
    (ERROR, 'Error'),
    (RUNNING, 'Running'),
    (ARCHIVING, 'Archiving'),
    (COMPLETE, 'Complete'),
    (ALIGN_COMPLETE, 'Align Complete'),
    (HMMCOPY_COMPLETE, 'Hmmcopy Complete'),
    (ANNOTATION_COMPLETE, "Annotation Complete"),
)

# Aligner choices
aligner_choices = (
    ('A', 'bwa-aln'),
    ('M', 'bwa-mem'),
)

# Smoothing choices
smoothing_choices = (
    ('M', 'modal'),
    ('L', 'loess'),
)

# choices
priority_level_choices = (
    ('L', 'Low'),
    ('M', 'Medium'),
    ('H', 'High'),
)

verified_choices = (
    ('T', 'True'),
    ('F', 'False'),
)

MONTAGE_STATUS_CHOICES = (
    ('Success', 'Success'),
    ('Error', 'Error'),
    ('Deleted', 'Deleted'),
    ('Ignore', 'Ignore'),
    ('Pending', 'Pending'),
)

# Enumeration for TenxLibraryConstructionInformation library_type
# choices

SI_GA_A1 = "SI-GA-A1,GGTTTACT,CTAAACGG,TCGGCGTC,AACCGTAA"
SI_GA_A2 = "SI-GA-A2,TTTCATGA,ACGTCCCT,CGCATGTG,GAAGGAAC"
SI_GA_A3 = "SI-GA-A3,CAGTACTG,AGTAGTCT,GCAGTAGA,TTCCCGAC"
SI_GA_A4 = "SI-GA-A4,TATGATTC,CCCACAGT,ATGCTGAA,GGATGCCG"
SI_GA_A5 = "SI-GA-A5,CTAGGTGA,TCGTTCAG,AGCCAATT,GATACGCC"
SI_GA_A6 = "SI-GA-A6,CGCTATGT,GCTGTCCA,TTGAGATC,AAACCGAG"
SI_GA_A7 = "SI-GA-A7,ACAGAGGT,TATAGTTG,CGGTCCCA,GTCCTAAC"
SI_GA_A8 = "SI-GA-A8,GCATCTCC,TGTAAGGT,CTGCGATG,AACGTCAA"
SI_GA_A9 = "SI-GA-A9,TCTTAAAG,CGAGGCTC,GTCCTTCT,AAGACGGA"
SI_GA_A10 = "SI-GA-A10,GAAACCCT,TTTCTGTC,CCGTGTGA,AGCGAAAG"
SI_GA_A11 = "SI-GA-A11,GTCCGGTC,AAGATCAT,CCTGAAGG,TGATCTCA"
SI_GA_A12 = "SI-GA-A12,AGTGGAAC,GTCTCCTT,TCACATCA,CAGATGGG"
SI_GA_B1 = "SI-GA-B1,GTAATCTT,TCCGGAAG,AGTTCGGC,CAGCATCA"
SI_GA_B2 = "SI-GA-B2,TACTCTTC,CCTGTGCG,GGACACGT,ATGAGAAA"
SI_GA_B3 = "SI-GA-B3,GTGTATTA,TGTGCGGG,ACCATAAC,CAACGCCT"
SI_GA_B4 = "SI-GA-B4,ACTTCATA,GAGATGAC,TGCCGTGG,CTAGACCT"
SI_GA_B5 = "SI-GA-B5,AATAATGG,CCAGGGCA,TGCCTCAT,GTGTCATC"
SI_GA_B6 = "SI-GA-B6,CGTTAATC,GCCACGCT,TTACTCAG,AAGGGTGA"
SI_GA_B7 = "SI-GA-B7,AAACCTCA,GCCTTGGT,CTGGACTC,TGTAGAAG"
SI_GA_B8 = "SI-GA-B8,AAAGTGCT,GCTACCTG,TGCTGTAA,CTGCAAGC"
SI_GA_B9 = "SI-GA-B9,CTGTAACT,TCTAGCGA,AGAGTGTG,GACCCTAC"
SI_GA_B10 = "SI-GA-B10,ACCGTATG,GATTAGAT,CTGACTGA,TGACGCCC"
SI_GA_B11 = "SI-GA-B11,GTTCCTCA,AGGTACGC,TAAGTATG,CCCAGGAT"
SI_GA_B12 = "SI-GA-B12,TACCACCA,CTAAGTTT,GGGTCAAG,ACTGTGGC"
SI_GA_C1 = "SI-GA-C1,CCACTTAT,AACTGGCG,TTGGCATA,GGTAACGC"
SI_GA_C2 = "SI-GA-C2,CCTAGACC,ATCTCTGT,TAGCTCTA,GGAGAGAG"
SI_GA_C3 = "SI-GA-C3,TCAGCCGT,CAGAGGCC,GGTCAATA,ATCTTTAG"
SI_GA_C4 = "SI-GA-C4,ACAATTCA,TGCGCAGC,CATCACTT,GTGTGGAG"
SI_GA_C5 = "SI-GA-C5,CGACTTGA,TACAGACT,ATTGCGTG,GCGTACAC"
SI_GA_C6 = "SI-GA-C6,ATTACTTC,TGCGAACT,GCATTCGG,CAGCGGAA"
SI_GA_C7 = "SI-GA-C7,GTCTCTCG,AATCTCTC,CGGAGGGA,TCAGAAAT"
SI_GA_C8 = "SI-GA-C8,GTTGAGAA,AGATCTGG,TCGATACT,CACCGCTC"
SI_GA_C9 = "SI-GA-C9,GCGCAGAA,ATCTTACC,TATGGTGT,CGAACCTG"
SI_GA_C10 = "SI-GA-C10,TCTCAGTG,GAGACTAT,CGCTTAGC,ATAGGCCA"
SI_GA_C11 = "SI-GA-C11,GAGGATCT,AGACCATA,TCCTGCGC,CTTATGAG"
SI_GA_C12 = "SI-GA-C12,TCTCGTTT,GGCTAGCG,ATGACCGC,CAAGTAAA"
SI_GA_D1 = "SI-GA-D1,CACTCGGA,GCTGAATT,TGAAGTAC,ATGCTCCG"
SI_GA_D2 = "SI-GA-D2,TAACAAGG,GGTTCCTC,ATCATGCA,CCGGGTAT"
SI_GA_D3 = "SI-GA-D3,ACATTACT,TTTGGGTA,CAGCCCAC,GGCAATGG"
SI_GA_D4 = "SI-GA-D4,CCCTAACA,ATTCCGAT,TGGATTGC,GAAGGCTG"
SI_GA_D5 = "SI-GA-D5,CTCGTCAC,GATCAGCA,ACAACAGG,TGGTGTTT"
SI_GA_D6 = "SI-GA-D6,CATGCGAT,TGATATTC,GTGATCGA,ACCCGACG"
SI_GA_D7 = "SI-GA-D7,ATTTGCTA,TAGACACC,CCACAGGG,GGCGTTAT"
SI_GA_D8 = "SI-GA-D8,GCAACAAA,TAGTTGTC,CGCCATCG,ATTGGCGT"
SI_GA_D9 = "SI-GA-D9,AGGAGATG,GATGTGGT,CTACATCC,TCCTCCAA"
SI_GA_D10 = "SI-GA-D10,CAATACCC,TGTCTATG,ACCACGAA,GTGGGTGT"
SI_GA_D11 = "SI-GA-D11,CTTTGCGG,TGCACAAA,AAGCAGTC,GCAGTTCT"
SI_GA_D12 = "SI-GA-D12,GCACAATG,CTTGGTAC,TGCACCGT,AAGTTGCA"
SI_GA_E1 = "SI-GA-E1,TGGTAAAC,GAAAGGGT,ACTGCTCG,CTCCTCTA"
SI_GA_E2 = "SI-GA-E2,GTGGTACC,TACTATAG,ACAAGGTA,CGTCCCGT"
SI_GA_E3 = "SI-GA-E3,AGGTATTG,CTCCTAGT,TCAAGGCC,GATGCCAA"
SI_GA_E4 = "SI-GA-E4,TTCGCCCT,GGATGGGC,AATCAATG,CCGATTAA"
SI_GA_E5 = "SI-GA-E5,CATTAGCG,TTCGCTGA,ACAAGAAT,GGGCTCTC"
SI_GA_E6 = "SI-GA-E6,CTGCGGCT,GACTCAAA,AGAAACTC,TCTGTTGG"
SI_GA_E7 = "SI-GA-E7,CACGCCTT,GTATATAG,TCTCGGGC,AGGATACA"
SI_GA_E8 = "SI-GA-E8,ATAGTTAC,TGCTGAGT,CCTACGTA,GAGCACCG"
SI_GA_E9 = "SI-GA-E9,TTGTTTCC,GGAGGAGG,CCTAACAA,AACCCGTT"
SI_GA_E10 = "SI-GA-E10,AAATGTGC,GGGCAAAT,TCTATCCG,CTCGCGTA"
SI_GA_E11 = "SI-GA-E11,AAGCGCTG,CGTTTGAT,GTAGCACA,TCCAATGC"
SI_GA_E12 = "SI-GA-E12,ACCGGCTC,GAGTTAGT,CGTCCTAG,TTAAAGCA"
SI_GA_F1 = "SI-GA-F1,GTTGCAGC,TGGAATTA,CAATGGAG,ACCCTCCT"
SI_GA_F2 = "SI-GA-F2,TTTACATG,CGCGATAC,ACGCGGGT,GAATTCCA"
SI_GA_F3 = "SI-GA-F3,TTCAGGTG,ACGGACAT,GATCTTGA,CGATCACC"
SI_GA_F4 = "SI-GA-F4,CCCAATAG,GTGTCGCT,AGAGTCGC,TATCGATA"
SI_GA_F5 = "SI-GA-F5,GACTACGT,CTAGCGAG,TCTATATC,AGGCGTCA"
SI_GA_F6 = "SI-GA-F6,CGGAGCAC,GACCTATT,ACTTAGGA,TTAGCTCG"
SI_GA_F7 = "SI-GA-F7,CGTGCAGA,AACAAGAT,TCGCTTCG,GTATGCTC"
SI_GA_F8 = "SI-GA-F8,CATGAACA,TCACTCGC,AGCTGGAT,GTGACTTG"
SI_GA_F9 = "SI-GA-F9,CAAGCTCC,GTTCACTG,TCGTGAAA,AGCATGGT"
SI_GA_F10 = "SI-GA-F10,GCTTGGCT,AAACAAAC,CGGGCTTA,TTCATCGG"
SI_GA_F11 = "SI-GA-F11,GCGAGAGT,TACGTTCA,AGTCCCAC,CTATAGTG"
SI_GA_F12 = "SI-GA-F12,TGATGCAT,GCTACTGA,CACCTGCC,ATGGAATG"
SI_GA_G1 = "SI-GA-G1,ATGAATCT,GATCTCAG,CCAGGAGC,TGCTCGTA"
SI_GA_G2 = "SI-GA-G2,TGATTCTA,ACTAGGAG,CAGCCACT,GTCGATGC"
SI_GA_G3 = "SI-GA-G3,CCTCATTC,AGCATCCG,GTGGCAAT,TAATGGGA"
SI_GA_G4 = "SI-GA-G4,GCGATGTG,AGATACAA,TTTCCACT,CACGGTGC"
SI_GA_G5 = "SI-GA-G5,GAGCAAGA,TCTGTGAT,CGCAGTTC,ATATCCCG"
SI_GA_G6 = "SI-GA-G6,CTGACGCG,GGTCGTAC,TCCTTCTT,AAAGAAGA"
SI_GA_G7 = "SI-GA-G7,GGTATGCA,CTCGAAAT,ACACCTTC,TAGTGCGG"
SI_GA_G8 = "SI-GA-G8,TATGAGCT,CCGATAGC,ATACCCAA,GGCTGTTG"
SI_GA_G9 = "SI-GA-G9,TAGGACGT,ATCCCACA,GGAATGTC,CCTTGTAG"
SI_GA_G10 = "SI-GA-G10,TCGCCAGC,AATGTTAG,CGATAGCT,GTCAGCTA"
SI_GA_G11 = "SI-GA-G11,TTATCGTT,AGCAGAGC,CATCTCCA,GCGGATAG"
SI_GA_G12 = "SI-GA-G12,ATTCTAAG,CCCGATTA,TGGAGGCT,GAATCCGC"
SI_GA_H1 = "SI-GA-H1,GTATGTCA,TGTCAGAC,CACGTCGG,ACGACATT"
SI_GA_H2 = "SI-GA-H2,TAATGACC,ATGCCTTA,GCCGAGAT,CGTATCGG"
SI_GA_H3 = "SI-GA-H3,CCAAGATG,AGGCCCGA,TACGTGAC,GTTTATCT"
SI_GA_H4 = "SI-GA-H4,GCCATTCC,CAAGAATT,TTGCCGGA,AGTTGCAG"
SI_GA_H5 = "SI-GA-H5,CCACTACA,GATTCTGG,TGCGGCTT,ATGAAGAC"
SI_GA_H6 = "SI-GA-H6,TAGGATAA,CCTTTGTC,GTACGCGG,AGCACACT"
SI_GA_H7 = "SI-GA-H7,AGCTATCA,CATATAAC,TCAGGGTG,GTGCCCGT"
SI_GA_H8 = "SI-GA-H8,TTGTTGAT,GCTCAACC,CAAAGTGG,AGCGCCTA"
SI_GA_H9 = "SI-GA-H9,ACACTGTT,CAGGATGG,GGCTGAAC,TTTACCCA"
SI_GA_H10 = "SI-GA-H10,GTAATTGC,AGTCGCTT,CACGAGAA,TCGTCACG"
SI_GA_H11 = "SI-GA-H11,GGCGAGTA,ACTTCTAT,CAAATACG,TTGCGCGC"
SI_GA_H12 = "SI-GA-H12,GACAGCAT,TTTGTACA,AGGCCGTG,CCATATGC"
SI_NA_A1 = "SI-NA-A1,AAACGGCG,CCTACCAT,GGCGTTTC,TTGTAAGA"
SI_NA_B1 = "SI-NA-B1,AGGCTACC,CTAGCTGT,GCCAACAA,TATTGGTG"
SI_NA_C1 = "SI-NA-C1,AGACTTTC,CCGAGGCA,GATGCAGT,TTCTACAG"
SI_NA_D1 = "SI-NA-D1,AGCTGCGT,CAACCATC,GTGGAGCA,TCTATTAG"
SI_NA_E1 = "SI-NA-E1,ACGAAAGC,CGCCCGTA,GTTTGCCT,TAAGTTAG"
SI_NA_F1 = "SI-NA-F1,ATCGCTCC,CCGTACAG,GATAGGTA,TGACTAGT"
SI_NA_G1 = "SI-NA-G1,ATGCGATT,CATATGCG,GGATACGA,TCCGCTAC"
SI_NA_H1 = "SI-NA-H1,AAACTCAT,CGGGAGTA,GTCACAGG,TCTTGTCC"
SI_NA_A2 = "SI-NA-A2,AGCCCTTT,CAAGTCCA,GTGAGAAG,TCTTAGGC"
SI_NA_B2 = "SI-NA-B2,AAGTTGAT,CCCACCCA,GGTCGAGC,TTAGATTG"
SI_NA_C2 = "SI-NA-C2,AATCACTA,CCGAGAAC,GTAGTGCG,TGCTCTGT"
SI_NA_D2 = "SI-NA-D2,ACATTCCG,CTGCGGTA,GACACAAT,TGTGATGC"
SI_NA_E2 = "SI-NA-E2,AGGCTGGT,CACAACTA,GTTGGTCC,TCATCAAG"
SI_NA_F2 = "SI-NA-F2,ATGGTTAG,CATTGATA,GCAAACGC,TGCCCGCT"
SI_NA_G2 = "SI-NA-G2,ATAACCTA,CGGTGAGC,GATCTTAT,TCCGAGCG"
SI_NA_H2 = "SI-NA-H2,AACGGTCA,CCGAACTC,GGTCCAAG,TTATTGGT"
SI_NA_A3 = "SI-NA-A3,AAAGCATA,CTGCAGCC,GCCTTTAT,TGTAGCGG"
SI_NA_B3 = "SI-NA-B3,ATTGGACG,CAGCTTAC,GGCAAGGA,TCATCCTT"
SI_NA_C3 = "SI-NA-C3,ACGTTACA,CGTAGGTT,GACGACGG,TTACCTAC"
SI_NA_D3 = "SI-NA-D3,ACTTCACT,CGAAGTTG,GAGCACGC,TTCGTGAA"
SI_NA_E3 = "SI-NA-E3,AACAAGTC,CGGCTCCA,GTATGTAT,TCTGCAGG"
SI_NA_F3 = "SI-NA-F3,AGTCTGTA,CAGAATAG,GCCTCCGT,TTAGGACC"
SI_NA_G3 = "SI-NA-G3,ATGTCCAG,CGACGTCA,GCTATAGC,TACGAGTT"
SI_NA_H3 = "SI-NA-H3,ACACCTAA,CGTTTGGG,GACAAACC,TTGGGCTT"
SI_NA_A4 = "SI-NA-A4,AGAACGCC,CATGGCAG,GTCTTTGA,TCGCAATT"
SI_NA_B4 = "SI-NA-B4,AGGGACTG,CCTCTAAC,GACAGGCT,TTATCTGA"
SI_NA_C4 = "SI-NA-C4,ACATTGGC,CTTAGTCA,GAGCCCAT,TGCGAATG"
SI_NA_D4 = "SI-NA-D4,AAATCGTC,CTTCGAAT,GCGATCGG,TGCGATCA"
SI_NA_E4 = "SI-NA-E4,AGCTGACG,CCGGTGTC,GTAAACAT,TATCCTGA"
SI_NA_F4 = "SI-NA-F4,AACGACAC,CGTCCTCT,GCATGATA,TTGATGGG"
SI_NA_G4 = "SI-NA-G4,AGCTTCTC,CCTGCGGT,GTACAACG,TAGAGTAA"
SI_NA_H4 = "SI-NA-H4,ACTGGAGC,CGGTCGTG,GAAATCAA,TTCCATCT"
SI_NA_A5 = "SI-NA-A5,ATTGGGAA,CAGTCTGG,GGCATACT,TCACACTC"
SI_NA_B5 = "SI-NA-B5,ATCGTACT,CATCAGTG,GGGACTAC,TCATGCGA"
SI_NA_C5 = "SI-NA-C5,ATGCATTC,CACTGACT,GGTACGGG,TCAGTCAA"
SI_NA_D5 = "SI-NA-D5,AGACGGAT,CCTTTAGA,GTCGACTC,TAGACTCG"
SI_NA_E5 = "SI-NA-E5,ATCCAAGG,CCGTTGAA,GGAAGCTC,TATGCTCT"
SI_NA_F5 = "SI-NA-F5,AACACAGC,CGGTTTAG,GTACGGCT,TCTGACTA"
SI_NA_G5 = "SI-NA-G5,ATGAAGTA,CGCCGAAC,GAAGCTCG,TCTTTCGT"
SI_NA_H5 = "SI-NA-H5,ATAGTATG,CCGCGTCT,GGCTCCAC,TATAAGGA"
SI_NA_A6 = "SI-NA-A6,ACGGGACT,CTTTCGAC,GAACATGA,TGCATCTG"
SI_NA_B6 = "SI-NA-B6,AACGCGAA,CTATTTGG,GCGCACCT,TGTAGATC"
SI_NA_C6 = "SI-NA-C6,ACTCAGAC,CGCTCAGG,GAGGTTTA,TTAAGCCT"
SI_NA_D6 = "SI-NA-D6,ATGCCAAA,CCTTATCG,GAAGTCTT,TGCAGGGC"
SI_NA_E6 = "SI-NA-E6,ATTGAAAC,CAGCCCGA,GCCATTTG,TGATGGCT"
SI_NA_F6 = "SI-NA-F6,ATGCCGGC,CCTAATTA,GACTTCCT,TGAGGAAG"
SI_NA_G6 = "SI-NA-G6,AGCACTGG,CATTACAC,GTGCGACA,TCAGTGTT"
SI_NA_H6 = "SI-NA-H6,AAGCATAA,CCCATCGC,GGTTGATG,TTAGCGCT"
SI_NA_A7 = "SI-NA-A7,AGGTCATA,CTCATCAT,GCTGAGGG,TAACGTCC"
SI_NA_B7 = "SI-NA-B7,AGGGATGA,CTTCTGTT,GAATGCAC,TCCACACG"
SI_NA_C7 = "SI-NA-C7,ACACCGGG,CATAATCC,GGCGGAAT,TTGTTCTA"
SI_NA_D7 = "SI-NA-D7,AACTTAGA,CCGGATCC,GGTCGCAT,TTAACGTG"
SI_NA_E7 = "SI-NA-E7,AAGACGTG,CCATGTGT,GTTCACAA,TGCGTACC"
SI_NA_F7 = "SI-NA-F7,ACCCGAGA,CAAACTTT,GGTTAGAC,TTGGTCCG"
SI_NA_G7 = "SI-NA-G7,ATTACCGG,CAGTAATT,GCCGGTAA,TGACTGCC"
SI_NA_H7 = "SI-NA-H7,AACGGGTG,CTAATTCT,GCTTCAAC,TGGCACGA"
SI_NA_A8 = "SI-NA-A8,ATGATACG,CCACAGAA,GACTGTTC,TGTGCCGT"
SI_NA_B8 = "SI-NA-B8,ACGTTCAC,CAAGGTCT,GTTAAGTG,TGCCCAGA"
SI_NA_C8 = "SI-NA-C8,AGCTCGAG,CAGGAAGA,GCACGTTT,TTTATCCC"
SI_NA_D8 = "SI-NA-D8,AATCTTTG,CTCAAGAC,GGATGAGT,TCGGCCCA"
SI_NA_E8 = "SI-NA-E8,AGCCTATG,CTAACGCA,GCTTACAT,TAGGGTGC"
SI_NA_F8 = "SI-NA-F8,AGTTGGGA,CCAGAAAG,GTGCCCTC,TACATTCT"
SI_NA_G8 = "SI-NA-G8,AAGTACTC,CTTGGAGA,GGAACTCT,TCCCTGAG"
SI_NA_H8 = "SI-NA-H8,AAGAGCGG,CTTGTTAT,GGCCCATC,TCATAGCA"
SI_NA_A9 = "SI-NA-A9,ACAACTTG,CTCCAACA,GAGTGCGT,TGTGTGAC"
SI_NA_B9 = "SI-NA-B9,AAGCGTGT,CTTGACCG,GCCACGTA,TGATTAAC"
SI_NA_C9 = "SI-NA-C9,AGATCGGT,CATCGTCG,GTCATATA,TCGGACAC"
SI_NA_D9 = "SI-NA-D9,ACCTACTG,CAAGGGAC,GGGACACA,TTTCTTGT"
SI_NA_E9 = "SI-NA-E9,AGTAAGCA,CCGGTAAT,GTATCTTC,TACCGCGG"
SI_NA_F9 = "SI-NA-F9,AGTTAGTT,CACGCACG,GTACTTAA,TCGAGCGC"
SI_NA_G9 = "SI-NA-G9,AGTCTCAG,CAATGGCA,GCCGAAGT,TTGACTTC"
SI_NA_H9 = "SI-NA-H9,ACCTGCCA,CTTCATAC,GGAATATG,TAGGCGGT"
SI_NA_A10 = "SI-NA-A10,ACAGCAAC,CGCAATTT,GAGTTGCG,TTTCGCGA"
SI_NA_B10 = "SI-NA-B10,ACCATTAA,CTGGACGT,GAACGGTC,TGTTCACG"
SI_NA_C10 = "SI-NA-C10,ATCTGATC,CGTGCTAA,GAGAAGGG,TCACTCCT"
SI_NA_D10 = "SI-NA-D10,AGATAACA,CTTATTTG,GCGGGCAT,TACCCGGC"
SI_NA_E10 = "SI-NA-E10,ATTGTTTC,CGCAGGAG,GCACCAGT,TAGTACCA"
SI_NA_F10 = "SI-NA-F10,ATTCGTGC,CGCGTGCA,GAATACTG,TCGACAAT"
SI_NA_G10 = "SI-NA-G10,ATACTGAG,CGGAGACT,GATGCCTC,TCCTATGA"
SI_NA_H10 = "SI-NA-H10,ATTTCAGC,CGAGTGAT,GACCGCCA,TCGAATTG"
SI_NA_A11 = "SI-NA-A11,ACCAGTCC,CTTTCCTT,GGACAGGG,TAGGTAAA"
SI_NA_B11 = "SI-NA-B11,ATGGTCGC,CGACATAG,GATTCGCT,TCCAGATA"
SI_NA_C11 = "SI-NA-C11,ACCGAACA,CGACTCTT,GTTTGTGG,TAGACGAC"
SI_NA_D11 = "SI-NA-D11,ATATGAGA,CACCTCAG,GCTACTTC,TGGGAGCT"
SI_NA_E11 = "SI-NA-E11,ATCGCCAT,CATAAAGG,GGGTTTCC,TCACGGTA"
SI_NA_F11 = "SI-NA-F11,AGCAGTTA,CTTGTACC,GAACCCGG,TCGTAGAT"
SI_NA_G11 = "SI-NA-G11,AGGGCGTT,CTATACGC,GCTCGTCA,TACATAAG"
SI_NA_H11 = "SI-NA-H11,AGGATCGA,CACGATTC,GTATCGAG,TCTCGACT"
SI_NA_A12 = "SI-NA-A12,ACTACTGT,CGGGAACG,GACCTCTC,TTATGGAA"
SI_NA_B12 = "SI-NA-B12,ACGCTTGG,CGCTACAT,GAAAGACA,TTTGCGTC"
SI_NA_C12 = "SI-NA-C12,ATCCGGCA,CCGTTATG,GGTAATGT,TAAGCCAC"
SI_NA_D12 = "SI-NA-D12,AGAAACGT,CACTCAAC,GCTGTGTA,TTGCGTCG"
SI_NA_E12 = "SI-NA-E12,ACGCGGAA,CGCTATCC,GTTGCATG,TAAATCGT"
SI_NA_F12 = "SI-NA-F12,AATTGAAC,CCAGTGGA,GTCCATTG,TGGACCCT"
SI_NA_G12 = "SI-NA-G12,ACCCGCAC,CATGCGTA,GTGATAGT,TGATATCG"
SI_NA_H12 = "SI-NA-H12,ACGAGTAG,CAATCCCT,GTCCAGGC,TGTGTATA"
SI_NN_A1 = "SI-NN-A1,GCCTTGTCAA,GATCCAATCA,TGATTGGATC"
SI_NN_A2 = "SI-NN-A2,AACTTCTTTG,ATAAGCGGTA,TACCGCTTAT"
SI_NN_A3 = "SI-NN-A3,TGGTTATAGA,GAGCTCATAA,TTATGAGCTC"
SI_NN_A4 = "SI-NN-A4,GTAGTGCATC,ATTTGACGGT,ACCGTCAAAT"
SI_NN_A5 = "SI-NN-A5,GCTTGATTTA,CGGGTGTGAC,GTCACACCCG"
SI_NN_A6 = "SI-NN-A6,GAAGTTTCGC,TTTCAAAGCA,TGCTTTGAAA"
SI_NN_A7 = "SI-NN-A7,GCAGTTGTTT,ACACTACTTT,AAAGTAGTGT"
SI_NN_A8 = "SI-NN-A8,GCCGCAAGTA,AAAGGTCCGC,GCGGACCTTT"
SI_NN_A9 = "SI-NN-A9,AAGTTGTATG,TGTACAATGC,GCATTGTACA"
SI_NN_A10 = "SI-NN-A10,AGCAACCTTT,TTCAGCGCTA,TAGCGCTGAA"
SI_NN_A11 = "SI-NN-A11,GACGAGGGTT,TTACTTTGAC,GTCAAAGTAA"
SI_NN_A12 = "SI-NN-A12,TGAACAGTCG,ATTTCTCAGA,TCTGAGAAAT"
SI_NN_B1 = "SI-NN-B1,CGAAAGGAGT,ACACCAAACA,TGTTTGGTGT"
SI_NN_B2 = "SI-NN-B2,GAATGACTTG,TGAGCTCGCT,AGCGAGCTCA"
SI_NN_B3 = "SI-NN-B3,GCCAGGGATT,CAAGTTTAGG,CCTAAACTTG"
SI_NN_B4 = "SI-NN-B4,CTTTGTCCGC,GCTGTCCCGT,ACGGGACAGC"
SI_NN_B5 = "SI-NN-B5,AGCTTGGGTG,AGCGTATAGT,ACTATACGCT"
SI_NN_B6 = "SI-NN-B6,TCGCACCGGT,TAGCCTCAGG,CCTGAGGCTA"
SI_NN_B7 = "SI-NN-B7,TTTAGGTAGG,ACTGAGGGAC,GTCCCTCAGT"
SI_NN_B8 = "SI-NN-B8,GTTCGAGCGG,CTGTGGGTTT,AAACCCACAG"
SI_NN_B9 = "SI-NN-B9,AGGGTATGGC,GAGTCCGACT,AGTCGGACTC"
SI_NN_B10 = "SI-NN-B10,TACCCACTAT,TGGAACATAT,ATATGTTCCA"
SI_NN_B11 = "SI-NN-B11,TTCAGGCTAC,CTGGGTATTG,CAATACCCAG"
SI_NN_B12 = "SI-NN-B12,AGGAATAGAT,TGCGGTCACG,CGTGACCGCA"
SI_NN_C1 = "SI-NN-C1,ACAGCGCTGT,GAGGGTCATC,GATGACCCTC"
SI_NN_C2 = "SI-NN-C2,GACGTACGGA,ACCTCGCTTT,AAAGCGAGGT"
SI_NN_C3 = "SI-NN-C3,CTTAGATGCA,CTATTCGACT,AGTCGAATAG"
SI_NN_C4 = "SI-NN-C4,ACTCCTCAAC,ATTCACGGGA,TCCCGTGAAT"
SI_NN_C5 = "SI-NN-C5,TCCATACTGT,GAGCGACTTC,GAAGTCGCTC"
SI_NN_C6 = "SI-NN-C6,GCCAGAATGG,GAATTGTATC,GATACAATTC"
SI_NN_C7 = "SI-NN-C7,ATTGCAAGAC,CGGTGACCAT,ATGGTCACCG"
SI_NN_C8 = "SI-NN-C8,CAACATATCG,AACTAAAGGC,GCCTTTAGTT"
SI_NN_C9 = "SI-NN-C9,CAGGGACCTC,AATAGCAGCA,TGCTGCTATT"
SI_NN_C10 = "SI-NN-C10,ATTTGGGAAT,TCAGCCGAGT,ACTCGGCTGA"
SI_NN_C11 = "SI-NN-C11,TGGATAATTG,TTTGTGATCA,TGATCACAAA"
SI_NN_C12 = "SI-NN-C12,CAGATTATGA,GTGCCTGTAC,GTACAGGCAC"
SI_NN_D1 = "SI-NN-D1,AATGGTAAGC,CTGTGAAGTT,AACTTCACAG"
SI_NN_D2 = "SI-NN-D2,CATCCCTCGG,AGGGTAGGCG,CGCCTACCCT"
SI_NN_D3 = "SI-NN-D3,CTGGTCCGTC,ACGAATAAGG,CCTTATTCGT"
SI_NN_D4 = "SI-NN-D4,GTCGTAAATT,GTAGTAGGCT,AGCCTACTAC"
SI_NN_D5 = "SI-NN-D5,CAACACTGAT,CAAACCAGGG,CCCTGGTTTG"
SI_NN_D6 = "SI-NN-D6,CAGACTGAAT,TGCCTAACCG,CGGTTAGGCA"
SI_NN_D7 = "SI-NN-D7,CGGACACGCT,TCACGATATA,TATATCGTGA"
SI_NN_D8 = "SI-NN-D8,CTCGGCTCTC,TATACTTCCA,TGGAAGTATA"
SI_NN_D9 = "SI-NN-D9,AAGCCTATCA,GTAGTGAACA,TGTTCACTAC"
SI_NN_D10 = "SI-NN-D10,ACTGTGCCAA,TAACCGTTAT,ATAACGGTTA"
SI_NN_D11 = "SI-NN-D11,CTACTCCCAT,TACGTTGCGG,CCGCAACGTA"
SI_NN_D12 = "SI-NN-D12,AGACTCTAAC,GTGTCGATGT,ACATCGACAC"
SI_NN_E1 = "SI-NN-E1,TGAGCCGGCA,TGCTGCATGT,ACATGCAGCA"
SI_NN_E2 = "SI-NN-E2,TAGCTTGCGT,GCTGCTAAAG,CTTTAGCAGC"
SI_NN_E3 = "SI-NN-E3,GTACACCGGG,AACAGTCGCG,CGCGACTGTT"
SI_NN_E4 = "SI-NN-E4,CGCGTAGACG,AAAGTAGCTG,CAGCTACTTT"
SI_NN_E5 = "SI-NN-E5,CCGATATATT,AACTATCCGA,TCGGATAGTT"
SI_NN_E6 = "SI-NN-E6,TTGGGCGGGA,ATGTATCTGT,ACAGATACAT"
SI_NN_E7 = "SI-NN-E7,GTTTATGAGG,GCCAAACAGC,GCTGTTTGGC"
SI_NN_E8 = "SI-NN-E8,TTGGATACTC,CGTACTGAAG,CTTCAGTACG"
SI_NN_E9 = "SI-NN-E9,GCTATCTATC,AAAGATGGAT,ATCCATCTTT"
SI_NN_E10 = "SI-NN-E10,ATGTGATCGC,TGACCTACCT,AGGTAGGTCA"
SI_NN_E11 = "SI-NN-E11,TCCTCACATG,AACAGATTCA,TGAATCTGTT"
SI_NN_E12 = "SI-NN-E12,GCCTCCTAAT,CTCCTCCTGT,ACAGGAGGAG"
SI_NN_F1 = "SI-NN-F1,CGAGGCTGAT,TCGACTTTCT,AGAAAGTCGA"
SI_NN_F2 = "SI-NN-F2,CTCATGACAT,TGTTCCGCAC,GTGCGGAACA"
SI_NN_F3 = "SI-NN-F3,AACGCGGCAA,GCCCGTTTAC,GTAAACGGGC"
SI_NN_F4 = "SI-NN-F4,AACACCTCTC,GATTGTATGA,TCATACAATC"
SI_NN_F5 = "SI-NN-F5,AAATAACGCG,ATAGAGGAGC,GCTCCTCTAT"
SI_NN_F6 = "SI-NN-F6,GAAATCTTGT,TAGACGCCAC,GTGGCGTCTA"
SI_NN_F7 = "SI-NN-F7,TAGATGGACT,CCAGGGATAT,ATATCCCTGG"
SI_NN_F8 = "SI-NN-F8,CAATCTGTAT,TCCCATCGTT,AACGATGGGA"
SI_NN_F9 = "SI-NN-F9,GCGAAAGTAT,GTGTCACAGA,TCTGTGACAC"
SI_NN_F10 = "SI-NN-F10,CCCAGAGCTT,ATGCTGTAAT,ATTACAGCAT"
SI_NN_F11 = "SI-NN-F11,GACTACAGGA,AGTGACAAAG,CTTTGTCACT"
SI_NN_F12 = "SI-NN-F12,CAATTCATGG,ACGTAGTTCG,CGAACTACGT"
SI_NN_G1 = "SI-NN-G1,TGGGAAGGGC,ACTAACGATG,CATCGTTAGT"
SI_NN_G2 = "SI-NN-G2,TACTTCGCAT,AACGGTGTCG,CGACACCGTT"
SI_NN_G3 = "SI-NN-G3,TAAACTGGCA,CCGACCTCTT,AAGAGGTCGG"
SI_NN_G4 = "SI-NN-G4,TTGAAGAACT,CAACACCAGG,CCTGGTGTTG"
SI_NN_G5 = "SI-NN-G5,TCCCTCGTCA,ATCAGGTGTG,CACACCTGAT"
SI_NN_G6 = "SI-NN-G6,ACTGGCCTAA,CGCTCCCTTG,CAAGGGAGCG"
SI_NN_G7 = "SI-NN-G7,TCATAATGCA,GATGAGGCGA,TCGCCTCATC"
SI_NN_G8 = "SI-NN-G8,CGCCACGTTA,CTTTCATAGG,CCTATGAAAG"
SI_NN_G9 = "SI-NN-G9,TGGACTAAGC,CTTAACATCG,CGATGTTAAG"
SI_NN_G10 = "SI-NN-G10,AAGCCCGGCA,GAGTTTCCGT,ACGGAAACTC"
SI_NN_G11 = "SI-NN-G11,ATAGTGGCGG,TACTGTTGTT,AACAACAGTA"
SI_NN_G12 = "SI-NN-G12,CCAACCGGAC,GTTCTATCTA,TAGATAGAAC"
SI_NN_H1 = "SI-NN-H1,TTACAGAGGG,GTTTATGGCA,TGCCATAAAC"
SI_NN_H2 = "SI-NN-H2,TCCAACAACG,GTCCGGGTTT,AAACCCGGAC"
SI_NN_H3 = "SI-NN-H3,AAAGCATGTC,AGATACTACT,AGTAGTATCT"
SI_NN_H4 = "SI-NN-H4,AGAAGTCGTT,AGGACATTTA,TAAATGTCCT"
SI_NN_H5 = "SI-NN-H5,GCTAGCGTTC,TCGCGTGGTG,CACCACGCGA"
SI_NN_H6 = "SI-NN-H6,CAACTAGCTT,TCAACTAATC,GATTAGTTGA"
SI_NN_H7 = "SI-NN-H7,AGGGCCAGTT,TAGGGCAAAT,ATTTGCCCTA"
SI_NN_H8 = "SI-NN-H8,CTCTATGCGT,CCTCTGATGC,GCATCAGAGG"
SI_NN_H9 = "SI-NN-H9,GTCCATACAA,AGCCACTCAC,GTGAGTGGCT"
SI_NN_H10 = "SI-NN-H10,AGGGATGCAA,CTCATATCCT,AGGATATGAG"
SI_NN_H11 = "SI-NN-H11,TTCAAGTCCT,CAGCAGCTAA,TTAGCTGCTG"
SI_NN_H12 = "SI-NN-H12,CTCCAACCTA,GCACCGCATC,GATGCGGTGC"
SI_NT_A1 = "SI-NT-A1,ATTTACCGCA,GACAATAAAG,CTTTATTGTC"
SI_NT_A2 = "SI-NT-A2,TTGTCGTAGA,CAATGTAGCA,TGCTACATTG"
SI_NT_A3 = "SI-NT-A3,AGTCCTGCGG,TGACACAAGT,ACTTGTGTCA"
SI_NT_A4 = "SI-NT-A4,TTGTTCATGT,TGACAGCTGA,TCAGCTGTCA"
SI_NT_A5 = "SI-NT-A5,TCAGGAAGGA,GAACGTGCTT,AAGCACGTTC"
SI_NT_A6 = "SI-NT-A6,CTGTTAGAGG,CCACGCTTCG,CGAAGCGTGG"
SI_NT_A7 = "SI-NT-A7,AGATGAGAAT,GTCGACGGGT,ACCCGTCGAC"
SI_NT_A8 = "SI-NT-A8,CCAAAGCCGG,ACCGTGCACA,TGTGCACGGT"
SI_NT_A9 = "SI-NT-A9,AGTCATAATG,AGGCTTGAAA,TTTCAAGCCT"
SI_NT_A10 = "SI-NT-A10,TTCATCAGAG,TTGTCGTCTC,GAGACGACAA"
SI_NT_A11 = "SI-NT-A11,GAAGCGCGAA,CAGCGAAATT,AATTTCGCTG"
SI_NT_A12 = "SI-NT-A12,ATCCGCCGAA,GCTACAGAAT,ATTCTGTAGC"
SI_NT_B1 = "SI-NT-B1,CTTATTGTGG,AGCTGTGGGT,ACCCACAGCT"
SI_NT_B2 = "SI-NT-B2,ATTCGTTGGG,CATCAGGAGC,GCTCCTGATG"
SI_NT_B3 = "SI-NT-B3,GTGGCCTCAT,TCGAAAGTGA,TCACTTTCGA"
SI_NT_B4 = "SI-NT-B4,CTATGGCATC,CTCTGAGCGC,GCGCTCAGAG"
SI_NT_B5 = "SI-NT-B5,AAACCACAGT,CCGCAAATGG,CCATTTGCGG"
SI_NT_B6 = "SI-NT-B6,ATGTATCCAC,CAGGCTGAGG,CCTCAGCCTG"
SI_NT_B7 = "SI-NT-B7,GATGAGTCTG,TATGTAACCG,CGGTTACATA"
SI_NT_B8 = "SI-NT-B8,CTCACAATAA,CCGTGTTTAA,TTAAACACGG"
SI_NT_B9 = "SI-NT-B9,TCTGTCGCAA,ATCCGAACTG,CAGTTCGGAT"
SI_NT_B10 = "SI-NT-B10,CATCGAGAAG,GTGCATCCGC,GCGGATGCAC"
SI_NT_B11 = "SI-NT-B11,ACGTATTGGG,CAATCGCAAA,TTTGCGATTG"
SI_NT_B12 = "SI-NT-B12,CTTACGCGAC,CCTGTCGGAT,ATCCGACAGG"
SI_NT_C1 = "SI-NT-C1,GATAGTGAAG,CGTTCGCCAG,CTGGCGAACG"
SI_NT_C2 = "SI-NT-C2,CTGTGCAATG,ATGGTGCTTT,AAAGCACCAT"
SI_NT_C3 = "SI-NT-C3,AAAGCTGAGC,CAGGAACGAG,CTCGTTCCTG"
SI_NT_C4 = "SI-NT-C4,GTCCAAGTCG,GTCATGGCAC,GTGCCATGAC"
SI_NT_C5 = "SI-NT-C5,GATTTCCATC,CTTATGGTCA,TGACCATAAG"
SI_NT_C6 = "SI-NT-C6,CTAAATGGAT,AATCACATAC,GTATGTGATT"
SI_NT_C7 = "SI-NT-C7,ATTTCAGTTC,GCAGCATTAA,TTAATGCTGC"
SI_NT_C8 = "SI-NT-C8,TTGCGACGTC,TTAATCCACA,TGTGGATTAA"
SI_NT_C9 = "SI-NT-C9,GTACTGTCCA,TTTGTTGGAA,TTCCAACAAA"
SI_NT_C10 = "SI-NT-C10,AAACGGTTTA,TCTTCGTTAC,GTAACGAAGA"
SI_NT_C11 = "SI-NT-C11,CGATAGTTCT,GCGATTTCCT,AGGAAATCGC"
SI_NT_C12 = "SI-NT-C12,TACTTTAGCT,GAGTTATTTG,CAAATAACTC"
SI_NT_D1 = "SI-NT-D1,CTGGGATTAA,AGTAAAGTTC,GAACTTTACT"
SI_NT_D2 = "SI-NT-D2,TACACTATTC,ATTGCAACGT,ACGTTGCAAT"
SI_NT_D3 = "SI-NT-D3,AGAGCTATTT,CTGGCACCCA,TGGGTGCCAG"
SI_NT_D4 = "SI-NT-D4,AGGTCGTTAT,AGGTTATCCA,TGGATAACCT"
SI_NT_D5 = "SI-NT-D5,GCTGGACAGG,TAATCTCTGT,ACAGAGATTA"
SI_NT_D6 = "SI-NT-D6,ACTTAGATGG,AATGTTGAGT,ACTCAACATT"
SI_NT_D7 = "SI-NT-D7,AGGCGCGAGT,TGTGTCTATA,TATAGACACA"
SI_NT_D8 = "SI-NT-D8,GAGGTCGTAC,CAACTGCGGG,CCCGCAGTTG"
SI_NT_D9 = "SI-NT-D9,CCCAATGAGC,AGTTTCTGAT,ATCAGAAACT"
SI_NT_D10 = "SI-NT-D10,ACATTCAGGG,GTCCTGAGAG,CTCTCAGGAC"
SI_NT_D11 = "SI-NT-D11,AGAAACGGTG,TCACCCAGCA,TGCTGGGTGA"
SI_NT_D12 = "SI-NT-D12,AGTTGCAAGT,ATACTTCATG,CATGAAGTAT"
SI_NT_E1 = "SI-NT-E1,GCCTAGAAAT,ACTACTCCGG,CCGGAGTAGT"
SI_NT_E2 = "SI-NT-E2,TACAAAGATG,CCGATGACGT,ACGTCATCGG"
SI_NT_E3 = "SI-NT-E3,GCAGGCTTAG,CGTCTATTGC,GCAATAGACG"
SI_NT_E4 = "SI-NT-E4,CAGCTCCAAT,TAGGAGGGTG,CACCCTCCTA"
SI_NT_E5 = "SI-NT-E5,TTTGGAGAAA,CAGCCCTTGA,TCAAGGGCTG"
SI_NT_E6 = "SI-NT-E6,TGTCGCTTTC,CCTAAAGGGT,ACCCTTTAGG"
SI_NT_E7 = "SI-NT-E7,GTGTTGCGAG,CACTTTGAGC,GCTCAAAGTG"
SI_NT_E8 = "SI-NT-E8,GTCTGTTCTG,TCTGATGCTT,AAGCATCAGA"
SI_NT_E9 = "SI-NT-E9,TCGCTCAATC,GCTTACGTGA,TCACGTAAGC"
SI_NT_E10 = "SI-NT-E10,CGTTACTAGC,AATGGCCATT,AATGGCCATT"
SI_NT_E11 = "SI-NT-E11,GTGCAGATTT,TAAAGGCGAT,ATCGCCTTTA"
SI_NT_E12 = "SI-NT-E12,GTTACCGAAA,CGTTTGAATC,GATTCAAACG"
SI_NT_F1 = "SI-NT-F1,CGGTATGGAA,TGCAACTGGT,ACCAGTTGCA"
SI_NT_F2 = "SI-NT-F2,TCGGTTTAGT,TAAAGTGTTC,GAACACTTTA"
SI_NT_F3 = "SI-NT-F3,CTTTGCTTTG,ACATTCATTC,GAATGAATGT"
SI_NT_F4 = "SI-NT-F4,ATGATCGCAC,GCGGTATGTA,TACATACCGC"
SI_NT_F5 = "SI-NT-F5,CGGCGTGTTA,TGAGACGCGG,CCGCGTCTCA"
SI_NT_F6 = "SI-NT-F6,TCATTTCCGC,ACAGCTGTTG,CAACAGCTGT"
SI_NT_F7 = "SI-NT-F7,TTGTGCCCAG,TTGCGAGTTG,CAACTCGCAA"
SI_NT_F8 = "SI-NT-F8,AGCCAACGTG,TCAAAGGAAC,GTTCCTTTGA"
SI_NT_F9 = "SI-NT-F9,GATCCATACT,ATCGAGAGAA,TTCTCTCGAT"
SI_NT_F10 = "SI-NT-F10,TTTCCATGAA,CGGTTCTAAC,GTTAGAACCG"
SI_NT_F11 = "SI-NT-F11,TCTTTATCGG,CCCAATAGCG,CGCTATTGGG"
SI_NT_F12 = "SI-NT-F12,GAACCCGATG,TCTATCCGGG,CCCGGATAGA"
SI_NT_G1 = "SI-NT-G1,GATGTCTGTG,CGTGCTACCG,CGGTAGCACG"
SI_NT_G2 = "SI-NT-G2,TGTTAGACTA,TCATGACGAC,GTCGTCATGA"
SI_NT_G3 = "SI-NT-G3,TAGAACGCTT,GTCGCAAACG,CGTTTGCGAC"
SI_NT_G4 = "SI-NT-G4,AATTTGACGT,AGAAGTGAGG,CCTCACTTCT"
SI_NT_G5 = "SI-NT-G5,GAGTGGCCAC,GATGCACAGT,ACTGTGCATC"
SI_NT_G6 = "SI-NT-G6,ATCAGTTACG,TACAATCTCT,AGAGATTGTA"
SI_NT_G7 = "SI-NT-G7,TGTAAGCTTT,CGGACTAGTC,GACTAGTCCG"
SI_NT_G8 = "SI-NT-G8,GCTTCGGTCT,CGCGGGTTAG,CTAACCCGCG"
SI_NT_G9 = "SI-NT-G9,AGTCTAAGAC,CTGAAGTGAA,TTCACTTCAG"
SI_NT_G10 = "SI-NT-G10,TGAAACATTC,CCTCCTGCCT,AGGCAGGAGG"
SI_NT_G11 = "SI-NT-G11,CCTCACGAAA,TGCCCTGTGC,GCACAGGGCA"
SI_NT_G12 = "SI-NT-G12,CTACGGGCTT,AGGCGTCCCT,AGGGACGCCT"
SI_NT_H1 = "SI-NT-H1,GCGGCGTAAA,CACGCGATCA,TGATCGCGTG"
SI_NT_H2 = "SI-NT-H2,TCTCCTTCGG,TGTCCGTCGC,GCGACGGACA"
SI_NT_H3 = "SI-NT-H3,CCTTACCCAT,TCCCGGCAAC,GTTGCCGGGA"
SI_NT_H4 = "SI-NT-H4,AAGGAACATC,TATCTGTGGG,CCCACAGATA"
SI_NT_H5 = "SI-NT-H5,GTGGGAACTT,GCACTTACAG,CTGTAAGTGC"
SI_NT_H6 = "SI-NT-H6,ACCGCACCAC,TCGGATTATA,TATAATCCGA"
SI_NT_H7 = "SI-NT-H7,ACCTTTATCT,CGAGTGCCAA,TTGGCACTCG"
SI_NT_H8 = "SI-NT-H8,AGTAGCCCGT,TTCGGGACCT,AGGTCCCGAA"
SI_NT_H9 = "SI-NT-H9,AGATAGCATA,CATTTCCGGA,TCCGGAAATG"
SI_NT_H10 = "SI-NT-H10,TGGCGTTAAA,TGTTAAGATG,CATCTTAACA"
SI_NT_H11 = "SI-NT-H11,TCAGGCGAAA,TCTCTGGAAG,CTTCCAGAGA"
SI_NT_H12 = "SI-NT-H12,AAGACATAGC,ATGTGGACGT,ACGTCCACAT"
SI_TT_A1 = "SI-TT-A1,GTAACATGCG,AGTGTTACCT,AGGTAACACT"
SI_TT_A2 = "SI-TT-A2,GTGGATCAAA,GCCAACCCTG,CAGGGTTGGC"
SI_TT_A3 = "SI-TT-A3,CACTACGAAA,TTAGACTGAT,ATCAGTCTAA"
SI_TT_A4 = "SI-TT-A4,CTCTAGCGAG,TATCTTCATC,GATGAAGATA"
SI_TT_A5 = "SI-TT-A5,GTAGCCCTGT,GAGCATCTAT,ATAGATGCTC"
SI_TT_A6 = "SI-TT-A6,TAACGCGTGA,CCCTAACTTC,GAAGTTAGGG"
SI_TT_A7 = "SI-TT-A7,TCCCAAGGGT,TACTACCTTT,AAAGGTAGTA"
SI_TT_A8 = "SI-TT-A8,CGAAGTATAC,GAACTTGGAG,CTCCAAGTTC"
SI_TT_A9 = "SI-TT-A9,AAGTGGAGAG,TTCCTGTTAC,GTAACAGGAA"
SI_TT_A10 = "SI-TT-A10,CGTGACATGC,ATGGTCTAAA,TTTAGACCAT"
SI_TT_A11 = "SI-TT-A11,CGGAACCCAA,GATTCGAGGA,TCCTCGAATC"
SI_TT_A12 = "SI-TT-A12,CACCGCACCA,GACTGTCAAT,ATTGACAGTC"
SI_TT_B1 = "SI-TT-B1,ACAGTAACTA,ACAGTTCGTT,AACGAACTGT"
SI_TT_B2 = "SI-TT-B2,TCTACCATTT,CGGGAGAGTC,GACTCTCCCG"
SI_TT_B3 = "SI-TT-B3,CACGGTGAAT,GTTCGTCACA,TGTGACGAAC"
SI_TT_B4 = "SI-TT-B4,GTAGACGAAA,CTAGTGTGGT,ACCACACTAG"
SI_TT_B5 = "SI-TT-B5,TCGGCTCTAC,CCGATGGTCT,AGACCATCGG"
SI_TT_B6 = "SI-TT-B6,AATGCCATGA,TACGTAATGC,GCATTACGTA"
SI_TT_B7 = "SI-TT-B7,GCCTTCGGTA,CCAACGATTT,AAATCGTTGG"
SI_TT_B8 = "SI-TT-B8,GCACTGAGAA,TATGCGTGAA,TTCACGCATA"
SI_TT_B9 = "SI-TT-B9,TATTGAGGCA,CAGGTAAGTG,CACTTACCTG"
SI_TT_B10 = "SI-TT-B10,GCCCGATGGA,AATCGTCTAG,CTAGACGATT"
SI_TT_B11 = "SI-TT-B11,TCTTACTTGC,TGACCTCTAG,CTAGAGGTCA"
SI_TT_B12 = "SI-TT-B12,CGTCAAGGGC,TAGGTCACTC,GAGTGACCTA"
SI_TT_C1 = "SI-TT-C1,TGCGCGGTTT,CAAGGATAAA,TTTATCCTTG"
SI_TT_C2 = "SI-TT-C2,CAATCCCGAC,CCGAGTAGTA,TACTACTCGG"
SI_TT_C3 = "SI-TT-C3,ATGGCTTGTG,GAATGTTGTG,CACAACATTC"
SI_TT_C4 = "SI-TT-C4,TTCTCGATGA,TGTCGGGCAC,GTGCCCGACA"
SI_TT_C5 = "SI-TT-C5,TCCGTTGGAT,ACGTTCTCGC,GCGAGAACGT"
SI_TT_C6 = "SI-TT-C6,ACGACTACCA,ACGACCCTAA,TTAGGGTCGT"
SI_TT_C7 = "SI-TT-C7,CGCGCACTTA,CCTGTATTCT,AGAATACAGG"
SI_TT_C8 = "SI-TT-C8,GCTACAAAGC,CACGTGCCCT,AGGGCACGTG"
SI_TT_C9 = "SI-TT-C9,TATCAGCCTA,GTTTCGTCCT,AGGACGAAAC"
SI_TT_C10 = "SI-TT-C10,AGAATGGTTT,GAGGGTGGGA,TCCCACCCTC"
SI_TT_C11 = "SI-TT-C11,ATGGGTGAAA,CTTGGGAATT,AATTCCCAAG"
SI_TT_C12 = "SI-TT-C12,TCGTCAAGAT,GCAACTCAGG,CCTGAGTTGC"
SI_TT_D1 = "SI-TT-D1,TGCAATGTTC,GCTTGTCGAA,TTCGACAAGC"
SI_TT_D2 = "SI-TT-D2,TTAATACGCG,CACCTCGGGT,ACCCGAGGTG"
SI_TT_D3 = "SI-TT-D3,CCTTCTAGAG,AATACAACGA,TCGTTGTATT"
SI_TT_D4 = "SI-TT-D4,GCAGTATAGG,TTCCGTGCAC,GTGCACGGAA"
SI_TT_D5 = "SI-TT-D5,TGGTTCGGGT,GTGGCAGGAG,CTCCTGCCAC"
SI_TT_D6 = "SI-TT-D6,CCCAGCTTCT,GACACCAAAC,GTTTGGTGTC"
SI_TT_D7 = "SI-TT-D7,CCTGTCAGGG,AGCCCGTAAC,GTTACGGGCT"
SI_TT_D8 = "SI-TT-D8,CGCTGAAATC,AGGTGTCTGC,GCAGACACCT"
SI_TT_D9 = "SI-TT-D9,TGGTCCCAAG,CCTCTGGCGT,ACGCCAGAGG"
SI_TT_D10 = "SI-TT-D10,ATGCGAATGG,ACAAGTGTCG,CGACACTTGT"
SI_TT_D11 = "SI-TT-D11,CGAATATTCG,CTGGAAGCAA,TTGCTTCCAG"
SI_TT_D12 = "SI-TT-D12,GAATTGGTTA,ACTCTAGTAG,CTACTAGAGT"
SI_TT_E1 = "SI-TT-E1,TTATTCGAGG,CTGTCCTGCT,AGCAGGACAG"
SI_TT_E2 = "SI-TT-E2,ATGGAGGGAG,ATAACCCATT,AATGGGTTAT"
SI_TT_E3 = "SI-TT-E3,ACCAGACAAC,AGGAACTAGG,CCTAGTTCCT"
SI_TT_E4 = "SI-TT-E4,AACCACGCAT,ATTCAGGTTA,TAACCTGAAT"
SI_TT_E5 = "SI-TT-E5,CGCGGTAGGT,CAGGATGTTG,CAACATCCTG"
SI_TT_E6 = "SI-TT-E6,TTGAGAGTCA,AACCTGGTAG,CTACCAGGTT"
SI_TT_E7 = "SI-TT-E7,GTCCTTCGGC,TCATGCACAG,CTGTGCATGA"
SI_TT_E8 = "SI-TT-E8,GAGCAAGGGC,ATTGACTTGG,CCAAGTCAAT"
SI_TT_E9 = "SI-TT-E9,TGTCCCAACG,TCGATGTCCA,TGGACATCGA"
SI_TT_E10 = "SI-TT-E10,CACAATCCCA,ATATCCACAA,TTGTGGATAT"
SI_TT_E11 = "SI-TT-E11,TCCGGGACAA,GTGAATGCCA,TGGCATTCAC"
SI_TT_E12 = "SI-TT-E12,CGTCCACCTG,CATTCATGAC,GTCATGAATG"
SI_TT_F1 = "SI-TT-F1,AAGATTGGAT,AGCGGGATTT,AAATCCCGCT"
SI_TT_F2 = "SI-TT-F2,AAGGGCCGCA,CTGATTCCTC,GAGGAATCAG"
SI_TT_F3 = "SI-TT-F3,GAGAGGATAT,TTGAAATGGG,CCCATTTCAA"
SI_TT_F4 = "SI-TT-F4,CCCACCACAA,ACCTCCGCTT,AAGCGGAGGT"
SI_TT_F5 = "SI-TT-F5,CGGCTGGATG,TGATAAGCAC,GTGCTTATCA"
SI_TT_F6 = "SI-TT-F6,TTGCCCGTGC,GCGTGAGATT,AATCTCACGC"
SI_TT_F7 = "SI-TT-F7,AATGTATCCA,AATGAGCTTA,TAAGCTCATT"
SI_TT_F8 = "SI-TT-F8,CTCCTTTAGA,GACATAGCTC,GAGCTATGTC"
SI_TT_F9 = "SI-TT-F9,GTCCCATCAA,CGAACGTGAC,GTCACGTTCG"
SI_TT_F10 = "SI-TT-F10,CCGGCAACTG,CGGTTTAACA,TGTTAAACCG"
SI_TT_F11 = "SI-TT-F11,TTCACACCTT,TAGTGTACAC,GTGTACACTA"
SI_TT_F12 = "SI-TT-F12,GAGACGCACG,CTATGAACAT,ATGTTCATAG"
SI_TT_G1 = "SI-TT-G1,TGTAGTCATT,CTTGATCGTA,TACGATCAAG"
SI_TT_G2 = "SI-TT-G2,CATGTGGGTT,GATTCCTTTA,TAAAGGAATC"
SI_TT_G3 = "SI-TT-G3,ATGACGTCGC,AGGTCAGGAT,ATCCTGACCT"
SI_TT_G4 = "SI-TT-G4,GCGCTTATGG,GCCTGGCTAG,CTAGCCAGGC"
SI_TT_G5 = "SI-TT-G5,ATAGGGCGAG,TGCATCGAGT,ACTCGATGCA"
SI_TT_G6 = "SI-TT-G6,GCGGGTAAGT,TAGCACTAAG,CTTAGTGCTA"
SI_TT_G7 = "SI-TT-G7,GTTTCACGAT,TTCGGCCAAA,TTTGGCCGAA"
SI_TT_G8 = "SI-TT-G8,TAAGCAACTG,CTATACTCAA,TTGAGTATAG"
SI_TT_G9 = "SI-TT-G9,CCGGAGGAAG,TGCGGATGTT,AACATCCGCA"
SI_TT_G10 = "SI-TT-G10,ACTTTACGTG,TGAACGCCCT,AGGGCGTTCA"
SI_TT_G11 = "SI-TT-G11,GATAACCTGC,CATTAGAAAC,GTTTCTAATG"
SI_TT_G12 = "SI-TT-G12,CTTGCATAAA,ATCAGGGCTT,AAGCCCTGAT"
SI_TT_H1 = "SI-TT-H1,ACAATGTGAA,CGTACCGTTA,TAACGGTACG"
SI_TT_H2 = "SI-TT-H2,TAGCATAGTG,CGGCTCTGTC,GACAGAGCCG"
SI_TT_H3 = "SI-TT-H3,CCCGTTCTCG,GACGGATTGG,CCAATCCGTC"
SI_TT_H4 = "SI-TT-H4,AGTTTCCTGG,TGCCACACAG,CTGTGTGGCA"
SI_TT_H5 = "SI-TT-H5,AGCAAGAAGC,TTGTGTTTCT,AGAAACACAA"
SI_TT_H6 = "SI-TT-H6,CCTATCCTCG,GAATACTAAC,GTTAGTATTC"
SI_TT_H7 = "SI-TT-H7,ACCTCGAGCT,TGTGTTCGAT,ATCGAACACA"
SI_TT_H8 = "SI-TT-H8,ATAAGGATAC,ATAGATAGGG,CCCTATCTAT"
SI_TT_H9 = "SI-TT-H9,AGAACTTAGA,CGAGTCCTTT,AAAGGACTCG"
SI_TT_H10 = "SI-TT-H10,TTATCTAGGG,AAAGGCTCTA,TAGAGCCTTT"
SI_TT_H11 = "SI-TT-H11,ACAATCGATC,TGACGGAATG,CATTCCGTCA"
SI_TT_H12 = "SI-TT-H12,TGATGATTCA,GTAGGAGTCG,CGACTCCTAC"

TENX_INDEX_CHOICES = (
    (SI_GA_A1, "SI-GA-A1"),
    (SI_GA_A2, "SI-GA-A2"),
    (SI_GA_A3, "SI-GA-A3"),
    (SI_GA_A4, "SI-GA-A4"),
    (SI_GA_A5, "SI-GA-A5"),
    (SI_GA_A6, "SI-GA-A6"),
    (SI_GA_A7, "SI-GA-A7"),
    (SI_GA_A8, "SI-GA-A8"),
    (SI_GA_A9, "SI-GA-A9"),
    (SI_GA_A10, "SI-GA-A10"),
    (SI_GA_A11, "SI-GA-A11"),
    (SI_GA_A12, "SI-GA-A12"),
    (SI_GA_B1, "SI-GA-B1"),
    (SI_GA_B2, "SI-GA-B2"),
    (SI_GA_B3, "SI-GA-B3"),
    (SI_GA_B4, "SI-GA-B4"),
    (SI_GA_B5, "SI-GA-B5"),
    (SI_GA_B6, "SI-GA-B6"),
    (SI_GA_B7, "SI-GA-B7"),
    (SI_GA_B8, "SI-GA-B8"),
    (SI_GA_B9, "SI-GA-B9"),
    (SI_GA_B10, "SI-GA-B10"),
    (SI_GA_B11, "SI-GA-B11"),
    (SI_GA_B12, "SI-GA-B12"),
    (SI_GA_C1, "SI-GA-C1"),
    (SI_GA_C2, "SI-GA-C2"),
    (SI_GA_C3, "SI-GA-C3"),
    (SI_GA_C4, "SI-GA-C4"),
    (SI_GA_C5, "SI-GA-C5"),
    (SI_GA_C6, "SI-GA-C6"),
    (SI_GA_C7, "SI-GA-C7"),
    (SI_GA_C8, "SI-GA-C8"),
    (SI_GA_C9, "SI-GA-C9"),
    (SI_GA_C10, "SI-GA-C10"),
    (SI_GA_C11, "SI-GA-C11"),
    (SI_GA_C12, "SI-GA-C12"),
    (SI_GA_D1, "SI-GA-D1"),
    (SI_GA_D2, "SI-GA-D2"),
    (SI_GA_D3, "SI-GA-D3"),
    (SI_GA_D4, "SI-GA-D4"),
    (SI_GA_D5, "SI-GA-D5"),
    (SI_GA_D6, "SI-GA-D6"),
    (SI_GA_D7, "SI-GA-D7"),
    (SI_GA_D8, "SI-GA-D8"),
    (SI_GA_D9, "SI-GA-D9"),
    (SI_GA_D10, "SI-GA-D10"),
    (SI_GA_D11, "SI-GA-D11"),
    (SI_GA_D12, "SI-GA-D12"),
    (SI_GA_E1, "SI-GA-E1"),
    (SI_GA_E2, "SI-GA-E2"),
    (SI_GA_E3, "SI-GA-E3"),
    (SI_GA_E4, "SI-GA-E4"),
    (SI_GA_E5, "SI-GA-E5"),
    (SI_GA_E6, "SI-GA-E6"),
    (SI_GA_E7, "SI-GA-E7"),
    (SI_GA_E8, "SI-GA-E8"),
    (SI_GA_E9, "SI-GA-E9"),
    (SI_GA_E10, "SI-GA-E10"),
    (SI_GA_E11, "SI-GA-E11"),
    (SI_GA_E12, "SI-GA-E12"),
    (SI_GA_F1, "SI-GA-F1"),
    (SI_GA_F2, "SI-GA-F2"),
    (SI_GA_F3, "SI-GA-F3"),
    (SI_GA_F4, "SI-GA-F4"),
    (SI_GA_F5, "SI-GA-F5"),
    (SI_GA_F6, "SI-GA-F6"),
    (SI_GA_F7, "SI-GA-F7"),
    (SI_GA_F8, "SI-GA-F8"),
    (SI_GA_F9, "SI-GA-F9"),
    (SI_GA_F10, "SI-GA-F10"),
    (SI_GA_F11, "SI-GA-F11"),
    (SI_GA_F12, "SI-GA-F12"),
    (SI_GA_G1, "SI-GA-G1"),
    (SI_GA_G2, "SI-GA-G2"),
    (SI_GA_G3, "SI-GA-G3"),
    (SI_GA_G4, "SI-GA-G4"),
    (SI_GA_G5, "SI-GA-G5"),
    (SI_GA_G6, "SI-GA-G6"),
    (SI_GA_G7, "SI-GA-G7"),
    (SI_GA_G8, "SI-GA-G8"),
    (SI_GA_G9, "SI-GA-G9"),
    (SI_GA_G10, "SI-GA-G10"),
    (SI_GA_G11, "SI-GA-G11"),
    (SI_GA_G12, "SI-GA-G12"),
    (SI_GA_H1, "SI-GA-H1"),
    (SI_GA_H2, "SI-GA-H2"),
    (SI_GA_H3, "SI-GA-H3"),
    (SI_GA_H4, "SI-GA-H4"),
    (SI_GA_H5, "SI-GA-H5"),
    (SI_GA_H6, "SI-GA-H6"),
    (SI_GA_H7, "SI-GA-H7"),
    (SI_GA_H8, "SI-GA-H8"),
    (SI_GA_H9, "SI-GA-H9"),
    (SI_GA_H10, "SI-GA-H10"),
    (SI_GA_H11, "SI-GA-H11"),
    (SI_GA_H12, "SI-GA-H12"),
    (SI_NA_A1, "SI-NA-A1"),
    (SI_NA_B1, "SI-NA-B1"),
    (SI_NA_C1, "SI-NA-C1"),
    (SI_NA_D1, "SI-NA-D1"),
    (SI_NA_E1, "SI-NA-E1"),
    (SI_NA_F1, "SI-NA-F1"),
    (SI_NA_G1, "SI-NA-G1"),
    (SI_NA_H1, "SI-NA-H1"),
    (SI_NA_A2, "SI-NA-A2"),
    (SI_NA_B2, "SI-NA-B2"),
    (SI_NA_C2, "SI-NA-C2"),
    (SI_NA_D2, "SI-NA-D2"),
    (SI_NA_E2, "SI-NA-E2"),
    (SI_NA_F2, "SI-NA-F2"),
    (SI_NA_G2, "SI-NA-G2"),
    (SI_NA_H2, "SI-NA-H2"),
    (SI_NA_A3, "SI-NA-A3"),
    (SI_NA_B3, "SI-NA-B3"),
    (SI_NA_C3, "SI-NA-C3"),
    (SI_NA_D3, "SI-NA-D3"),
    (SI_NA_E3, "SI-NA-E3"),
    (SI_NA_F3, "SI-NA-F3"),
    (SI_NA_G3, "SI-NA-G3"),
    (SI_NA_H3, "SI-NA-H3"),
    (SI_NA_A4, "SI-NA-A4"),
    (SI_NA_B4, "SI-NA-B4"),
    (SI_NA_C4, "SI-NA-C4"),
    (SI_NA_D4, "SI-NA-D4"),
    (SI_NA_E4, "SI-NA-E4"),
    (SI_NA_F4, "SI-NA-F4"),
    (SI_NA_G4, "SI-NA-G4"),
    (SI_NA_H4, "SI-NA-H4"),
    (SI_NA_A5, "SI-NA-A5"),
    (SI_NA_B5, "SI-NA-B5"),
    (SI_NA_C5, "SI-NA-C5"),
    (SI_NA_D5, "SI-NA-D5"),
    (SI_NA_E5, "SI-NA-E5"),
    (SI_NA_F5, "SI-NA-F5"),
    (SI_NA_G5, "SI-NA-G5"),
    (SI_NA_H5, "SI-NA-H5"),
    (SI_NA_A6, "SI-NA-A6"),
    (SI_NA_B6, "SI-NA-B6"),
    (SI_NA_C6, "SI-NA-C6"),
    (SI_NA_D6, "SI-NA-D6"),
    (SI_NA_E6, "SI-NA-E6"),
    (SI_NA_F6, "SI-NA-F6"),
    (SI_NA_G6, "SI-NA-G6"),
    (SI_NA_H6, "SI-NA-H6"),
    (SI_NA_A7, "SI-NA-A7"),
    (SI_NA_B7, "SI-NA-B7"),
    (SI_NA_C7, "SI-NA-C7"),
    (SI_NA_D7, "SI-NA-D7"),
    (SI_NA_E7, "SI-NA-E7"),
    (SI_NA_F7, "SI-NA-F7"),
    (SI_NA_G7, "SI-NA-G7"),
    (SI_NA_H7, "SI-NA-H7"),
    (SI_NA_A8, "SI-NA-A8"),
    (SI_NA_B8, "SI-NA-B8"),
    (SI_NA_C8, "SI-NA-C8"),
    (SI_NA_D8, "SI-NA-D8"),
    (SI_NA_E8, "SI-NA-E8"),
    (SI_NA_F8, "SI-NA-F8"),
    (SI_NA_G8, "SI-NA-G8"),
    (SI_NA_H8, "SI-NA-H8"),
    (SI_NA_A9, "SI-NA-A9"),
    (SI_NA_B9, "SI-NA-B9"),
    (SI_NA_C9, "SI-NA-C9"),
    (SI_NA_D9, "SI-NA-D9"),
    (SI_NA_E9, "SI-NA-E9"),
    (SI_NA_F9, "SI-NA-F9"),
    (SI_NA_G9, "SI-NA-G9"),
    (SI_NA_H9, "SI-NA-H9"),
    (SI_NA_A1, "SI-NA-A10"),
    (SI_NA_B1, "SI-NA-B10"),
    (SI_NA_C1, "SI-NA-C10"),
    (SI_NA_D1, "SI-NA-D10"),
    (SI_NA_E1, "SI-NA-E10"),
    (SI_NA_F1, "SI-NA-F10"),
    (SI_NA_G1, "SI-NA-G10"),
    (SI_NA_H1, "SI-NA-H10"),
    (SI_NA_A1, "SI-NA-A11"),
    (SI_NA_B1, "SI-NA-B11"),
    (SI_NA_C1, "SI-NA-C11"),
    (SI_NA_D1, "SI-NA-D11"),
    (SI_NA_E1, "SI-NA-E11"),
    (SI_NA_F1, "SI-NA-F11"),
    (SI_NA_G1, "SI-NA-G11"),
    (SI_NA_H1, "SI-NA-H11"),
    (SI_NA_A1, "SI-NA-A12"),
    (SI_NA_B1, "SI-NA-B12"),
    (SI_NA_C1, "SI-NA-C12"),
    (SI_NA_D1, "SI-NA-D12"),
    (SI_NA_E1, "SI-NA-E12"),
    (SI_NA_F1, "SI-NA-F12"),
    (SI_NA_G1, "SI-NA-G12"),
    (SI_NA_H1, "SI-NA-H12"),
    (SI_NN_A1, "SI-NN-A1"),
    (SI_NN_A2, "SI-NN-A2"),
    (SI_NN_A3, "SI-NN-A3"),
    (SI_NN_A4, "SI-NN-A4"),
    (SI_NN_A5, "SI-NN-A5"),
    (SI_NN_A6, "SI-NN-A6"),
    (SI_NN_A7, "SI-NN-A7"),
    (SI_NN_A8, "SI-NN-A8"),
    (SI_NN_A9, "SI-NN-A9"),
    (SI_NN_A10, "SI-NN-A10"),
    (SI_NN_A11, "SI-NN-A11"),
    (SI_NN_A12, "SI-NN-A12"),
    (SI_NN_B1, "SI-NN-B1"),
    (SI_NN_B2, "SI-NN-B2"),
    (SI_NN_B3, "SI-NN-B3"),
    (SI_NN_B4, "SI-NN-B4"),
    (SI_NN_B5, "SI-NN-B5"),
    (SI_NN_B6, "SI-NN-B6"),
    (SI_NN_B7, "SI-NN-B7"),
    (SI_NN_B8, "SI-NN-B8"),
    (SI_NN_B9, "SI-NN-B9"),
    (SI_NN_B10, "SI-NN-B10"),
    (SI_NN_B11, "SI-NN-B11"),
    (SI_NN_B12, "SI-NN-B12"),
    (SI_NN_C1, "SI-NN-C1"),
    (SI_NN_C2, "SI-NN-C2"),
    (SI_NN_C3, "SI-NN-C3"),
    (SI_NN_C4, "SI-NN-C4"),
    (SI_NN_C5, "SI-NN-C5"),
    (SI_NN_C6, "SI-NN-C6"),
    (SI_NN_C7, "SI-NN-C7"),
    (SI_NN_C8, "SI-NN-C8"),
    (SI_NN_C9, "SI-NN-C9"),
    (SI_NN_C10, "SI-NN-C10"),
    (SI_NN_C11, "SI-NN-C11"),
    (SI_NN_C12, "SI-NN-C12"),
    (SI_NN_D1, "SI-NN-D1"),
    (SI_NN_D2, "SI-NN-D2"),
    (SI_NN_D3, "SI-NN-D3"),
    (SI_NN_D4, "SI-NN-D4"),
    (SI_NN_D5, "SI-NN-D5"),
    (SI_NN_D6, "SI-NN-D6"),
    (SI_NN_D7, "SI-NN-D7"),
    (SI_NN_D8, "SI-NN-D8"),
    (SI_NN_D9, "SI-NN-D9"),
    (SI_NN_D10, "SI-NN-D10"),
    (SI_NN_D11, "SI-NN-D11"),
    (SI_NN_D12, "SI-NN-D12"),
    (SI_NN_E1, "SI-NN-E1"),
    (SI_NN_E2, "SI-NN-E2"),
    (SI_NN_E3, "SI-NN-E3"),
    (SI_NN_E4, "SI-NN-E4"),
    (SI_NN_E5, "SI-NN-E5"),
    (SI_NN_E6, "SI-NN-E6"),
    (SI_NN_E7, "SI-NN-E7"),
    (SI_NN_E8, "SI-NN-E8"),
    (SI_NN_E9, "SI-NN-E9"),
    (SI_NN_E10, "SI-NN-E10"),
    (SI_NN_E11, "SI-NN-E11"),
    (SI_NN_E12, "SI-NN-E12"),
    (SI_NN_F1, "SI-NN-F1"),
    (SI_NN_F2, "SI-NN-F2"),
    (SI_NN_F3, "SI-NN-F3"),
    (SI_NN_F4, "SI-NN-F4"),
    (SI_NN_F5, "SI-NN-F5"),
    (SI_NN_F6, "SI-NN-F6"),
    (SI_NN_F7, "SI-NN-F7"),
    (SI_NN_F8, "SI-NN-F8"),
    (SI_NN_F9, "SI-NN-F9"),
    (SI_NN_F10, "SI-NN-F10"),
    (SI_NN_F11, "SI-NN-F11"),
    (SI_NN_F12, "SI-NN-F12"),
    (SI_NN_G1, "SI-NN-G1"),
    (SI_NN_G2, "SI-NN-G2"),
    (SI_NN_G3, "SI-NN-G3"),
    (SI_NN_G4, "SI-NN-G4"),
    (SI_NN_G5, "SI-NN-G5"),
    (SI_NN_G6, "SI-NN-G6"),
    (SI_NN_G7, "SI-NN-G7"),
    (SI_NN_G8, "SI-NN-G8"),
    (SI_NN_G9, "SI-NN-G9"),
    (SI_NN_G10, "SI-NN-G10"),
    (SI_NN_G11, "SI-NN-G11"),
    (SI_NN_G12, "SI-NN-G12"),
    (SI_NN_H1, "SI-NN-H1"),
    (SI_NN_H2, "SI-NN-H2"),
    (SI_NN_H3, "SI-NN-H3"),
    (SI_NN_H4, "SI-NN-H4"),
    (SI_NN_H5, "SI-NN-H5"),
    (SI_NN_H6, "SI-NN-H6"),
    (SI_NN_H7, "SI-NN-H7"),
    (SI_NN_H8, "SI-NN-H8"),
    (SI_NN_H9, "SI-NN-H9"),
    (SI_NN_H10, "SI-NN-H10"),
    (SI_NN_H11, "SI-NN-H11"),
    (SI_NN_H12, "SI-NN-H12"),
    (SI_NT_A1, "SI-NT-A1"),
    (SI_NT_A2, "SI-NT-A2"),
    (SI_NT_A3, "SI-NT-A3"),
    (SI_NT_A4, "SI-NT-A4"),
    (SI_NT_A5, "SI-NT-A5"),
    (SI_NT_A6, "SI-NT-A6"),
    (SI_NT_A7, "SI-NT-A7"),
    (SI_NT_A8, "SI-NT-A8"),
    (SI_NT_A9, "SI-NT-A9"),
    (SI_NT_A10, "SI-NT-A10"),
    (SI_NT_A11, "SI-NT-A11"),
    (SI_NT_A12, "SI-NT-A12"),
    (SI_NT_B1, "SI-NT-B1"),
    (SI_NT_B2, "SI-NT-B2"),
    (SI_NT_B3, "SI-NT-B3"),
    (SI_NT_B4, "SI-NT-B4"),
    (SI_NT_B5, "SI-NT-B5"),
    (SI_NT_B6, "SI-NT-B6"),
    (SI_NT_B7, "SI-NT-B7"),
    (SI_NT_B8, "SI-NT-B8"),
    (SI_NT_B9, "SI-NT-B9"),
    (SI_NT_B10, "SI-NT-B10"),
    (SI_NT_B11, "SI-NT-B11"),
    (SI_NT_B12, "SI-NT-B12"),
    (SI_NT_C1, "SI-NT-C1"),
    (SI_NT_C2, "SI-NT-C2"),
    (SI_NT_C3, "SI-NT-C3"),
    (SI_NT_C4, "SI-NT-C4"),
    (SI_NT_C5, "SI-NT-C5"),
    (SI_NT_C6, "SI-NT-C6"),
    (SI_NT_C7, "SI-NT-C7"),
    (SI_NT_C8, "SI-NT-C8"),
    (SI_NT_C9, "SI-NT-C9"),
    (SI_NT_C10, "SI-NT-C10"),
    (SI_NT_C11, "SI-NT-C11"),
    (SI_NT_C12, "SI-NT-C12"),
    (SI_NT_D1, "SI-NT-D1"),
    (SI_NT_D2, "SI-NT-D2"),
    (SI_NT_D3, "SI-NT-D3"),
    (SI_NT_D4, "SI-NT-D4"),
    (SI_NT_D5, "SI-NT-D5"),
    (SI_NT_D6, "SI-NT-D6"),
    (SI_NT_D7, "SI-NT-D7"),
    (SI_NT_D8, "SI-NT-D8"),
    (SI_NT_D9, "SI-NT-D9"),
    (SI_NT_D10, "SI-NT-D10"),
    (SI_NT_D11, "SI-NT-D11"),
    (SI_NT_D12, "SI-NT-D12"),
    (SI_NT_E1, "SI-NT-E1"),
    (SI_NT_E2, "SI-NT-E2"),
    (SI_NT_E3, "SI-NT-E3"),
    (SI_NT_E4, "SI-NT-E4"),
    (SI_NT_E5, "SI-NT-E5"),
    (SI_NT_E6, "SI-NT-E6"),
    (SI_NT_E7, "SI-NT-E7"),
    (SI_NT_E8, "SI-NT-E8"),
    (SI_NT_E9, "SI-NT-E9"),
    (SI_NT_E10, "SI-NT-E10"),
    (SI_NT_E11, "SI-NT-E11"),
    (SI_NT_E12, "SI-NT-E12"),
    (SI_NT_F1, "SI-NT-F1"),
    (SI_NT_F2, "SI-NT-F2"),
    (SI_NT_F3, "SI-NT-F3"),
    (SI_NT_F4, "SI-NT-F4"),
    (SI_NT_F5, "SI-NT-F5"),
    (SI_NT_F6, "SI-NT-F6"),
    (SI_NT_F7, "SI-NT-F7"),
    (SI_NT_F8, "SI-NT-F8"),
    (SI_NT_F9, "SI-NT-F9"),
    (SI_NT_F10, "SI-NT-F10"),
    (SI_NT_F11, "SI-NT-F11"),
    (SI_NT_F12, "SI-NT-F12"),
    (SI_NT_G1, "SI-NT-G1"),
    (SI_NT_G2, "SI-NT-G2"),
    (SI_NT_G3, "SI-NT-G3"),
    (SI_NT_G4, "SI-NT-G4"),
    (SI_NT_G5, "SI-NT-G5"),
    (SI_NT_G6, "SI-NT-G6"),
    (SI_NT_G7, "SI-NT-G7"),
    (SI_NT_G8, "SI-NT-G8"),
    (SI_NT_G9, "SI-NT-G9"),
    (SI_NT_G10, "SI-NT-G10"),
    (SI_NT_G11, "SI-NT-G11"),
    (SI_NT_G12, "SI-NT-G12"),
    (SI_NT_H1, "SI-NT-H1"),
    (SI_NT_H2, "SI-NT-H2"),
    (SI_NT_H3, "SI-NT-H3"),
    (SI_NT_H4, "SI-NT-H4"),
    (SI_NT_H5, "SI-NT-H5"),
    (SI_NT_H6, "SI-NT-H6"),
    (SI_NT_H7, "SI-NT-H7"),
    (SI_NT_H8, "SI-NT-H8"),
    (SI_NT_H9, "SI-NT-H9"),
    (SI_NT_H10, "SI-NT-H10"),
    (SI_NT_H11, "SI-NT-H11"),
    (SI_NT_H12, "SI-NT-H12"),
    (SI_TT_A1, "SI-TT-A1"),
    (SI_TT_A2, "SI-TT-A2"),
    (SI_TT_A3, "SI-TT-A3"),
    (SI_TT_A4, "SI-TT-A4"),
    (SI_TT_A5, "SI-TT-A5"),
    (SI_TT_A6, "SI-TT-A6"),
    (SI_TT_A7, "SI-TT-A7"),
    (SI_TT_A8, "SI-TT-A8"),
    (SI_TT_A9, "SI-TT-A9"),
    (SI_TT_A10, "SI-TT-A10"),
    (SI_TT_A11, "SI-TT-A11"),
    (SI_TT_A12, "SI-TT-A12"),
    (SI_TT_B1, "SI-TT-B1"),
    (SI_TT_B2, "SI-TT-B2"),
    (SI_TT_B3, "SI-TT-B3"),
    (SI_TT_B4, "SI-TT-B4"),
    (SI_TT_B5, "SI-TT-B5"),
    (SI_TT_B6, "SI-TT-B6"),
    (SI_TT_B7, "SI-TT-B7"),
    (SI_TT_B8, "SI-TT-B8"),
    (SI_TT_B9, "SI-TT-B9"),
    (SI_TT_B10, "SI-TT-B10"),
    (SI_TT_B11, "SI-TT-B11"),
    (SI_TT_B12, "SI-TT-B12"),
    (SI_TT_C1, "SI-TT-C1"),
    (SI_TT_C2, "SI-TT-C2"),
    (SI_TT_C3, "SI-TT-C3"),
    (SI_TT_C4, "SI-TT-C4"),
    (SI_TT_C5, "SI-TT-C5"),
    (SI_TT_C6, "SI-TT-C6"),
    (SI_TT_C7, "SI-TT-C7"),
    (SI_TT_C8, "SI-TT-C8"),
    (SI_TT_C9, "SI-TT-C9"),
    (SI_TT_C10, "SI-TT-C10"),
    (SI_TT_C11, "SI-TT-C11"),
    (SI_TT_C12, "SI-TT-C12"),
    (SI_TT_D1, "SI-TT-D1"),
    (SI_TT_D2, "SI-TT-D2"),
    (SI_TT_D3, "SI-TT-D3"),
    (SI_TT_D4, "SI-TT-D4"),
    (SI_TT_D5, "SI-TT-D5"),
    (SI_TT_D6, "SI-TT-D6"),
    (SI_TT_D7, "SI-TT-D7"),
    (SI_TT_D8, "SI-TT-D8"),
    (SI_TT_D9, "SI-TT-D9"),
    (SI_TT_D10, "SI-TT-D10"),
    (SI_TT_D11, "SI-TT-D11"),
    (SI_TT_D12, "SI-TT-D12"),
    (SI_TT_E1, "SI-TT-E1"),
    (SI_TT_E2, "SI-TT-E2"),
    (SI_TT_E3, "SI-TT-E3"),
    (SI_TT_E4, "SI-TT-E4"),
    (SI_TT_E5, "SI-TT-E5"),
    (SI_TT_E6, "SI-TT-E6"),
    (SI_TT_E7, "SI-TT-E7"),
    (SI_TT_E8, "SI-TT-E8"),
    (SI_TT_E9, "SI-TT-E9"),
    (SI_TT_E10, "SI-TT-E10"),
    (SI_TT_E11, "SI-TT-E11"),
    (SI_TT_E12, "SI-TT-E12"),
    (SI_TT_F1, "SI-TT-F1"),
    (SI_TT_F2, "SI-TT-F2"),
    (SI_TT_F3, "SI-TT-F3"),
    (SI_TT_F4, "SI-TT-F4"),
    (SI_TT_F5, "SI-TT-F5"),
    (SI_TT_F6, "SI-TT-F6"),
    (SI_TT_F7, "SI-TT-F7"),
    (SI_TT_F8, "SI-TT-F8"),
    (SI_TT_F9, "SI-TT-F9"),
    (SI_TT_F10, "SI-TT-F10"),
    (SI_TT_F11, "SI-TT-F11"),
    (SI_TT_F12, "SI-TT-F12"),
    (SI_TT_G1, "SI-TT-G1"),
    (SI_TT_G2, "SI-TT-G2"),
    (SI_TT_G3, "SI-TT-G3"),
    (SI_TT_G4, "SI-TT-G4"),
    (SI_TT_G5, "SI-TT-G5"),
    (SI_TT_G6, "SI-TT-G6"),
    (SI_TT_G7, "SI-TT-G7"),
    (SI_TT_G8, "SI-TT-G8"),
    (SI_TT_G9, "SI-TT-G9"),
    (SI_TT_G10, "SI-TT-G10"),
    (SI_TT_G11, "SI-TT-G11"),
    (SI_TT_G12, "SI-TT-G12"),
    (SI_TT_H1, "SI-TT-H1"),
    (SI_TT_H2, "SI-TT-H2"),
    (SI_TT_H3, "SI-TT-H3"),
    (SI_TT_H4, "SI-TT-H4"),
    (SI_TT_H5, "SI-TT-H5"),
    (SI_TT_H6, "SI-TT-H6"),
    (SI_TT_H7, "SI-TT-H7"),
    (SI_TT_H8, "SI-TT-H8"),
    (SI_TT_H9, "SI-TT-H9"),
    (SI_TT_H10, "SI-TT-H10"),
    (SI_TT_H11, "SI-TT-H11"),
    (SI_TT_H12, "SI-TT-H12"),
)

chromium_index_mapping = {
    'SI-GA-A1': 'GGTTTACT; CTAAACGG; TCGGCGTC; AACCGTAA',
    'SI-GA-A2': 'TTTCATGA; ACGTCCCT; CGCATGTG; GAAGGAAC',
    'SI-GA-A3': 'CAGTACTG; AGTAGTCT; GCAGTAGA; TTCCCGAC',
    'SI-GA-A4': 'TATGATTC; CCCACAGT; ATGCTGAA; GGATGCCG',
    'SI-GA-A5': 'CTAGGTGA; TCGTTCAG; AGCCAATT; GATACGCC',
    'SI-GA-A6': 'CGCTATGT; GCTGTCCA; TTGAGATC; AAACCGAG',
    'SI-GA-A7': 'ACAGAGGT; TATAGTTG; CGGTCCCA; GTCCTAAC',
    'SI-GA-A8': 'GCATCTCC; TGTAAGGT; CTGCGATG; AACGTCAA',
    'SI-GA-A9': 'TCTTAAAG; CGAGGCTC; GTCCTTCT; AAGACGGA',
    'SI-GA-A10': 'GAAACCCT; TTTCTGTC; CCGTGTGA; AGCGAAAG',
    'SI-GA-A11': 'GTCCGGTC; AAGATCAT; CCTGAAGG; TGATCTCA',
    'SI-GA-A12': 'AGTGGAAC; GTCTCCTT; TCACATCA; CAGATGGG',
    'SI-GA-B1': 'GTAATCTT; TCCGGAAG; AGTTCGGC; CAGCATCA',
    'SI-GA-B2': 'TACTCTTC; CCTGTGCG; GGACACGT; ATGAGAAA',
    'SI-GA-B3': 'GTGTATTA; TGTGCGGG; ACCATAAC; CAACGCCT',
    'SI-GA-B4': 'ACTTCATA; GAGATGAC; TGCCGTGG; CTAGACCT',
    'SI-GA-B5': 'AATAATGG; CCAGGGCA; TGCCTCAT; GTGTCATC',
    'SI-GA-B6': 'CGTTAATC; GCCACGCT; TTACTCAG; AAGGGTGA',
    'SI-GA-B7': 'AAACCTCA; GCCTTGGT; CTGGACTC; TGTAGAAG',
    'SI-GA-B8': 'AAAGTGCT; GCTACCTG; TGCTGTAA; CTGCAAGC',
    'SI-GA-B9': 'CTGTAACT; TCTAGCGA; AGAGTGTG; GACCCTAC',
    'SI-GA-B10': 'ACCGTATG; GATTAGAT; CTGACTGA; TGACGCCC',
    'SI-GA-B11': 'GTTCCTCA; AGGTACGC; TAAGTATG; CCCAGGAT',
    'SI-GA-B12': 'TACCACCA; CTAAGTTT; GGGTCAAG; ACTGTGGC',
    'SI-GA-C1': 'CCACTTAT; AACTGGCG; TTGGCATA; GGTAACGC',
    'SI-GA-C2': 'CCTAGACC; ATCTCTGT; TAGCTCTA; GGAGAGAG',
    'SI-GA-C3': 'TCAGCCGT; CAGAGGCC; GGTCAATA; ATCTTTAG',
    'SI-GA-C4': 'ACAATTCA; TGCGCAGC; CATCACTT; GTGTGGAG',
    'SI-GA-C5': 'CGACTTGA; TACAGACT; ATTGCGTG; GCGTACAC',
    'SI-GA-C6': 'ATTACTTC; TGCGAACT; GCATTCGG; CAGCGGAA',
    'SI-GA-C7': 'GTCTCTCG; AATCTCTC; CGGAGGGA; TCAGAAAT',
    'SI-GA-C8': 'GTTGAGAA; AGATCTGG; TCGATACT; CACCGCTC',
    'SI-GA-C9': 'GCGCAGAA; ATCTTACC; TATGGTGT; CGAACCTG',
    'SI-GA-C10': 'TCTCAGTG; GAGACTAT; CGCTTAGC; ATAGGCCA',
    'SI-GA-C11': 'GAGGATCT; AGACCATA; TCCTGCGC; CTTATGAG',
    'SI-GA-C12': 'TCTCGTTT; GGCTAGCG; ATGACCGC; CAAGTAAA',
    'SI-GA-D1': 'CACTCGGA; GCTGAATT; TGAAGTAC; ATGCTCCG',
    'SI-GA-D2': 'TAACAAGG; GGTTCCTC; ATCATGCA; CCGGGTAT',
    'SI-GA-D3': 'ACATTACT; TTTGGGTA; CAGCCCAC; GGCAATGG',
    'SI-GA-D4': 'CCCTAACA; ATTCCGAT; TGGATTGC; GAAGGCTG',
    'SI-GA-D5': 'CTCGTCAC; GATCAGCA; ACAACAGG; TGGTGTTT',
    'SI-GA-D6': 'CATGCGAT; TGATATTC; GTGATCGA; ACCCGACG',
    'SI-GA-D7': 'ATTTGCTA; TAGACACC; CCACAGGG; GGCGTTAT',
    'SI-GA-D8': 'GCAACAAA; TAGTTGTC; CGCCATCG; ATTGGCGT',
    'SI-GA-D9': 'AGGAGATG; GATGTGGT; CTACATCC; TCCTCCAA',
    'SI-GA-D10': 'CAATACCC; TGTCTATG; ACCACGAA; GTGGGTGT',
    'SI-GA-D11': 'CTTTGCGG; TGCACAAA; AAGCAGTC; GCAGTTCT',
    'SI-GA-D12': 'GCACAATG; CTTGGTAC; TGCACCGT; AAGTTGCA',
    'SI-GA-E1': 'TGGTAAAC; GAAAGGGT; ACTGCTCG; CTCCTCTA',
    'SI-GA-E2': 'GTGGTACC; TACTATAG; ACAAGGTA; CGTCCCGT',
    'SI-GA-E3': 'AGGTATTG; CTCCTAGT; TCAAGGCC; GATGCCAA',
    'SI-GA-E4': 'TTCGCCCT; GGATGGGC; AATCAATG; CCGATTAA',
    'SI-GA-E5': 'CATTAGCG; TTCGCTGA; ACAAGAAT; GGGCTCTC',
    'SI-GA-E6': 'CTGCGGCT; GACTCAAA; AGAAACTC; TCTGTTGG',
    'SI-GA-E7': 'CACGCCTT; GTATATAG; TCTCGGGC; AGGATACA',
    'SI-GA-E8': 'ATAGTTAC; TGCTGAGT; CCTACGTA; GAGCACCG',
    'SI-GA-E9': 'TTGTTTCC; GGAGGAGG; CCTAACAA; AACCCGTT',
    'SI-GA-E10': 'AAATGTGC; GGGCAAAT; TCTATCCG; CTCGCGTA',
    'SI-GA-E11': 'AAGCGCTG; CGTTTGAT; GTAGCACA; TCCAATGC',
    'SI-GA-E12': 'ACCGGCTC; GAGTTAGT; CGTCCTAG; TTAAAGCA',
    'SI-GA-F1': 'GTTGCAGC; TGGAATTA; CAATGGAG; ACCCTCCT',
    'SI-GA-F2': 'TTTACATG; CGCGATAC; ACGCGGGT; GAATTCCA',
    'SI-GA-F3': 'TTCAGGTG; ACGGACAT; GATCTTGA; CGATCACC',
    'SI-GA-F4': 'CCCAATAG; GTGTCGCT; AGAGTCGC; TATCGATA',
    'SI-GA-F5': 'GACTACGT; CTAGCGAG; TCTATATC; AGGCGTCA',
    'SI-GA-F6': 'CGGAGCAC; GACCTATT; ACTTAGGA; TTAGCTCG',
    'SI-GA-F7': 'CGTGCAGA; AACAAGAT; TCGCTTCG; GTATGCTC',
    'SI-GA-F8': 'CATGAACA; TCACTCGC; AGCTGGAT; GTGACTTG',
    'SI-GA-F9': 'CAAGCTCC; GTTCACTG; TCGTGAAA; AGCATGGT',
    'SI-GA-F10': 'GCTTGGCT; AAACAAAC; CGGGCTTA; TTCATCGG',
    'SI-GA-F11': 'GCGAGAGT; TACGTTCA; AGTCCCAC; CTATAGTG',
    'SI-GA-F12': 'TGATGCAT; GCTACTGA; CACCTGCC; ATGGAATG',
    'SI-GA-G1': 'ATGAATCT; GATCTCAG; CCAGGAGC; TGCTCGTA',
    'SI-GA-G2': 'TGATTCTA; ACTAGGAG; CAGCCACT; GTCGATGC',
    'SI-GA-G3': 'CCTCATTC; AGCATCCG; GTGGCAAT; TAATGGGA',
    'SI-GA-G4': 'GCGATGTG; AGATACAA; TTTCCACT; CACGGTGC',
    'SI-GA-G5': 'GAGCAAGA; TCTGTGAT; CGCAGTTC; ATATCCCG',
    'SI-GA-G6': 'CTGACGCG; GGTCGTAC; TCCTTCTT; AAAGAAGA',
    'SI-GA-G7': 'GGTATGCA; CTCGAAAT; ACACCTTC; TAGTGCGG',
    'SI-GA-G8': 'TATGAGCT; CCGATAGC; ATACCCAA; GGCTGTTG',
    'SI-GA-G9': 'TAGGACGT; ATCCCACA; GGAATGTC; CCTTGTAG',
    'SI-GA-G10': 'TCGCCAGC; AATGTTAG; CGATAGCT; GTCAGCTA',
    'SI-GA-G11': 'TTATCGTT; AGCAGAGC; CATCTCCA; GCGGATAG',
    'SI-GA-G12': 'ATTCTAAG; CCCGATTA; TGGAGGCT; GAATCCGC',
    'SI-GA-H1': 'GTATGTCA; TGTCAGAC; CACGTCGG; ACGACATT',
    'SI-GA-H2': 'TAATGACC; ATGCCTTA; GCCGAGAT; CGTATCGG',
    'SI-GA-H3': 'CCAAGATG; AGGCCCGA; TACGTGAC; GTTTATCT',
    'SI-GA-H4': 'GCCATTCC; CAAGAATT; TTGCCGGA; AGTTGCAG',
    'SI-GA-H5': 'CCACTACA; GATTCTGG; TGCGGCTT; ATGAAGAC',
    'SI-GA-H6': 'TAGGATAA; CCTTTGTC; GTACGCGG; AGCACACT',
    'SI-GA-H7': 'AGCTATCA; CATATAAC; TCAGGGTG; GTGCCCGT',
    'SI-GA-H8': 'TTGTTGAT; GCTCAACC; CAAAGTGG; AGCGCCTA',
    'SI-GA-H9': 'ACACTGTT; CAGGATGG; GGCTGAAC; TTTACCCA',
    'SI-GA-H10': 'GTAATTGC; AGTCGCTT; CACGAGAA; TCGTCACG',
    'SI-GA-H11': 'GGCGAGTA; ACTTCTAT; CAAATACG; TTGCGCGC',
    'SI-GA-H12': 'GACAGCAT; TTTGTACA; AGGCCGTG; CCATATGC',
    'SI-NA-B1': 'AGGCTACC; CTAGCTGT; GCCAACAA; TATTGGTG',
    'SI-NA-C1': 'AGACTTTC; CCGAGGCA; GATGCAGT; TTCTACAG',
    'SI-NA-D1': 'AGCTGCGT; CAACCATC; GTGGAGCA; TCTATTAG',
    'SI-NA-E1': 'ACGAAAGC; CGCCCGTA; GTTTGCCT; TAAGTTAG',
    'SI-NA-F1': 'ATCGCTCC; CCGTACAG; GATAGGTA; TGACTAGT',
    'SI-NA-G1': 'ATGCGATT; CATATGCG; GGATACGA; TCCGCTAC',
    'SI-NA-H1': 'AAACTCAT; CGGGAGTA; GTCACAGG; TCTTGTCC',
    'SI-NA-A2': 'AGCCCTTT; CAAGTCCA; GTGAGAAG; TCTTAGGC',
    'SI-NA-B2': 'AAGTTGAT; CCCACCCA; GGTCGAGC; TTAGATTG',
    'SI-NA-C2': 'AATCACTA; CCGAGAAC; GTAGTGCG; TGCTCTGT',
    'SI-NA-D2': 'ACATTCCG; CTGCGGTA; GACACAAT; TGTGATGC',
    'SI-NA-E2': 'AGGCTGGT; CACAACTA; GTTGGTCC; TCATCAAG',
    'SI-NA-F2': 'ATGGTTAG; CATTGATA; GCAAACGC; TGCCCGCT',
    'SI-NA-G2': 'ATAACCTA; CGGTGAGC; GATCTTAT; TCCGAGCG',
    'SI-NA-H2': 'AACGGTCA; CCGAACTC; GGTCCAAG; TTATTGGT',
    'SI-NA-A3': 'AAAGCATA; CTGCAGCC; GCCTTTAT; TGTAGCGG',
    'SI-NA-B3': 'ATTGGACG; CAGCTTAC; GGCAAGGA; TCATCCTT',
    'SI-NA-C3': 'ACGTTACA; CGTAGGTT; GACGACGG; TTACCTAC',
    'SI-NA-D3': 'ACTTCACT; CGAAGTTG; GAGCACGC; TTCGTGAA',
    'SI-NA-E3': 'AACAAGTC; CGGCTCCA; GTATGTAT; TCTGCAGG',
    'SI-NA-F3': 'AGTCTGTA; CAGAATAG; GCCTCCGT; TTAGGACC',
    'SI-NA-G3': 'ATGTCCAG; CGACGTCA; GCTATAGC; TACGAGTT',
    'SI-NA-H3': 'ACACCTAA; CGTTTGGG; GACAAACC; TTGGGCTT',
    'SI-NA-A4': 'AGAACGCC; CATGGCAG; GTCTTTGA; TCGCAATT',
    'SI-NA-B4': 'AGGGACTG; CCTCTAAC; GACAGGCT; TTATCTGA',
    'SI-NA-C4': 'ACATTGGC; CTTAGTCA; GAGCCCAT; TGCGAATG',
    'SI-NA-D4': 'AAATCGTC; CTTCGAAT; GCGATCGG; TGCGATCA',
    'SI-NA-E4': 'AGCTGACG; CCGGTGTC; GTAAACAT; TATCCTGA',
    'SI-NA-F4': 'AACGACAC; CGTCCTCT; GCATGATA; TTGATGGG',
    'SI-NA-G4': 'AGCTTCTC; CCTGCGGT; GTACAACG; TAGAGTAA',
    'SI-NA-H4': 'ACTGGAGC; CGGTCGTG; GAAATCAA; TTCCATCT',
    'SI-NA-A5': 'ATTGGGAA; CAGTCTGG; GGCATACT; TCACACTC',
    'SI-NA-B5': 'ATCGTACT; CATCAGTG; GGGACTAC; TCATGCGA',
    'SI-NA-C5': 'ATGCATTC; CACTGACT; GGTACGGG; TCAGTCAA',
    'SI-NA-D5': 'AGACGGAT; CCTTTAGA; GTCGACTC; TAGACTCG',
    'SI-NA-E5': 'ATCCAAGG; CCGTTGAA; GGAAGCTC; TATGCTCT',
    'SI-NA-F5': 'AACACAGC; CGGTTTAG; GTACGGCT; TCTGACTA',
    'SI-NA-G5': 'ATGAAGTA; CGCCGAAC; GAAGCTCG; TCTTTCGT',
    'SI-NA-H5': 'ATAGTATG; CCGCGTCT; GGCTCCAC; TATAAGGA',
    'SI-NA-A6': 'ACGGGACT; CTTTCGAC; GAACATGA; TGCATCTG',
    'SI-NA-B6': 'AACGCGAA; CTATTTGG; GCGCACCT; TGTAGATC',
    'SI-NA-C6': 'ACTCAGAC; CGCTCAGG; GAGGTTTA; TTAAGCCT',
    'SI-NA-D6': 'ATGCCAAA; CCTTATCG; GAAGTCTT; TGCAGGGC',
    'SI-NA-E6': 'ATTGAAAC; CAGCCCGA; GCCATTTG; TGATGGCT',
    'SI-NA-F6': 'ATGCCGGC; CCTAATTA; GACTTCCT; TGAGGAAG',
    'SI-NA-G6': 'AGCACTGG; CATTACAC; GTGCGACA; TCAGTGTT',
    'SI-NA-H6': 'AAGCATAA; CCCATCGC; GGTTGATG; TTAGCGCT',
    'SI-NA-A7': 'AGGTCATA; CTCATCAT; GCTGAGGG; TAACGTCC',
    'SI-NA-B7': 'AGGGATGA; CTTCTGTT; GAATGCAC; TCCACACG',
    'SI-NA-C7': 'ACACCGGG; CATAATCC; GGCGGAAT; TTGTTCTA',
    'SI-NA-D7': 'AACTTAGA; CCGGATCC; GGTCGCAT; TTAACGTG',
    'SI-NA-E7': 'AAGACGTG; CCATGTGT; GTTCACAA; TGCGTACC',
    'SI-NA-F7': 'ACCCGAGA; CAAACTTT; GGTTAGAC; TTGGTCCG',
    'SI-NA-G7': 'ATTACCGG; CAGTAATT; GCCGGTAA; TGACTGCC',
    'SI-NA-H7': 'AACGGGTG; CTAATTCT; GCTTCAAC; TGGCACGA',
    'SI-NA-A8': 'ATGATACG; CCACAGAA; GACTGTTC; TGTGCCGT',
    'SI-NA-B8': 'ACGTTCAC; CAAGGTCT; GTTAAGTG; TGCCCAGA',
    'SI-NA-C8': 'AGCTCGAG; CAGGAAGA; GCACGTTT; TTTATCCC',
    'SI-NA-D8': 'AATCTTTG; CTCAAGAC; GGATGAGT; TCGGCCCA',
    'SI-NA-E8': 'AGCCTATG; CTAACGCA; GCTTACAT; TAGGGTGC',
    'SI-NA-F8': 'AGTTGGGA; CCAGAAAG; GTGCCCTC; TACATTCT',
    'SI-NA-G8': 'AAGTACTC; CTTGGAGA; GGAACTCT; TCCCTGAG',
    'SI-NA-H8': 'AAGAGCGG; CTTGTTAT; GGCCCATC; TCATAGCA',
    'SI-NA-A9': 'ACAACTTG; CTCCAACA; GAGTGCGT; TGTGTGAC',
    'SI-NA-B9': 'AAGCGTGT; CTTGACCG; GCCACGTA; TGATTAAC',
    'SI-NA-C9': 'AGATCGGT; CATCGTCG; GTCATATA; TCGGACAC',
    'SI-NA-D9': 'ACCTACTG; CAAGGGAC; GGGACACA; TTTCTTGT',
    'SI-NA-E9': 'AGTAAGCA; CCGGTAAT; GTATCTTC; TACCGCGG',
    'SI-NA-F9': 'AGTTAGTT; CACGCACG; GTACTTAA; TCGAGCGC',
    'SI-NA-G9': 'AGTCTCAG; CAATGGCA; GCCGAAGT; TTGACTTC',
    'SI-NA-H9': 'ACCTGCCA; CTTCATAC; GGAATATG; TAGGCGGT',
    'SI-NA-A10': 'ACAGCAAC; CGCAATTT; GAGTTGCG; TTTCGCGA',
    'SI-NA-B10': 'ACCATTAA; CTGGACGT; GAACGGTC; TGTTCACG',
    'SI-NA-C10': 'ATCTGATC; CGTGCTAA; GAGAAGGG; TCACTCCT',
    'SI-NA-D10': 'AGATAACA; CTTATTTG; GCGGGCAT; TACCCGGC',
    'SI-NA-E10': 'ATTGTTTC; CGCAGGAG; GCACCAGT; TAGTACCA',
    'SI-NA-F10': 'ATTCGTGC; CGCGTGCA; GAATACTG; TCGACAAT',
    'SI-NA-G10': 'ATACTGAG; CGGAGACT; GATGCCTC; TCCTATGA',
    'SI-NA-H10': 'ATTTCAGC; CGAGTGAT; GACCGCCA; TCGAATTG',
    'SI-NA-A11': 'ACCAGTCC; CTTTCCTT; GGACAGGG; TAGGTAAA',
    'SI-NA-B11': 'ATGGTCGC; CGACATAG; GATTCGCT; TCCAGATA',
    'SI-NA-C11': 'ACCGAACA; CGACTCTT; GTTTGTGG; TAGACGAC',
    'SI-NA-D11': 'ATATGAGA; CACCTCAG; GCTACTTC; TGGGAGCT',
    'SI-NA-E11': 'ATCGCCAT; CATAAAGG; GGGTTTCC; TCACGGTA',
    'SI-NA-F11': 'AGCAGTTA; CTTGTACC; GAACCCGG; TCGTAGAT',
    'SI-NA-G11': 'AGGGCGTT; CTATACGC; GCTCGTCA; TACATAAG',
    'SI-NA-H11': 'AGGATCGA; CACGATTC; GTATCGAG; TCTCGACT',
    'SI-NA-A12': 'ACTACTGT; CGGGAACG; GACCTCTC; TTATGGAA',
    'SI-NA-B12': 'ACGCTTGG; CGCTACAT; GAAAGACA; TTTGCGTC',
    'SI-NA-C12': 'ATCCGGCA; CCGTTATG; GGTAATGT; TAAGCCAC',
    'SI-NA-D12': 'AGAAACGT; CACTCAAC; GCTGTGTA; TTGCGTCG',
    'SI-NA-E12': 'ACGCGGAA; CGCTATCC; GTTGCATG; TAAATCGT',
    'SI-NA-F12': 'AATTGAAC; CCAGTGGA; GTCCATTG; TGGACCCT',
    'SI-NA-G12': 'ACCCGCAC; CATGCGTA; GTGATAGT; TGATATCG',
    'SI-NA-H12': 'ACGAGTAG; CAATCCCT; GTCCAGGC; TGTGTATA',
    'SI-NN-A1': 'GCCTTGTCAA; GATCCAATCA; TGATTGGATC',
    'SI-NN-A2': 'AACTTCTTTG; ATAAGCGGTA; TACCGCTTAT',
    'SI-NN-A3': 'TGGTTATAGA; GAGCTCATAA; TTATGAGCTC',
    'SI-NN-A4': 'GTAGTGCATC; ATTTGACGGT; ACCGTCAAAT',
    'SI-NN-A5': 'GCTTGATTTA; CGGGTGTGAC; GTCACACCCG',
    'SI-NN-A6': 'GAAGTTTCGC; TTTCAAAGCA; TGCTTTGAAA',
    'SI-NN-A7': 'GCAGTTGTTT; ACACTACTTT; AAAGTAGTGT',
    'SI-NN-A8': 'GCCGCAAGTA; AAAGGTCCGC; GCGGACCTTT',
    'SI-NN-A9': 'AAGTTGTATG; TGTACAATGC; GCATTGTACA',
    'SI-NN-A10': 'AGCAACCTTT; TTCAGCGCTA; TAGCGCTGAA',
    'SI-NN-A11': 'GACGAGGGTT; TTACTTTGAC; GTCAAAGTAA',
    'SI-NN-A12': 'TGAACAGTCG; ATTTCTCAGA; TCTGAGAAAT',
    'SI-NN-B1': 'CGAAAGGAGT; ACACCAAACA; TGTTTGGTGT',
    'SI-NN-B2': 'GAATGACTTG; TGAGCTCGCT; AGCGAGCTCA',
    'SI-NN-B3': 'GCCAGGGATT; CAAGTTTAGG; CCTAAACTTG',
    'SI-NN-B4': 'CTTTGTCCGC; GCTGTCCCGT; ACGGGACAGC',
    'SI-NN-B5': 'AGCTTGGGTG; AGCGTATAGT; ACTATACGCT',
    'SI-NN-B6': 'TCGCACCGGT; TAGCCTCAGG; CCTGAGGCTA',
    'SI-NN-B7': 'TTTAGGTAGG; ACTGAGGGAC; GTCCCTCAGT',
    'SI-NN-B8': 'GTTCGAGCGG; CTGTGGGTTT; AAACCCACAG',
    'SI-NN-B9': 'AGGGTATGGC; GAGTCCGACT; AGTCGGACTC',
    'SI-NN-B10': 'TACCCACTAT; TGGAACATAT; ATATGTTCCA',
    'SI-NN-B11': 'TTCAGGCTAC; CTGGGTATTG; CAATACCCAG',
    'SI-NN-B12': 'AGGAATAGAT; TGCGGTCACG; CGTGACCGCA',
    'SI-NN-C1': 'ACAGCGCTGT; GAGGGTCATC; GATGACCCTC',
    'SI-NN-C2': 'GACGTACGGA; ACCTCGCTTT; AAAGCGAGGT',
    'SI-NN-C3': 'CTTAGATGCA; CTATTCGACT; AGTCGAATAG',
    'SI-NN-C4': 'ACTCCTCAAC; ATTCACGGGA; TCCCGTGAAT',
    'SI-NN-C5': 'TCCATACTGT; GAGCGACTTC; GAAGTCGCTC',
    'SI-NN-C6': 'GCCAGAATGG; GAATTGTATC; GATACAATTC',
    'SI-NN-C7': 'ATTGCAAGAC; CGGTGACCAT; ATGGTCACCG',
    'SI-NN-C8': 'CAACATATCG; AACTAAAGGC; GCCTTTAGTT',
    'SI-NN-C9': 'CAGGGACCTC; AATAGCAGCA; TGCTGCTATT',
    'SI-NN-C10': 'ATTTGGGAAT; TCAGCCGAGT; ACTCGGCTGA',
    'SI-NN-C11': 'TGGATAATTG; TTTGTGATCA; TGATCACAAA',
    'SI-NN-C12': 'CAGATTATGA; GTGCCTGTAC; GTACAGGCAC',
    'SI-NN-D1': 'AATGGTAAGC; CTGTGAAGTT; AACTTCACAG',
    'SI-NN-D2': 'CATCCCTCGG; AGGGTAGGCG; CGCCTACCCT',
    'SI-NN-D3': 'CTGGTCCGTC; ACGAATAAGG; CCTTATTCGT',
    'SI-NN-D4': 'GTCGTAAATT; GTAGTAGGCT; AGCCTACTAC',
    'SI-NN-D5': 'CAACACTGAT; CAAACCAGGG; CCCTGGTTTG',
    'SI-NN-D6': 'CAGACTGAAT; TGCCTAACCG; CGGTTAGGCA',
    'SI-NN-D7': 'CGGACACGCT; TCACGATATA; TATATCGTGA',
    'SI-NN-D8': 'CTCGGCTCTC; TATACTTCCA; TGGAAGTATA',
    'SI-NN-D9': 'AAGCCTATCA; GTAGTGAACA; TGTTCACTAC',
    'SI-NN-D10': 'ACTGTGCCAA; TAACCGTTAT; ATAACGGTTA',
    'SI-NN-D11': 'CTACTCCCAT; TACGTTGCGG; CCGCAACGTA',
    'SI-NN-D12': 'AGACTCTAAC; GTGTCGATGT; ACATCGACAC',
    'SI-NN-E1': 'TGAGCCGGCA; TGCTGCATGT; ACATGCAGCA',
    'SI-NN-E2': 'TAGCTTGCGT; GCTGCTAAAG; CTTTAGCAGC',
    'SI-NN-E3': 'GTACACCGGG; AACAGTCGCG; CGCGACTGTT',
    'SI-NN-E4': 'CGCGTAGACG; AAAGTAGCTG; CAGCTACTTT',
    'SI-NN-E5': 'CCGATATATT; AACTATCCGA; TCGGATAGTT',
    'SI-NN-E6': 'TTGGGCGGGA; ATGTATCTGT; ACAGATACAT',
    'SI-NN-E7': 'GTTTATGAGG; GCCAAACAGC; GCTGTTTGGC',
    'SI-NN-E8': 'TTGGATACTC; CGTACTGAAG; CTTCAGTACG',
    'SI-NN-E9': 'GCTATCTATC; AAAGATGGAT; ATCCATCTTT',
    'SI-NN-E10': 'ATGTGATCGC; TGACCTACCT; AGGTAGGTCA',
    'SI-NN-E11': 'TCCTCACATG; AACAGATTCA; TGAATCTGTT',
    'SI-NN-E12': 'GCCTCCTAAT; CTCCTCCTGT; ACAGGAGGAG',
    'SI-NN-F1': 'CGAGGCTGAT; TCGACTTTCT; AGAAAGTCGA',
    'SI-NN-F2': 'CTCATGACAT; TGTTCCGCAC; GTGCGGAACA',
    'SI-NN-F3': 'AACGCGGCAA; GCCCGTTTAC; GTAAACGGGC',
    'SI-NN-F4': 'AACACCTCTC; GATTGTATGA; TCATACAATC',
    'SI-NN-F5': 'AAATAACGCG; ATAGAGGAGC; GCTCCTCTAT',
    'SI-NN-F6': 'GAAATCTTGT; TAGACGCCAC; GTGGCGTCTA',
    'SI-NN-F7': 'TAGATGGACT; CCAGGGATAT; ATATCCCTGG',
    'SI-NN-F8': 'CAATCTGTAT; TCCCATCGTT; AACGATGGGA',
    'SI-NN-F9': 'GCGAAAGTAT; GTGTCACAGA; TCTGTGACAC',
    'SI-NN-F10': 'CCCAGAGCTT; ATGCTGTAAT; ATTACAGCAT',
    'SI-NN-F11': 'GACTACAGGA; AGTGACAAAG; CTTTGTCACT',
    'SI-NN-F12': 'CAATTCATGG; ACGTAGTTCG; CGAACTACGT',
    'SI-NN-G1': 'TGGGAAGGGC; ACTAACGATG; CATCGTTAGT',
    'SI-NN-G2': 'TACTTCGCAT; AACGGTGTCG; CGACACCGTT',
    'SI-NN-G3': 'TAAACTGGCA; CCGACCTCTT; AAGAGGTCGG',
    'SI-NN-G4': 'TTGAAGAACT; CAACACCAGG; CCTGGTGTTG',
    'SI-NN-G5': 'TCCCTCGTCA; ATCAGGTGTG; CACACCTGAT',
    'SI-NN-G6': 'ACTGGCCTAA; CGCTCCCTTG; CAAGGGAGCG',
    'SI-NN-G7': 'TCATAATGCA; GATGAGGCGA; TCGCCTCATC',
    'SI-NN-G8': 'CGCCACGTTA; CTTTCATAGG; CCTATGAAAG',
    'SI-NN-G9': 'TGGACTAAGC; CTTAACATCG; CGATGTTAAG',
    'SI-NN-G10': 'AAGCCCGGCA; GAGTTTCCGT; ACGGAAACTC',
    'SI-NN-G11': 'ATAGTGGCGG; TACTGTTGTT; AACAACAGTA',
    'SI-NN-G12': 'CCAACCGGAC; GTTCTATCTA; TAGATAGAAC',
    'SI-NN-H1': 'TTACAGAGGG; GTTTATGGCA; TGCCATAAAC',
    'SI-NN-H2': 'TCCAACAACG; GTCCGGGTTT; AAACCCGGAC',
    'SI-NN-H3': 'AAAGCATGTC; AGATACTACT; AGTAGTATCT',
    'SI-NN-H4': 'AGAAGTCGTT; AGGACATTTA; TAAATGTCCT',
    'SI-NN-H5': 'GCTAGCGTTC; TCGCGTGGTG; CACCACGCGA',
    'SI-NN-H6': 'CAACTAGCTT; TCAACTAATC; GATTAGTTGA',
    'SI-NN-H7': 'AGGGCCAGTT; TAGGGCAAAT; ATTTGCCCTA',
    'SI-NN-H8': 'CTCTATGCGT; CCTCTGATGC; GCATCAGAGG',
    'SI-NN-H9': 'GTCCATACAA; AGCCACTCAC; GTGAGTGGCT',
    'SI-NN-H10': 'AGGGATGCAA; CTCATATCCT; AGGATATGAG',
    'SI-NN-H11': 'TTCAAGTCCT; CAGCAGCTAA; TTAGCTGCTG',
    'SI-NN-H12': 'CTCCAACCTA; GCACCGCATC; GATGCGGTGC',
    'SI-NT-A1': 'ATTTACCGCA; GACAATAAAG; CTTTATTGTC',
    'SI-NT-A2': 'TTGTCGTAGA; CAATGTAGCA; TGCTACATTG',
    'SI-NT-A3': 'AGTCCTGCGG; TGACACAAGT; ACTTGTGTCA',
    'SI-NT-A4': 'TTGTTCATGT; TGACAGCTGA; TCAGCTGTCA',
    'SI-NT-A5': 'TCAGGAAGGA; GAACGTGCTT; AAGCACGTTC',
    'SI-NT-A6': 'CTGTTAGAGG; CCACGCTTCG; CGAAGCGTGG',
    'SI-NT-A7': 'AGATGAGAAT; GTCGACGGGT; ACCCGTCGAC',
    'SI-NT-A8': 'CCAAAGCCGG; ACCGTGCACA; TGTGCACGGT',
    'SI-NT-A9': 'AGTCATAATG; AGGCTTGAAA; TTTCAAGCCT',
    'SI-NT-A10': 'TTCATCAGAG; TTGTCGTCTC; GAGACGACAA',
    'SI-NT-A11': 'GAAGCGCGAA; CAGCGAAATT; AATTTCGCTG',
    'SI-NT-A12': 'ATCCGCCGAA; GCTACAGAAT; ATTCTGTAGC',
    'SI-NT-B1': 'CTTATTGTGG; AGCTGTGGGT; ACCCACAGCT',
    'SI-NT-B2': 'ATTCGTTGGG; CATCAGGAGC; GCTCCTGATG',
    'SI-NT-B3': 'GTGGCCTCAT; TCGAAAGTGA; TCACTTTCGA',
    'SI-NT-B4': 'CTATGGCATC; CTCTGAGCGC; GCGCTCAGAG',
    'SI-NT-B5': 'AAACCACAGT; CCGCAAATGG; CCATTTGCGG',
    'SI-NT-B6': 'ATGTATCCAC; CAGGCTGAGG; CCTCAGCCTG',
    'SI-NT-B7': 'GATGAGTCTG; TATGTAACCG; CGGTTACATA',
    'SI-NT-B8': 'CTCACAATAA; CCGTGTTTAA; TTAAACACGG',
    'SI-NT-B9': 'TCTGTCGCAA; ATCCGAACTG; CAGTTCGGAT',
    'SI-NT-B10': 'CATCGAGAAG; GTGCATCCGC; GCGGATGCAC',
    'SI-NT-B11': 'ACGTATTGGG; CAATCGCAAA; TTTGCGATTG',
    'SI-NT-B12': 'CTTACGCGAC; CCTGTCGGAT; ATCCGACAGG',
    'SI-NT-C1': 'GATAGTGAAG; CGTTCGCCAG; CTGGCGAACG',
    'SI-NT-C2': 'CTGTGCAATG; ATGGTGCTTT; AAAGCACCAT',
    'SI-NT-C3': 'AAAGCTGAGC; CAGGAACGAG; CTCGTTCCTG',
    'SI-NT-C4': 'GTCCAAGTCG; GTCATGGCAC; GTGCCATGAC',
    'SI-NT-C5': 'GATTTCCATC; CTTATGGTCA; TGACCATAAG',
    'SI-NT-C6': 'CTAAATGGAT; AATCACATAC; GTATGTGATT',
    'SI-NT-C7': 'ATTTCAGTTC; GCAGCATTAA; TTAATGCTGC',
    'SI-NT-C8': 'TTGCGACGTC; TTAATCCACA; TGTGGATTAA',
    'SI-NT-C9': 'GTACTGTCCA; TTTGTTGGAA; TTCCAACAAA',
    'SI-NT-C10': 'AAACGGTTTA; TCTTCGTTAC; GTAACGAAGA',
    'SI-NT-C11': 'CGATAGTTCT; GCGATTTCCT; AGGAAATCGC',
    'SI-NT-C12': 'TACTTTAGCT; GAGTTATTTG; CAAATAACTC',
    'SI-NT-D1': 'CTGGGATTAA; AGTAAAGTTC; GAACTTTACT',
    'SI-NT-D2': 'TACACTATTC; ATTGCAACGT; ACGTTGCAAT',
    'SI-NT-D3': 'AGAGCTATTT; CTGGCACCCA; TGGGTGCCAG',
    'SI-NT-D4': 'AGGTCGTTAT; AGGTTATCCA; TGGATAACCT',
    'SI-NT-D5': 'GCTGGACAGG; TAATCTCTGT; ACAGAGATTA',
    'SI-NT-D6': 'ACTTAGATGG; AATGTTGAGT; ACTCAACATT',
    'SI-NT-D7': 'AGGCGCGAGT; TGTGTCTATA; TATAGACACA',
    'SI-NT-D8': 'GAGGTCGTAC; CAACTGCGGG; CCCGCAGTTG',
    'SI-NT-D9': 'CCCAATGAGC; AGTTTCTGAT; ATCAGAAACT',
    'SI-NT-D10': 'ACATTCAGGG; GTCCTGAGAG; CTCTCAGGAC',
    'SI-NT-D11': 'AGAAACGGTG; TCACCCAGCA; TGCTGGGTGA',
    'SI-NT-D12': 'AGTTGCAAGT; ATACTTCATG; CATGAAGTAT',
    'SI-NT-E1': 'GCCTAGAAAT; ACTACTCCGG; CCGGAGTAGT',
    'SI-NT-E2': 'TACAAAGATG; CCGATGACGT; ACGTCATCGG',
    'SI-NT-E3': 'GCAGGCTTAG; CGTCTATTGC; GCAATAGACG',
    'SI-NT-E4': 'CAGCTCCAAT; TAGGAGGGTG; CACCCTCCTA',
    'SI-NT-E5': 'TTTGGAGAAA; CAGCCCTTGA; TCAAGGGCTG',
    'SI-NT-E6': 'TGTCGCTTTC; CCTAAAGGGT; ACCCTTTAGG',
    'SI-NT-E7': 'GTGTTGCGAG; CACTTTGAGC; GCTCAAAGTG',
    'SI-NT-E8': 'GTCTGTTCTG; TCTGATGCTT; AAGCATCAGA',
    'SI-NT-E9': 'TCGCTCAATC; GCTTACGTGA; TCACGTAAGC',
    'SI-NT-E10': 'CGTTACTAGC; AATGGCCATT; AATGGCCATT',
    'SI-NT-E11': 'GTGCAGATTT; TAAAGGCGAT; ATCGCCTTTA',
    'SI-NT-E12': 'GTTACCGAAA; CGTTTGAATC; GATTCAAACG',
    'SI-NT-F1': 'CGGTATGGAA; TGCAACTGGT; ACCAGTTGCA',
    'SI-NT-F2': 'TCGGTTTAGT; TAAAGTGTTC; GAACACTTTA',
    'SI-NT-F3': 'CTTTGCTTTG; ACATTCATTC; GAATGAATGT',
    'SI-NT-F4': 'ATGATCGCAC; GCGGTATGTA; TACATACCGC',
    'SI-NT-F5': 'CGGCGTGTTA; TGAGACGCGG; CCGCGTCTCA',
    'SI-NT-F6': 'TCATTTCCGC; ACAGCTGTTG; CAACAGCTGT',
    'SI-NT-F7': 'TTGTGCCCAG; TTGCGAGTTG; CAACTCGCAA',
    'SI-NT-F8': 'AGCCAACGTG; TCAAAGGAAC; GTTCCTTTGA',
    'SI-NT-F9': 'GATCCATACT; ATCGAGAGAA; TTCTCTCGAT',
    'SI-NT-F10': 'TTTCCATGAA; CGGTTCTAAC; GTTAGAACCG',
    'SI-NT-F11': 'TCTTTATCGG; CCCAATAGCG; CGCTATTGGG',
    'SI-NT-F12': 'GAACCCGATG; TCTATCCGGG; CCCGGATAGA',
    'SI-NT-G1': 'GATGTCTGTG; CGTGCTACCG; CGGTAGCACG',
    'SI-NT-G2': 'TGTTAGACTA; TCATGACGAC; GTCGTCATGA',
    'SI-NT-G3': 'TAGAACGCTT; GTCGCAAACG; CGTTTGCGAC',
    'SI-NT-G4': 'AATTTGACGT; AGAAGTGAGG; CCTCACTTCT',
    'SI-NT-G5': 'GAGTGGCCAC; GATGCACAGT; ACTGTGCATC',
    'SI-NT-G6': 'ATCAGTTACG; TACAATCTCT; AGAGATTGTA',
    'SI-NT-G7': 'TGTAAGCTTT; CGGACTAGTC; GACTAGTCCG',
    'SI-NT-G8': 'GCTTCGGTCT; CGCGGGTTAG; CTAACCCGCG',
    'SI-NT-G9': 'AGTCTAAGAC; CTGAAGTGAA; TTCACTTCAG',
    'SI-NT-G10': 'TGAAACATTC; CCTCCTGCCT; AGGCAGGAGG',
    'SI-NT-G11': 'CCTCACGAAA; TGCCCTGTGC; GCACAGGGCA',
    'SI-NT-G12': 'CTACGGGCTT; AGGCGTCCCT; AGGGACGCCT',
    'SI-NT-H1': 'GCGGCGTAAA; CACGCGATCA; TGATCGCGTG',
    'SI-NT-H2': 'TCTCCTTCGG; TGTCCGTCGC; GCGACGGACA',
    'SI-NT-H3': 'CCTTACCCAT; TCCCGGCAAC; GTTGCCGGGA',
    'SI-NT-H4': 'AAGGAACATC; TATCTGTGGG; CCCACAGATA',
    'SI-NT-H5': 'GTGGGAACTT; GCACTTACAG; CTGTAAGTGC',
    'SI-NT-H6': 'ACCGCACCAC; TCGGATTATA; TATAATCCGA',
    'SI-NT-H7': 'ACCTTTATCT; CGAGTGCCAA; TTGGCACTCG',
    'SI-NT-H8': 'AGTAGCCCGT; TTCGGGACCT; AGGTCCCGAA',
    'SI-NT-H9': 'AGATAGCATA; CATTTCCGGA; TCCGGAAATG',
    'SI-NT-H10': 'TGGCGTTAAA; TGTTAAGATG; CATCTTAACA',
    'SI-NT-H11': 'TCAGGCGAAA; TCTCTGGAAG; CTTCCAGAGA',
    'SI-NT-H12': 'AAGACATAGC; ATGTGGACGT; ACGTCCACAT',
    'SI-TT-A1': 'GTAACATGCG; AGTGTTACCT; AGGTAACACT',
    'SI-TT-A2': 'GTGGATCAAA; GCCAACCCTG; CAGGGTTGGC',
    'SI-TT-A3': 'CACTACGAAA; TTAGACTGAT; ATCAGTCTAA',
    'SI-TT-A4': 'CTCTAGCGAG; TATCTTCATC; GATGAAGATA',
    'SI-TT-A5': 'GTAGCCCTGT; GAGCATCTAT; ATAGATGCTC',
    'SI-TT-A6': 'TAACGCGTGA; CCCTAACTTC; GAAGTTAGGG',
    'SI-TT-A7': 'TCCCAAGGGT; TACTACCTTT; AAAGGTAGTA',
    'SI-TT-A8': 'CGAAGTATAC; GAACTTGGAG; CTCCAAGTTC',
    'SI-TT-A9': 'AAGTGGAGAG; TTCCTGTTAC; GTAACAGGAA',
    'SI-TT-A10': 'CGTGACATGC; ATGGTCTAAA; TTTAGACCAT',
    'SI-TT-A11': 'CGGAACCCAA; GATTCGAGGA; TCCTCGAATC',
    'SI-TT-A12': 'CACCGCACCA; GACTGTCAAT; ATTGACAGTC',
    'SI-TT-B1': 'ACAGTAACTA; ACAGTTCGTT; AACGAACTGT',
    'SI-TT-B2': 'TCTACCATTT; CGGGAGAGTC; GACTCTCCCG',
    'SI-TT-B3': 'CACGGTGAAT; GTTCGTCACA; TGTGACGAAC',
    'SI-TT-B4': 'GTAGACGAAA; CTAGTGTGGT; ACCACACTAG',
    'SI-TT-B5': 'TCGGCTCTAC; CCGATGGTCT; AGACCATCGG',
    'SI-TT-B6': 'AATGCCATGA; TACGTAATGC; GCATTACGTA',
    'SI-TT-B7': 'GCCTTCGGTA; CCAACGATTT; AAATCGTTGG',
    'SI-TT-B8': 'GCACTGAGAA; TATGCGTGAA; TTCACGCATA',
    'SI-TT-B9': 'TATTGAGGCA; CAGGTAAGTG; CACTTACCTG',
    'SI-TT-B10': 'GCCCGATGGA; AATCGTCTAG; CTAGACGATT',
    'SI-TT-B11': 'TCTTACTTGC; TGACCTCTAG; CTAGAGGTCA',
    'SI-TT-B12': 'CGTCAAGGGC; TAGGTCACTC; GAGTGACCTA',
    'SI-TT-C1': 'TGCGCGGTTT; CAAGGATAAA; TTTATCCTTG',
    'SI-TT-C2': 'CAATCCCGAC; CCGAGTAGTA; TACTACTCGG',
    'SI-TT-C3': 'ATGGCTTGTG; GAATGTTGTG; CACAACATTC',
    'SI-TT-C4': 'TTCTCGATGA; TGTCGGGCAC; GTGCCCGACA',
    'SI-TT-C5': 'TCCGTTGGAT; ACGTTCTCGC; GCGAGAACGT',
    'SI-TT-C6': 'ACGACTACCA; ACGACCCTAA; TTAGGGTCGT',
    'SI-TT-C7': 'CGCGCACTTA; CCTGTATTCT; AGAATACAGG',
    'SI-TT-C8': 'GCTACAAAGC; CACGTGCCCT; AGGGCACGTG',
    'SI-TT-C9': 'TATCAGCCTA; GTTTCGTCCT; AGGACGAAAC',
    'SI-TT-C10': 'AGAATGGTTT; GAGGGTGGGA; TCCCACCCTC',
    'SI-TT-C11': 'ATGGGTGAAA; CTTGGGAATT; AATTCCCAAG',
    'SI-TT-C12': 'TCGTCAAGAT; GCAACTCAGG; CCTGAGTTGC',
    'SI-TT-D1': 'TGCAATGTTC; GCTTGTCGAA; TTCGACAAGC',
    'SI-TT-D2': 'TTAATACGCG; CACCTCGGGT; ACCCGAGGTG',
    'SI-TT-D3': 'CCTTCTAGAG; AATACAACGA; TCGTTGTATT',
    'SI-TT-D4': 'GCAGTATAGG; TTCCGTGCAC; GTGCACGGAA',
    'SI-TT-D5': 'TGGTTCGGGT; GTGGCAGGAG; CTCCTGCCAC',
    'SI-TT-D6': 'CCCAGCTTCT; GACACCAAAC; GTTTGGTGTC',
    'SI-TT-D7': 'CCTGTCAGGG; AGCCCGTAAC; GTTACGGGCT',
    'SI-TT-D8': 'CGCTGAAATC; AGGTGTCTGC; GCAGACACCT',
    'SI-TT-D9': 'TGGTCCCAAG; CCTCTGGCGT; ACGCCAGAGG',
    'SI-TT-D10': 'ATGCGAATGG; ACAAGTGTCG; CGACACTTGT',
    'SI-TT-D11': 'CGAATATTCG; CTGGAAGCAA; TTGCTTCCAG',
    'SI-TT-D12': 'GAATTGGTTA; ACTCTAGTAG; CTACTAGAGT',
    'SI-TT-E1': 'TTATTCGAGG; CTGTCCTGCT; AGCAGGACAG',
    'SI-TT-E2': 'ATGGAGGGAG; ATAACCCATT; AATGGGTTAT',
    'SI-TT-E3': 'ACCAGACAAC; AGGAACTAGG; CCTAGTTCCT',
    'SI-TT-E4': 'AACCACGCAT; ATTCAGGTTA; TAACCTGAAT',
    'SI-TT-E5': 'CGCGGTAGGT; CAGGATGTTG; CAACATCCTG',
    'SI-TT-E6': 'TTGAGAGTCA; AACCTGGTAG; CTACCAGGTT',
    'SI-TT-E7': 'GTCCTTCGGC; TCATGCACAG; CTGTGCATGA',
    'SI-TT-E8': 'GAGCAAGGGC; ATTGACTTGG; CCAAGTCAAT',
    'SI-TT-E9': 'TGTCCCAACG; TCGATGTCCA; TGGACATCGA',
    'SI-TT-E10': 'CACAATCCCA; ATATCCACAA; TTGTGGATAT',
    'SI-TT-E11': 'TCCGGGACAA; GTGAATGCCA; TGGCATTCAC',
    'SI-TT-E12': 'CGTCCACCTG; CATTCATGAC; GTCATGAATG',
    'SI-TT-F1': 'AAGATTGGAT; AGCGGGATTT; AAATCCCGCT',
    'SI-TT-F2': 'AAGGGCCGCA; CTGATTCCTC; GAGGAATCAG',
    'SI-TT-F3': 'GAGAGGATAT; TTGAAATGGG; CCCATTTCAA',
    'SI-TT-F4': 'CCCACCACAA; ACCTCCGCTT; AAGCGGAGGT',
    'SI-TT-F5': 'CGGCTGGATG; TGATAAGCAC; GTGCTTATCA',
    'SI-TT-F6': 'TTGCCCGTGC; GCGTGAGATT; AATCTCACGC',
    'SI-TT-F7': 'AATGTATCCA; AATGAGCTTA; TAAGCTCATT',
    'SI-TT-F8': 'CTCCTTTAGA; GACATAGCTC; GAGCTATGTC',
    'SI-TT-F9': 'GTCCCATCAA; CGAACGTGAC; GTCACGTTCG',
    'SI-TT-F10': 'CCGGCAACTG; CGGTTTAACA; TGTTAAACCG',
    'SI-TT-F11': 'TTCACACCTT; TAGTGTACAC; GTGTACACTA',
    'SI-TT-F12': 'GAGACGCACG; CTATGAACAT; ATGTTCATAG',
    'SI-TT-G1': 'TGTAGTCATT; CTTGATCGTA; TACGATCAAG',
    'SI-TT-G2': 'CATGTGGGTT; GATTCCTTTA; TAAAGGAATC',
    'SI-TT-G3': 'ATGACGTCGC; AGGTCAGGAT; ATCCTGACCT',
    'SI-TT-G4': 'GCGCTTATGG; GCCTGGCTAG; CTAGCCAGGC',
    'SI-TT-G5': 'ATAGGGCGAG; TGCATCGAGT; ACTCGATGCA',
    'SI-TT-G6': 'GCGGGTAAGT; TAGCACTAAG; CTTAGTGCTA',
    'SI-TT-G7': 'GTTTCACGAT; TTCGGCCAAA; TTTGGCCGAA',
    'SI-TT-G8': 'TAAGCAACTG; CTATACTCAA; TTGAGTATAG',
    'SI-TT-G9': 'CCGGAGGAAG; TGCGGATGTT; AACATCCGCA',
    'SI-TT-G10': 'ACTTTACGTG; TGAACGCCCT; AGGGCGTTCA',
    'SI-TT-G11': 'GATAACCTGC; CATTAGAAAC; GTTTCTAATG',
    'SI-TT-G12': 'CTTGCATAAA; ATCAGGGCTT; AAGCCCTGAT',
    'SI-TT-H1': 'ACAATGTGAA; CGTACCGTTA; TAACGGTACG',
    'SI-TT-H2': 'TAGCATAGTG; CGGCTCTGTC; GACAGAGCCG',
    'SI-TT-H3': 'CCCGTTCTCG; GACGGATTGG; CCAATCCGTC',
    'SI-TT-H4': 'AGTTTCCTGG; TGCCACACAG; CTGTGTGGCA',
    'SI-TT-H5': 'AGCAAGAAGC; TTGTGTTTCT; AGAAACACAA',
    'SI-TT-H6': 'CCTATCCTCG; GAATACTAAC; GTTAGTATTC',
    'SI-TT-H7': 'ACCTCGAGCT; TGTGTTCGAT; ATCGAACACA',
    'SI-TT-H8': 'ATAAGGATAC; ATAGATAGGG; CCCTATCTAT',
    'SI-TT-H9': 'AGAACTTAGA; CGAGTCCTTT; AAAGGACTCG',
    'SI-TT-H10': 'TTATCTAGGG; AAAGGCTCTA; TAGAGCCTTT',
    'SI-TT-H11': 'ACAATCGATC; TGACGGAATG; CATTCCGTCA',
    'SI-TT-H12': 'TGATGATTCA; GTAGGAGTCG; CGACTCCTAC',

}

#normal sample type choices
normal_sample_type_chioces =  (
    ("D", "DLP+ library"),
    ("W", "GSC WGS library")
)
