# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-17 23:00
from __future__ import unicode_literals

import core.helpers
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0016_auto_20170731_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_level', models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], default='L', max_length=50, verbose_name='Priority Level')),
                ('analysis_jira_ticket', models.CharField(max_length=50, null=True, verbose_name='Jira ticket')),
                ('sequencings', models.ManyToManyField(to='core.Sequencing')),
            ],
            bases=(models.Model, core.helpers.FieldValue),
        ),
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_submission_date', models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Analysis start date/time')),
                ('analysis_completion_date', models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Analysis start date/time')),
                ('run_status', models.CharField(choices=[('W', 'Waiting to be reviewed/submitted'), ('R', 'Running'), ('C', 'Completed successfully'), ('E', 'Error in run'), ('A', 'Archiving')], default='W', max_length=50, verbose_name='Run Status')),
                ('analysis_information', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sisyphus.AnalysisInformation')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50, verbose_name='Analysis Version')),
            ],
        ),
        migrations.AddField(
            model_name='analysisinformation',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisyphus.AnalysisVersion', verbose_name='Analysis Version'),
        ),
    ]
