# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-04 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisyphus', '0001_initial'),
        ('pbal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pbalanalysisinformation',
            name='sequencings',
            field=models.ManyToManyField(to='pbal.PbalSequencing'),
        ),
    ]
