# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-09 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisyphus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dlpanalysisinformation',
            name='montage_status',
            field=models.CharField(choices=[('Success', 'Success'), ('Error', 'Error'), ('Ignore', 'Ignore'), ('Pending', 'Pending')], default='Pending', max_length=50, verbose_name='Montage State'),
        ),
        migrations.AddField(
            model_name='historicaldlpanalysisinformation',
            name='montage_status',
            field=models.CharField(choices=[('Success', 'Success'), ('Error', 'Error'), ('Ignore', 'Ignore'), ('Pending', 'Pending')], default='Pending', max_length=50, verbose_name='Montage State'),
        ),
    ]
