# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-11-22 01:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sisyphus', '0001_initial'),
        ('core', '0023_auto_20171116_1353'),
    ]

    operations = [
    	migrations.RemoveField(
            model_name='analysisrun',
            name='analysis_information',
        ),
        migrations.DeleteModel(
            name='AnalysisInformation',
        ),
    ]
