# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-09 21:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sisyphus', '0002_update_pbal_relationship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpbalanalysisinformation',
            name='analysis_run',
        ),
        migrations.RemoveField(
            model_name='historicalpbalanalysisinformation',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalpbalanalysisinformation',
            name='reference_genome',
        ),
        migrations.RemoveField(
            model_name='historicalpbalanalysisinformation',
            name='version',
        ),
        migrations.RemoveField(
            model_name='historicalpbalanalysisversion',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaltenxanalysisinformation',
            name='analysis_run',
        ),
        migrations.RemoveField(
            model_name='historicaltenxanalysisinformation',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaltenxanalysisinformation',
            name='reference_genome',
        ),
        migrations.RemoveField(
            model_name='historicaltenxanalysisinformation',
            name='version',
        ),
        migrations.RemoveField(
            model_name='historicaltenxanalysisversion',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='pbalanalysisinformation',
            name='analysis_run',
        ),
        migrations.RemoveField(
            model_name='pbalanalysisinformation',
            name='reference_genome',
        ),
        migrations.RemoveField(
            model_name='pbalanalysisinformation',
            name='sequencings',
        ),
        migrations.RemoveField(
            model_name='pbalanalysisinformation',
            name='version',
        ),
        migrations.RemoveField(
            model_name='tenxanalysisinformation',
            name='analysis_run',
        ),
        migrations.RemoveField(
            model_name='tenxanalysisinformation',
            name='reference_genome',
        ),
        migrations.RemoveField(
            model_name='tenxanalysisinformation',
            name='sequencings',
        ),
        migrations.RemoveField(
            model_name='tenxanalysisinformation',
            name='version',
        ),
        migrations.DeleteModel(
            name='HistoricalPbalAnalysisInformation',
        ),
        migrations.DeleteModel(
            name='HistoricalPbalAnalysisVersion',
        ),
        migrations.DeleteModel(
            name='HistoricalTenxAnalysisInformation',
        ),
        migrations.DeleteModel(
            name='HistoricalTenxAnalysisVersion',
        ),
        migrations.DeleteModel(
            name='PbalAnalysisInformation',
        ),
        migrations.DeleteModel(
            name='PbalAnalysisVersion',
        ),
        migrations.DeleteModel(
            name='TenxAnalysisInformation',
        ),
        migrations.DeleteModel(
            name='TenxAnalysisVersion',
        ),
    ]
