# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-11-22 18:34
from __future__ import unicode_literals

import core.helpers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sisyphus', '0002_auto_20171121_1707'),
        ('core', '0024_auto_20171121_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_level', models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], default='L', max_length=50, verbose_name='Priority Level')),
                ('analysis_jira_ticket', models.CharField(max_length=50, null=True, verbose_name='Jira ticket')),
                ('sequencings', models.ManyToManyField(to='core.DlpSequencing')),
            ],
            bases=(models.Model, core.helpers.FieldValue),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='analysis_information',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sisyphus.AnalysisInformation'),
        ),
        migrations.AddField(
            model_name='analysisinformation',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisyphus.AnalysisVersion', verbose_name='Analysis Version'),
        ),
    ]
