# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-09 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sisyphus', '0003_auto_20190409_1419'),
        ('dlp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dlpanalysisinformation',
            name='lanes',
            field=models.ManyToManyField(blank=True, to='dlp.DlpLane'),
        ),
        migrations.AlterField(
            model_name='dlpanalysisinformation',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dlp.DlpLibrary', verbose_name='Library'),
        ),
        migrations.AlterField(
            model_name='dlpanalysisinformation',
            name='sequencings',
            field=models.ManyToManyField(to='dlp.DlpSequencing'),
        ),
        migrations.AlterField(
            model_name='historicaldlpanalysisinformation',
            name='library',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dlp.DlpLibrary', verbose_name='Library'),
        ),
    ]
