# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-01-08 20:55
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sisyphus', '0003_auto_20171122_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceGenome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_genome', models.CharField(max_length=50, verbose_name='reference_genome')),
            ],
        ),
        migrations.RemoveField(
            model_name='analysisrun',
            name='analysis_completion_date',
        ),
        migrations.RemoveField(
            model_name='analysisrun',
            name='analysis_information',
        ),
        migrations.RemoveField(
            model_name='analysisrun',
            name='analysis_submission_date',
        ),
        migrations.AddField(
            model_name='analysisinformation',
            name='analysis_run',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='sisyphus.AnalysisRun'),
        ),
        migrations.AddField(
            model_name='analysisinformation',
            name='analysis_submission_date',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Analysis submission date'),
        ),
        migrations.AddField(
            model_name='analysisinformation',
            name='sisyphus_options',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='last_updated',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Analysis last updated date/time'),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='log_file',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='error_log'),
        ),
        migrations.AddField(
            model_name='analysisinformation',
            name='reference_genome',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sisyphus.ReferenceGenome', verbose_name='ReferenceGenome'),
        ),
    ]
