# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-18 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisyphus', '0004_auto_20191112_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dlpanalysisinformation',
            name='montage_status',
            field=models.CharField(choices=[('Success', 'Success'), ('Error', 'Error'), ('Deleted', 'Deleted'), ('Ignore', 'Ignore'), ('Pending', 'Pending')], default='Pending', max_length=50, verbose_name='Montage State'),
        ),
        migrations.AlterField(
            model_name='historicaldlpanalysisinformation',
            name='montage_status',
            field=models.CharField(choices=[('Success', 'Success'), ('Error', 'Error'), ('Deleted', 'Deleted'), ('Ignore', 'Ignore'), ('Pending', 'Pending')], default='Pending', max_length=50, verbose_name='Montage State'),
        ),
    ]
