# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-01-17 23:24
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20180117_1448'),
        ('sisyphus', '0004_auto_20180108_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='DlpAnalysisVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50, verbose_name='DlpAnalysis Version')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PbalAnalysisInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_level', models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], default='L', max_length=50, verbose_name='Priority Level')),
                ('analysis_jira_ticket', models.CharField(max_length=50, null=True, verbose_name='Jira ticket')),
                ('analysis_submission_date', models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Analysis submission date')),
                ('sisyphus_options', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True)),
                ('analysis_run', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='sisyphus.AnalysisRun')),
                ('reference_genome', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sisyphus.ReferenceGenome', verbose_name='ReferenceGenome')),
                ('sequencings', models.ManyToManyField(to='core.PbalSequencing')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PbalAnalysisVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50, verbose_name='PbalAnalysis Version')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TenxAnalysisInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_level', models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], default='L', max_length=50, verbose_name='Priority Level')),
                ('analysis_jira_ticket', models.CharField(max_length=50, null=True, verbose_name='Jira ticket')),
                ('analysis_submission_date', models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Analysis submission date')),
                ('sisyphus_options', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True)),
                ('analysis_run', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='sisyphus.AnalysisRun')),
                ('reference_genome', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sisyphus.ReferenceGenome', verbose_name='ReferenceGenome')),
                ('sequencings', models.ManyToManyField(to='core.TenxSequencing')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TenxAnalysisVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50, verbose_name='TenxAnalysis Version')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='AnalysisInformation',
            new_name='DlpAnalysisInformation',
        ),
        migrations.DeleteModel(
            name='AnalysisVersion',
        ),
        migrations.AlterField(
            model_name='dlpanalysisinformation',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisyphus.DlpAnalysisVersion', verbose_name='Analysis Version'),
        ),
        migrations.AddField(
            model_name='tenxanalysisinformation',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisyphus.TenxAnalysisVersion', verbose_name='Analysis Version'),
        ),
        migrations.AddField(
            model_name='pbalanalysisinformation',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisyphus.PbalAnalysisVersion', verbose_name='Analysis Version'),
        ),
    ]
