# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-01-17 23:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20180117_1448'),
        ('sisyphus', '0005_auto_20180117_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='dlpanalysisinformation',
            name='library',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.DlpLibrary', verbose_name='Library'),
        ),
    ]
