# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-01-17 23:30
from __future__ import unicode_literals

from django.db import migrations


def populate_library_from_existing_libraryfields(apps, schema_editor):
    DlpSequencing = apps.get_model('core', 'DlpSequencing')
    DlpAnalysisInformation= apps.get_model('sisyphus', 'DlpAnalysisInformation')

    for new in DlpAnalysisInformation.objects.all():
        new.library = new.sequencings.all()[0].library
        new.save()


class Migration(migrations.Migration):

    dependencies = [
        ('sisyphus', '0006_dlpanalysisinformation_library'),
    ]

    operations = [
        migrations.RunPython(populate_library_from_existing_libraryfields),
    ]
