# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-01-17 23:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sisyphus', '0007_dlpanalysislibrary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dlpanalysisinformation',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DlpLibrary', verbose_name='Library'),
        ),
    ]
