# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-06-13 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisyphus', '0008_auto_20180117_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisrun',
            name='run_status',
            field=models.CharField(default='Unknown', max_length=50, verbose_name='Run Status'),
        ),
    ]
