# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-06-25 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisyphus', '0009_auto_20180613_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dlpanalysisinformation',
            name='sisyphus_options',
        ),
        migrations.RemoveField(
            model_name='pbalanalysisinformation',
            name='sisyphus_options',
        ),
        migrations.RemoveField(
            model_name='tenxanalysisinformation',
            name='sisyphus_options',
        ),
        migrations.AddField(
            model_name='dlpanalysisinformation',
            name='aligner',
            field=models.CharField(choices=[('A', 'bwa-aln'), ('M', 'bwa-mem')], default='A', max_length=50, verbose_name='Aligner'),
        ),
        migrations.AddField(
            model_name='dlpanalysisinformation',
            name='sftp_path',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='sftp path'),
        ),
        migrations.AddField(
            model_name='dlpanalysisinformation',
            name='smoothing',
            field=models.CharField(choices=[('M', 'modal'), ('L', 'loess')], default='M', max_length=50, verbose_name='Smoothing'),
        ),
        migrations.AddField(
            model_name='dlpanalysisinformation',
            name='tantalus_path',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='tantalus path'),
        ),
        migrations.AddField(
            model_name='pbalanalysisinformation',
            name='aligner',
            field=models.CharField(choices=[('A', 'bwa-aln'), ('M', 'bwa-mem')], default='A', max_length=50, verbose_name='Aligner'),
        ),
        migrations.AddField(
            model_name='pbalanalysisinformation',
            name='sftp_path',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='sftp path'),
        ),
        migrations.AddField(
            model_name='pbalanalysisinformation',
            name='smoothing',
            field=models.CharField(choices=[('M', 'modal'), ('L', 'loess')], default='M', max_length=50, verbose_name='Smoothing'),
        ),
        migrations.AddField(
            model_name='pbalanalysisinformation',
            name='tantalus_path',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='tantalus path'),
        ),
        migrations.AddField(
            model_name='tenxanalysisinformation',
            name='aligner',
            field=models.CharField(choices=[('A', 'bwa-aln'), ('M', 'bwa-mem')], default='A', max_length=50, verbose_name='Aligner'),
        ),
        migrations.AddField(
            model_name='tenxanalysisinformation',
            name='sftp_path',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='sftp path'),
        ),
        migrations.AddField(
            model_name='tenxanalysisinformation',
            name='smoothing',
            field=models.CharField(choices=[('M', 'modal'), ('L', 'loess')], default='M', max_length=50, verbose_name='Smoothing'),
        ),
        migrations.AddField(
            model_name='tenxanalysisinformation',
            name='tantalus_path',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='tantalus path'),
        ),
    ]
