# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-08-03 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sisyphus', '0011_auto_20180803_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisrun',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Analysis last updated date/time'),
        ),
    ]
