# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-08-22 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisyphus', '0014_auto_20180821_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='dlpanalysisinformation',
            name='saltant_job_uuid',
            field=models.CharField(editable=False, max_length=36, null=True),
        ),
    ]
