# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-08-27 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20180803_1257'),
        ('sisyphus', '0015_dlpanalysisinformation_saltant_job_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='dlpanalysisinformation',
            name='lanes',
            field=models.ManyToManyField(to='core.DlpLane'),
        ),
    ]
