# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-04 23:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sisyphus', '0016_dlpanalysisinformation_lanes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dlpanalysisinformation',
            name='saltant_job_uuid',
        ),
    ]
