# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-04 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisyphus', '0017_remove_dlpanalysisinformation_saltant_job_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisrun',
            name='run_status',
            field=models.CharField(choices=[('idle', 'Idle'), ('error', 'Error'), ('running', 'Running'), ('archiving', 'Archiving'), ('complete', 'Complete')], default='idle', max_length=50, verbose_name='Run Status'),
        ),
    ]
