# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-18 21:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sisyphus', '0020_change_run_status_names_20180905_1007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dlpanalysisinformation',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='pbalanalysisinformation',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='tenxanalysisinformation',
            options={'ordering': ['pk']},
        ),
    ]
