# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-09 01:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sisyphus', '0021_auto_20180918_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dlpanalysisinformation',
            name='analysis_jira_ticket',
            field=models.CharField(max_length=50, null=True, verbose_name='Analysis Jira ticket'),
        ),
        migrations.AlterField(
            model_name='dlpanalysisinformation',
            name='analysis_run',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sisyphus.AnalysisRun'),
        ),
        migrations.AlterField(
            model_name='dlpanalysisinformation',
            name='analysis_submission_date',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='Analysis submission date'),
        ),
        migrations.AlterField(
            model_name='pbalanalysisinformation',
            name='analysis_jira_ticket',
            field=models.CharField(max_length=50, null=True, verbose_name='Analysis Jira ticket'),
        ),
        migrations.AlterField(
            model_name='pbalanalysisinformation',
            name='analysis_run',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sisyphus.AnalysisRun'),
        ),
        migrations.AlterField(
            model_name='pbalanalysisinformation',
            name='analysis_submission_date',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='Analysis submission date'),
        ),
        migrations.AlterField(
            model_name='tenxanalysisinformation',
            name='analysis_jira_ticket',
            field=models.CharField(max_length=50, null=True, verbose_name='Analysis Jira ticket'),
        ),
        migrations.AlterField(
            model_name='tenxanalysisinformation',
            name='analysis_run',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sisyphus.AnalysisRun'),
        ),
        migrations.AlterField(
            model_name='tenxanalysisinformation',
            name='analysis_submission_date',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='Analysis submission date'),
        ),
    ]
