# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-31 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisyphus', '0022_auto_20190108_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisrun',
            name='run_status',
            field=models.CharField(choices=[('idle', 'Idle'), ('error', 'Error'), ('running', 'Running'), ('archiving', 'Archiving'), ('complete', 'Complete'), ('align_complete', 'Align Complete'), ('hmmcopy_complete', 'Hmmcopy Complete')], default='idle', max_length=50, verbose_name='Run Status'),
        ),
    ]
