# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-04 18:54
from __future__ import unicode_literals

import core.helpers
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_rename_table_pbal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    state_operations = [
        migrations.CreateModel(
            name='HistoricalPbalLane',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('flow_cell_id', models.CharField(max_length=50, verbose_name='Flow cell/Lane ID')),
                ('path_to_archive', models.CharField(blank=True, max_length=150, null=True, verbose_name='Path to archive')),
                ('sequencing_date', models.DateTimeField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical pbal lane',
                'db_table': 'pbal_history_lane',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPbalLibrary',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Description')),
                ('result', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Result')),
                ('failed', models.BooleanField(default=False, verbose_name='Failed')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sample', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Sample', verbose_name='Primary Sample')),
            ],
            options={
                'verbose_name': 'historical pbal library',
                'db_table': 'pbal_history_library',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPbalLibraryConstructionInformation',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('format', models.CharField(blank=True, default='384-well plate', max_length=50, null=True, verbose_name='Format')),
                ('library_construction_method', models.CharField(blank=True, default='pbal', max_length=50, null=True, verbose_name='Library construction method')),
                ('library_type', models.CharField(blank=True, default='methylome', max_length=50, null=True, verbose_name='Library type')),
                ('submission_date', models.DateField(blank=True, null=True, verbose_name='Submission date')),
                ('library_prep_location', models.CharField(blank=True, default='Hirst Lab', max_length=50, null=True, verbose_name='Library prep location')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical pbal library construction information',
                'db_table': 'pbal_history_library_construction_information',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPbalLibraryQuantificationAndStorage',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('qc_check', models.CharField(blank=True, choices=[('P', 'Will sequence'), ('N', 'Will not sequence')], max_length=50, null=True, verbose_name='QC check')),
                ('qc_notes', models.TextField(blank=True, max_length=5000, null=True, verbose_name='QC notes')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical pbal library quantification and storage',
                'db_table': 'pbal_history_library_q_and_s',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPbalLibrarySampleDetail',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('sample_spot_date', models.DateField(blank=True, null=True, verbose_name='Sample spot date')),
                ('spotting_location', models.CharField(blank=True, choices=[('AD', 'Aparicio Lab - Deckard'), ('AR', 'Aparicio Lab - Rachael'), ('H', 'Hansen Lab'), ('G', 'GSC'), ('T', 'TFL flow facility')], max_length=50, null=True, verbose_name='Spotting location')),
                ('cell_state', models.CharField(blank=True, choices=[('C', 'Cells'), ('N', 'Nuclei'), ('M', 'Mixed'), ('U', 'Unknown')], max_length=50, null=True, verbose_name='Cell state')),
                ('estimated_percent_viability', models.IntegerField(blank=True, null=True, verbose_name='Estimated percent viability')),
                ('label_of_original_sample_vial', models.CharField(blank=True, max_length=50, null=True, verbose_name='Label of original sample vial')),
                ('lims_vial_barcode', models.CharField(blank=True, max_length=50, null=True, verbose_name='LIMS vial barcode')),
                ('original_storage_temperature', models.IntegerField(blank=True, null=True, verbose_name='Original storage temperature (C)')),
                ('passage_of_cell_line', models.IntegerField(blank=True, null=True, verbose_name='Passage')),
                ('sample_notes', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Sample notes')),
                ('sample_preparation_method', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Sample preparation method')),
                ('sample_preservation_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sample preservation method')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical pbal library sample detail',
                'db_table': 'pbal_history_library_sample_detail',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPbalSequencing',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('adapter', models.CharField(blank=True, default='CTGTCTCTTATACACATCT', max_length=50, null=True, verbose_name='Adapter')),
                ('format_for_data_submission', models.CharField(blank=True, default='fastq', max_length=50, null=True, verbose_name='Format for data dissemination')),
                ('index_read_type', models.CharField(blank=True, default='Dual Index (i7 and i5)', max_length=50, null=True, verbose_name='Index read type')),
                ('index_read1_length', models.IntegerField(blank=True, default=6, null=True, verbose_name='Index read1 length')),
                ('index_read2_length', models.IntegerField(blank=True, default=6, null=True, verbose_name='Index read2 length')),
                ('read_type', models.CharField(blank=True, choices=[('P', 'PET'), ('S', 'SET')], default='P', max_length=50, null=True, verbose_name='Read type')),
                ('read1_length', models.IntegerField(blank=True, default=150, null=True, verbose_name='Read1 length')),
                ('read2_length', models.IntegerField(blank=True, default=150, null=True, verbose_name='Read2 length')),
                ('sequencing_instrument', models.CharField(blank=True, choices=[('HX', 'HiSeqX'), ('H2500', 'HiSeq2500'), ('N500', 'NextSeq500'), ('N550', 'NextSeq550'), ('MI', 'MiSeq'), ('O', 'other')], default='HX', max_length=50, null=True, verbose_name='Sequencing instrument')),
                ('sequencing_output_mode', models.CharField(blank=True, choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], max_length=50, null=True, verbose_name='Sequencing output mode')),
                ('short_description_of_submission', models.CharField(blank=True, max_length=150, null=True, verbose_name='Short description of submission')),
                ('submission_date', models.DateField(default=datetime.date.today, verbose_name='Submission date')),
                ('number_of_lanes_requested', models.PositiveIntegerField(default=0, verbose_name='Sequencing Goal')),
                ('lane_requested_date', models.DateField(null=True)),
                ('gsc_library_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='GSC library ID')),
                ('sequencer_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sequencer ID')),
                ('sequencing_center', models.CharField(choices=[('BCCAGSC', 'BCCAGSC'), ('UBCBRC', 'UBCBRC')], default='BCCAGSC', max_length=50, null=True, verbose_name='Sequencing center')),
                ('sequencer_notes', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Sequencing notes')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical pbal sequencing',
                'db_table': 'pbal_history_sequencing',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPlate',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('jira_ticket', models.CharField(max_length=50, verbose_name='Jira ticket')),
                ('plate_number', models.IntegerField(blank=True, null=True, verbose_name='Plate number')),
                ('plate_status', models.CharField(blank=True, choices=[('submitted', 'submitted'), ('sequenced', 'sequenced'), ('stored', 'stored')], max_length=50, null=True, verbose_name='Plate status')),
                ('plate_location', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Plate location')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical plate',
                'db_table': 'pbal_plate_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PbalLane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_cell_id', models.CharField(max_length=50, verbose_name='Flow cell/Lane ID')),
                ('path_to_archive', models.CharField(blank=True, max_length=150, null=True, verbose_name='Path to archive')),
                ('sequencing_date', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'pbal_pballane',
            },
            bases=(models.Model, core.helpers.FieldValue),
        ),
        migrations.CreateModel(
            name='PbalLibrary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Description')),
                ('result', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Result')),
                ('failed', models.BooleanField(default=False, verbose_name='Failed')),
                ('projects', models.ManyToManyField(blank=True, related_name='pballibrary_projects', to='core.Project', verbose_name='Project')),
                ('relates_to_dlp', models.ManyToManyField(blank=True, related_name='pballibrary_relates_to_dlp', to='core.DlpLibrary', verbose_name='Relates to (DLP)')),
                ('relates_to_tenx', models.ManyToManyField(blank=True, related_name='pballibrary_relates_to_tenx', to='core.TenxLibrary', verbose_name='Relates to (Tenx)')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pballibrary_sample', to='core.Sample', verbose_name='Primary Sample')),
            ],
            options={
                'ordering': ['sample'],
                'db_table': 'pbal_pballibrary',
            },
            bases=(models.Model, core.helpers.FieldValue, core.helpers.LibraryAssistant),
        ),
        migrations.CreateModel(
            name='PbalLibraryConstructionInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(blank=True, default='384-well plate', max_length=50, null=True, verbose_name='Format')),
                ('library_construction_method', models.CharField(blank=True, default='pbal', max_length=50, null=True, verbose_name='Library construction method')),
                ('library_type', models.CharField(blank=True, default='methylome', max_length=50, null=True, verbose_name='Library type')),
                ('submission_date', models.DateField(blank=True, null=True, verbose_name='Submission date')),
                ('library_prep_location', models.CharField(blank=True, default='Hirst Lab', max_length=50, null=True, verbose_name='Library prep location')),
                ('library', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pbal.PbalLibrary', verbose_name='Library')),
            ],
            options={
                'db_table': 'pbal_pballibraryconstructioninformation',
            },
            bases=(models.Model, core.helpers.FieldValue),
        ),
        migrations.CreateModel(
            name='PbalLibraryQuantificationAndStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qc_check', models.CharField(blank=True, choices=[('P', 'Will sequence'), ('N', 'Will not sequence')], max_length=50, null=True, verbose_name='QC check')),
                ('qc_notes', models.TextField(blank=True, max_length=5000, null=True, verbose_name='QC notes')),
                ('library', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pbal.PbalLibrary', verbose_name='Library')),
            ],
            options={
                'db_table': 'pbal_pballibraryquantificationandstorage',
            },
            bases=(models.Model, core.helpers.FieldValue),
        ),
        migrations.CreateModel(
            name='PbalLibrarySampleDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_spot_date', models.DateField(blank=True, null=True, verbose_name='Sample spot date')),
                ('spotting_location', models.CharField(blank=True, choices=[('AD', 'Aparicio Lab - Deckard'), ('AR', 'Aparicio Lab - Rachael'), ('H', 'Hansen Lab'), ('G', 'GSC'), ('T', 'TFL flow facility')], max_length=50, null=True, verbose_name='Spotting location')),
                ('cell_state', models.CharField(blank=True, choices=[('C', 'Cells'), ('N', 'Nuclei'), ('M', 'Mixed'), ('U', 'Unknown')], max_length=50, null=True, verbose_name='Cell state')),
                ('estimated_percent_viability', models.IntegerField(blank=True, null=True, verbose_name='Estimated percent viability')),
                ('label_of_original_sample_vial', models.CharField(blank=True, max_length=50, null=True, verbose_name='Label of original sample vial')),
                ('lims_vial_barcode', models.CharField(blank=True, max_length=50, null=True, verbose_name='LIMS vial barcode')),
                ('original_storage_temperature', models.IntegerField(blank=True, null=True, verbose_name='Original storage temperature (C)')),
                ('passage_of_cell_line', models.IntegerField(blank=True, null=True, verbose_name='Passage')),
                ('sample_notes', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Sample notes')),
                ('sample_preparation_method', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Sample preparation method')),
                ('sample_preservation_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sample preservation method')),
                ('library', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pbal.PbalLibrary', verbose_name='Library')),
            ],
            options={
                'db_table': 'pbal_pballibrarysampledetail',
            },
            bases=(models.Model, core.helpers.FieldValue),
        ),
        migrations.CreateModel(
            name='PbalSequencing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adapter', models.CharField(blank=True, default='CTGTCTCTTATACACATCT', max_length=50, null=True, verbose_name='Adapter')),
                ('format_for_data_submission', models.CharField(blank=True, default='fastq', max_length=50, null=True, verbose_name='Format for data dissemination')),
                ('index_read_type', models.CharField(blank=True, default='Dual Index (i7 and i5)', max_length=50, null=True, verbose_name='Index read type')),
                ('index_read1_length', models.IntegerField(blank=True, default=6, null=True, verbose_name='Index read1 length')),
                ('index_read2_length', models.IntegerField(blank=True, default=6, null=True, verbose_name='Index read2 length')),
                ('read_type', models.CharField(blank=True, choices=[('P', 'PET'), ('S', 'SET')], default='P', max_length=50, null=True, verbose_name='Read type')),
                ('read1_length', models.IntegerField(blank=True, default=150, null=True, verbose_name='Read1 length')),
                ('read2_length', models.IntegerField(blank=True, default=150, null=True, verbose_name='Read2 length')),
                ('sequencing_instrument', models.CharField(blank=True, choices=[('HX', 'HiSeqX'), ('H2500', 'HiSeq2500'), ('N500', 'NextSeq500'), ('N550', 'NextSeq550'), ('MI', 'MiSeq'), ('O', 'other')], default='HX', max_length=50, null=True, verbose_name='Sequencing instrument')),
                ('sequencing_output_mode', models.CharField(blank=True, choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], max_length=50, null=True, verbose_name='Sequencing output mode')),
                ('short_description_of_submission', models.CharField(blank=True, max_length=150, null=True, verbose_name='Short description of submission')),
                ('submission_date', models.DateField(default=datetime.date.today, verbose_name='Submission date')),
                ('number_of_lanes_requested', models.PositiveIntegerField(default=0, verbose_name='Sequencing Goal')),
                ('lane_requested_date', models.DateField(null=True)),
                ('gsc_library_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='GSC library ID')),
                ('sequencer_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sequencer ID')),
                ('sequencing_center', models.CharField(choices=[('BCCAGSC', 'BCCAGSC'), ('UBCBRC', 'UBCBRC')], default='BCCAGSC', max_length=50, null=True, verbose_name='Sequencing center')),
                ('sequencer_notes', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Sequencing notes')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pbal.PbalLibrary', verbose_name='Library')),
                ('relates_to', models.ManyToManyField(blank=True, related_name='_pbalsequencing_relates_to_+', to='pbal.PbalSequencing', verbose_name='Relates to')),
            ],
            options={
                'db_table': 'pbal_pbalsequencing',
            },
            bases=(models.Model, core.helpers.FieldValue),
        ),
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jira_ticket', models.CharField(max_length=50, verbose_name='Jira ticket')),
                ('plate_number', models.IntegerField(blank=True, null=True, verbose_name='Plate number')),
                ('plate_status', models.CharField(blank=True, choices=[('submitted', 'submitted'), ('sequenced', 'sequenced'), ('stored', 'stored')], max_length=50, null=True, verbose_name='Plate status')),
                ('plate_location', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Plate location')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pbal.PbalLibrary', verbose_name='Library')),
            ],
            options={
                'db_table': 'pbal_plate',
            },
            bases=(models.Model, core.helpers.FieldValue),
        ),
        migrations.AddField(
            model_name='pballane',
            name='sequencing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pbal.PbalSequencing', verbose_name='Sequencing'),
        ),
        migrations.AddField(
            model_name='historicalplate',
            name='library',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pbal.PbalLibrary', verbose_name='Library'),
        ),
        migrations.AddField(
            model_name='historicalpbalsequencing',
            name='library',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pbal.PbalLibrary', verbose_name='Library'),
        ),
        migrations.AddField(
            model_name='historicalpballibrarysampledetail',
            name='library',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pbal.PbalLibrary', verbose_name='Library'),
        ),
        migrations.AddField(
            model_name='historicalpballibraryquantificationandstorage',
            name='library',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pbal.PbalLibrary', verbose_name='Library'),
        ),
        migrations.AddField(
            model_name='historicalpballibraryconstructioninformation',
            name='library',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pbal.PbalLibrary', verbose_name='Library'),
        ),
        migrations.AddField(
            model_name='historicalpballane',
            name='sequencing',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pbal.PbalSequencing', verbose_name='Sequencing'),
        ),
        migrations.AlterUniqueTogether(
            name='pbalsequencing',
            unique_together=set([('library', 'sequencing_center', 'sequencing_instrument')]),
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]