# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-04 20:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pbal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pballane',
            table=None,
        ),
        migrations.AlterModelTable(
            name='pballibrary',
            table=None,
        ),
        migrations.AlterModelTable(
            name='pballibraryconstructioninformation',
            table=None,
        ),
        migrations.AlterModelTable(
            name='pballibraryquantificationandstorage',
            table=None,
        ),
        migrations.AlterModelTable(
            name='pballibrarysampledetail',
            table=None,
        ),
        migrations.AlterModelTable(
            name='pbalsequencing',
            table=None,
        ),
        migrations.AlterModelTable(
            name='plate',
            table=None,
        ),
    ]
