# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-09 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190409_1419'),
        ('pbal', '0002_auto_20190404_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbalsequencing',
            name='analysis',
            field=models.ManyToManyField(blank=True, to='core.Analysis', verbose_name='Analysis'),
        ),
    ]
