# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-06 21:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pbal', '0003_pbalsequencing_analysis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pballibrary',
            name='relates_to_tenx',
        ),
    ]
