# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-26 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbal', '0003_pbalsequencing_analysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pballibrary',
            name='relates_to_tenx',
            field=models.ManyToManyField(blank=True, related_name='pballibrary_relates_to_tenx', to='tenx.TenxLibrary', verbose_name='Relates to (Tenx)'),
        ),
    ]
