# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-09 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbal', '0004_remove_pballibrary_relates_to_tenx'),
        ('dlp', '0001_initial')
    ]

    operations = [
        migrations.AlterField(
            model_name='pballibrary',
            name='relates_to_dlp',
            field=models.ManyToManyField(blank=True, related_name='pballibrary_relates_to_dlp', to='dlp.DlpLibrary', verbose_name='Relates to (DLP)'),
        ),
    ]
